"""Daily-merge markdown report writer."""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Iterable

from .classifier import Commit
from .cherry_pick import CherryPickResult
from .file_copy import FileCopyResult
from .smoke_test import SmokeTestResult
from .canary import CanaryResult
from .drift_detector import DriftFinding


REPORTS_DIR = Path("/Users/anstudio/smedjan/audit-reports")


def render_report(
    *,
    run_start: datetime,
    run_end: datetime,
    classified: dict[str, list[Commit]],
    cp: CherryPickResult,
    fc: FileCopyResult,
    smoke: SmokeTestResult,
    canary: CanaryResult,
    drift: list[DriftFinding],
    rollback_tag: str,
    triggered_rollback: bool,
) -> str:
    md = []
    date_str = run_start.strftime("%Y-%m-%d")
    md.append(f"# Daily merge — {date_str}\n")
    md.append(f"**Run start:** {run_start.strftime('%H:%M:%S')} UTC")
    md.append(f"**Run end:**   {run_end.strftime('%H:%M:%S')} UTC")
    md.append(f"**Status:**    {'🔴 ROLLED BACK' if triggered_rollback else ('✅ green' if smoke.passed else '🟡 partial')}")
    md.append(f"**Pre-run tag:** `{rollback_tag}`\n")

    md.append("## Commits processed\n")
    md.append("| Category | Picked | Skipped | Total |")
    md.append("|---|---:|---:|---:|")
    for k, label in [("A", "feat"), ("B", "fix"), ("C", "refactor"),
                     ("D", "worker-internal"), ("E", "noise")]:
        commits = classified.get(k, [])
        picked = sum(1 for c in commits if c.short in cp.picked)
        skipped_short = {s for s, _ in cp.skipped}
        skipped = sum(1 for c in commits if c.short in skipped_short)
        if k in ("D", "E"):
            skipped = len(commits)  # not even attempted
            picked = 0
        md.append(f"| {k} — {label} | {picked} | {skipped} | {len(commits)} |")
    total_picked = len(cp.picked)
    total_skipped = len(cp.skipped) + len(classified.get("D", [])) + len(classified.get("E", []))
    md.append(f"| **Total** | **{total_picked}** | **{total_skipped}** | "
              f"**{sum(len(v) for v in classified.values())}** |\n")

    md.append("## Files synced (smedjan/)\n")
    if fc.copied:
        for f in fc.copied:
            md.append(f"- `{f}` (copied)")
    else:
        md.append("- (none)")
    if fc.skipped_no_change:
        md.append(f"\n_{len(fc.skipped_no_change)} no-change files (factory == main bytes)_")
    if fc.skipped_missing:
        md.append("\n**Missing in factory:**")
        for f in fc.skipped_missing:
            md.append(f"- `{f}`")
    md.append("")

    md.append("## Smoke test\n")
    md.append(f"`{smoke.summary()}`\n")
    if not smoke.passed:
        md.append("**FAILED endpoints:**")
        for p in smoke.base + smoke.localized:
            if p.status != 200:
                md.append(f"- `{p.url}` → {p.status} ({p.error or 'no body'})")
        for p in smoke.sacred_bytes:
            if p.error == "missing-sacred-bytes":
                md.append(f"- `{p.url}` sacred-bytes: {p.body_excerpt}")
    md.append("")

    md.append("## Canary 30 min\n")
    md.append(f"- Ticks: {len(canary.ticks)}")
    md.append(f"- Triggered: {'**yes — rollback**' if canary.triggered else 'no'}")
    if canary.trigger_reason:
        md.append(f"- Reason: {canary.trigger_reason}")
    if canary.ticks:
        max_5xx = max((t.fivex for t in canary.ticks), default=0)
        md.append(f"- Max 5xx in any minute: {max_5xx}")
    md.append("")

    if cp.skipped:
        md.append("## Skipped commits\n")
        for short, reason in cp.skipped:
            md.append(f"- `{short}` — {reason}")
        md.append("")

    if cp.halted_at:
        md.append("## Halted on conflict\n")
        md.append(f"- `{cp.halted_at}` — {cp.halt_reason}")
        md.append("")

    if drift:
        md.append("## Drift anomalies\n")
        for d in drift:
            md.append(f"- `{d.file}` — type={d.anomaly_type}, "
                      f"factory-only-commits=`{','.join(d.factory_only_hashes[:5])}`, "
                      f"factory-blob={d.factory_blob_sha}, main-blob={d.main_blob_sha}")
        md.append("")

    md.append("---\n")
    md.append("_Generated by smedjan daily_merge_\n")
    return "\n".join(md)


def write_report(date_str: str, content: str) -> Path:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    path = REPORTS_DIR / f"daily-merge-{date_str}.md"
    path.write_text(content)
    return path
