"""
CVE Alert Publisher — Daily 08:30
===================================
Publishes blog posts and Bluesky alerts for critical CVEs.

Usage:
    python -m agentindex.intelligence.cve_alert_publisher
"""

import json
import logging
import sqlite3
from datetime import datetime
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s [cve-alerts] %(message)s")
logger = logging.getLogger("cve-alerts")

SQLITE_DB = Path(__file__).parent.parent / "crypto" / "crypto_trust.db"
REPORTS_DIR = Path(__file__).parent.parent.parent / "docs" / "auto-reports"


def _init_db():
    conn = sqlite3.connect(str(SQLITE_DB))
    conn.execute("""
        CREATE TABLE IF NOT EXISTS published_cve_alerts (
            cve_id TEXT PRIMARY KEY,
            agent_name TEXT,
            severity TEXT,
            published_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            blog_slug TEXT,
            bluesky_posted BOOLEAN DEFAULT 0
        )
    """)
    conn.commit()
    conn.close()


def _get_unpublished_cves(conn, limit=5):
    """Get critical/high CVEs not yet published."""
    try:
        rows = conn.execute("""
            SELECT av.agent_name, av.cve_id, av.severity, av.description,
                   av.package_name
            FROM agent_vulnerabilities av
            LEFT JOIN published_cve_alerts pca ON av.cve_id = pca.cve_id
            WHERE pca.cve_id IS NULL
              AND av.severity IN ('CRITICAL', 'HIGH')
            ORDER BY CASE WHEN av.severity = 'CRITICAL' THEN 0 ELSE 1 END,
                     av.cve_id DESC
            LIMIT ?
        """, (limit,)).fetchall()
        return rows
    except Exception as e:
        logger.warning(f"Error fetching CVEs: {e}")
        return []


def _count_affected_agents(conn, agent_name):
    """Count agents that share dependencies with the affected agent."""
    try:
        count = conn.execute("""
            SELECT COUNT(DISTINCT ad2.agent_name)
            FROM agent_dependencies ad1
            INNER JOIN agent_dependencies ad2 ON ad1.dependency_name = ad2.dependency_name
            WHERE ad1.agent_name = ? AND ad2.agent_name != ?
        """, (agent_name, agent_name)).fetchone()
        return count[0] if count else 0
    except Exception:
        return 0


def _generate_blog_post(agent_name, cve_id, severity, description, affected_count):
    """Generate a blog post for a CVE alert."""
    now = datetime.now()
    slug = f"cve-alert-{cve_id.lower().replace('-', '-')}"

    md = f"""---
title: "Security Alert: {agent_name} — {cve_id} ({severity})"
date: {now.strftime('%Y-%m-%d')}
---

# Security Alert: {cve_id} ({severity})

**Affected agent:** {agent_name}
**Severity:** {severity}
**Detected:** {now.strftime('%B %d, %Y')}

## Summary

{description or f'A {severity} vulnerability ({cve_id}) has been identified affecting {agent_name}.'}

## Impact

- **Directly affected:** [{agent_name}](https://nerq.ai/safe/{agent_name.lower().replace('/', '').replace(' ', '-')})
- **Potentially affected via shared dependencies:** {affected_count} agents

## Recommendations

1. Check if your project depends on {agent_name}
2. Update to the latest version if a patch is available
3. Run `nerq preflight {agent_name}` to verify current trust status

## Check Your Agent

- [Safety Report for {agent_name}](https://nerq.ai/safe/{agent_name.lower().replace('/', '').replace(' ', '-')})
- [Preflight Check](https://nerq.ai/v1/preflight?target={agent_name})
- [Full Dashboard](https://nerq.ai/dashboard/{agent_name.lower().replace('/', '').replace(' ', '-')})

---

*This alert was auto-generated by [Nerq Intelligence](https://nerq.ai/security). Nerq continuously monitors {200000:,}+ AI agents for security vulnerabilities.*
"""
    return md, slug


def _publish_alert(conn, agent_name, cve_id, severity, description):
    """Publish a single CVE alert to all channels."""
    affected_count = _count_affected_agents(conn, agent_name)
    md, slug = _generate_blog_post(agent_name, cve_id, severity, description, affected_count)

    # Save blog post
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    now = datetime.now()
    filename = f"{now.strftime('%Y-%m-%d')}-{slug}.md"
    blog_path = REPORTS_DIR / filename
    blog_path.write_text(md)
    logger.info(f"  Blog post saved: {blog_path}")

    # Post to Bluesky
    bluesky_posted = False
    try:
        from agentindex.bluesky_bot import post_to_bluesky
        text = (
            f"Security Alert: {agent_name}\n"
            f"{severity} vulnerability {cve_id}\n"
            f"{affected_count} agents may be affected via shared deps.\n\n"
            f"Details: nerq.ai/safe/{agent_name.lower().replace('/', '').replace(' ', '-')}"
        )
        result = post_to_bluesky(text)
        bluesky_posted = result is not None
        if bluesky_posted:
            logger.info(f"  Bluesky alert posted for {cve_id}")
    except Exception as e:
        logger.warning(f"  Bluesky posting skipped: {e}")

    # Record as published
    conn.execute(
        "INSERT OR REPLACE INTO published_cve_alerts (cve_id, agent_name, severity, blog_slug, bluesky_posted) "
        "VALUES (?, ?, ?, ?, ?)",
        (cve_id, agent_name, severity, slug, bluesky_posted)
    )
    conn.commit()

    return {"cve_id": cve_id, "agent": agent_name, "severity": severity, "affected": affected_count, "slug": slug}


def publish_alerts(limit=5):
    """Check for and publish new CVE alerts. Returns list of published alerts."""
    _init_db()
    conn = sqlite3.connect(str(SQLITE_DB))

    cves = _get_unpublished_cves(conn, limit)
    logger.info(f"  Found {len(cves)} unpublished critical/high CVEs")

    published = []
    for r in cves:
        agent_name, cve_id, severity, description, package_name = r[0], r[1], r[2], r[3], r[4]
        try:
            result = _publish_alert(conn, agent_name, cve_id, severity, description)
            published.append(result)
            logger.info(f"  Published: {cve_id} ({severity}) for {agent_name}")
        except Exception as e:
            logger.error(f"  Error publishing {cve_id}: {e}")

    conn.close()
    return published


def main():
    logger.info("=" * 60)
    logger.info("CVE Alert Publisher — starting")
    logger.info("=" * 60)

    published = publish_alerts(limit=5)

    logger.info("")
    logger.info("=" * 60)
    logger.info("CVE Alert Publisher — COMPLETE")
    logger.info(f"  Alerts published: {len(published)}")
    for p in published:
        logger.info(f"    {p['cve_id']} ({p['severity']}): {p['agent']} ({p['affected']} affected)")
    logger.info(f"  Timestamp: {datetime.now().isoformat()}")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
