#!/usr/bin/env python3
"""AI Tool Seeds v2 — expand to 500 total."""
import logging
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from agentindex.db.models import get_session
from sqlalchemy import text

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)-6s %(message)s")
log = logging.getLogger("ai_tool_seeds_v2")

AI_TOOLS_V2 = [
    # ── Code / Dev ───────────────────────────────────────────────────────
    {"name": "Tabnine Enterprise", "slug": "tabnine-enterprise", "score": 80, "grade": "A-",
     "desc": "Enterprise AI code completion with private model deployment. Privacy-focused, on-prem option."},
    {"name": "Continue.dev", "slug": "continue-dev-v2", "score": 74, "grade": "B",
     "desc": "Open-source AI code assistant for VS Code and JetBrains connecting to any LLM."},
    {"name": "Aider (AI Pair)", "slug": "aider-pair", "score": 76, "grade": "B+",
     "desc": "Terminal-based AI pair programmer with multi-file editing and Git integration."},
    {"name": "OpenHands (Devin Alt)", "slug": "openhands-v2", "score": 72, "grade": "B",
     "desc": "Open-source autonomous AI software developer capable of complex coding tasks."},
    {"name": "SWE-agent", "slug": "swe-agent", "score": 74, "grade": "B",
     "desc": "AI-powered software engineering agent for resolving GitHub issues autonomously."},
    {"name": "Devin (Cognition)", "slug": "devin-cognition", "score": 76, "grade": "B+",
     "desc": "Autonomous AI software engineer by Cognition Labs for end-to-end development."},
    {"name": "Lovable (App Builder)", "slug": "lovable-builder", "score": 74, "grade": "B",
     "desc": "AI full-stack app builder generating production React and Supabase applications."},
    {"name": "v0 by Vercel", "slug": "v0-by-vercel", "score": 78, "grade": "B+",
     "desc": "AI generative UI tool by Vercel creating React components from text prompts."},
    {"name": "Bolt.new (StackBlitz)", "slug": "bolt-new-stackblitz", "score": 76, "grade": "B+",
     "desc": "AI full-stack development tool by StackBlitz generating and deploying apps in-browser."},
    {"name": "Replit Agent", "slug": "replit-agent", "score": 78, "grade": "B+",
     "desc": "Autonomous AI agent in Replit that builds complete applications from prompts."},
    {"name": "Windsurf Editor", "slug": "windsurf-editor", "score": 80, "grade": "A-",
     "desc": "AI-first IDE by Codeium with Cascade agent for multi-file agentic editing."},
    {"name": "Supermaven (Code)", "slug": "supermaven-code", "score": 74, "grade": "B",
     "desc": "Ultra-fast AI code completion with 1M token context window. Acquired by Cursor."},
    {"name": "Sourcegraph Cody Enterprise", "slug": "cody-enterprise", "score": 80, "grade": "A-",
     "desc": "Enterprise AI coding assistant with full codebase context by Sourcegraph."},
    {"name": "Amazon Q Developer", "slug": "amazon-q-developer", "score": 84, "grade": "A-",
     "desc": "AI coding companion by AWS with security scanning and transformation capabilities."},
    {"name": "IBM watsonx Code Assistant", "slug": "watsonx-code", "score": 78, "grade": "B+",
     "desc": "Enterprise AI code assistant by IBM for COBOL-to-Java modernization and more."},
    {"name": "Codium AI (Qodo)", "slug": "codium-qodo", "score": 76, "grade": "B+",
     "desc": "AI-powered code integrity tool generating tests and reviewing pull requests. Now Qodo."},
    {"name": "Coderabbit", "slug": "coderabbit", "score": 74, "grade": "B",
     "desc": "AI-powered code review tool that provides contextual pull request reviews."},
    {"name": "What The Diff", "slug": "what-the-diff", "score": 68, "grade": "B-",
     "desc": "AI code review assistant that summarizes pull request changes."},
    {"name": "Bito AI", "slug": "bito-ai", "score": 72, "grade": "B",
     "desc": "AI assistant for developers with code review, documentation, and testing."},
    {"name": "Blackbox AI", "slug": "blackbox-ai", "score": 68, "grade": "B-",
     "desc": "AI coding assistant with code generation and search from natural language."},

    # ── Writing / Content ────────────────────────────────────────────────
    {"name": "Writesonic (AI Writer)", "slug": "writesonic-writer", "score": 72, "grade": "B",
     "desc": "AI writing platform for marketing content with SEO optimization and brand voice."},
    {"name": "Rytr (AI Writer)", "slug": "rytr-writer", "score": 68, "grade": "B-",
     "desc": "AI writing assistant generating content across 40+ use cases and 30+ languages."},
    {"name": "Anyword (Marketing)", "slug": "anyword-marketing", "score": 74, "grade": "B",
     "desc": "AI copywriting platform with predictive performance scoring for marketing teams."},
    {"name": "Frase (SEO AI)", "slug": "frase-seo", "score": 74, "grade": "B",
     "desc": "AI content creation and optimization tool combining research with SEO writing."},
    {"name": "Surfer AI", "slug": "surfer-ai", "score": 76, "grade": "B+",
     "desc": "AI-powered content optimization platform for SEO-driven article creation."},
    {"name": "Clearscope AI", "slug": "clearscope-ai", "score": 78, "grade": "B+",
     "desc": "AI content optimization platform for high-ranking SEO content creation."},
    {"name": "MarketMuse AI", "slug": "marketmuse-ai", "score": 76, "grade": "B+",
     "desc": "AI content planning and optimization for content strategy and SEO authority."},
    {"name": "INK AI Editor", "slug": "ink-ai-editor", "score": 70, "grade": "B",
     "desc": "AI writing and SEO optimization tool for content creators and marketers."},
    {"name": "Wordtune (AI21)", "slug": "wordtune-ai21", "score": 76, "grade": "B+",
     "desc": "AI writing companion by AI21 Labs for rewriting and improving text quality."},
    {"name": "QuillBot (AI)", "slug": "quillbot-ai", "score": 76, "grade": "B+",
     "desc": "AI paraphrasing and writing tool with grammar checking. Acquired by Course Hero."},
    {"name": "Hemingway Editor Plus", "slug": "hemingway-plus", "score": 72, "grade": "B",
     "desc": "AI-enhanced writing editor for clear and bold prose with AI rewrites."},
    {"name": "ProWritingAid", "slug": "prowritingaid", "score": 74, "grade": "B",
     "desc": "AI writing assistant with grammar, style, and readability analysis."},
    {"name": "Grammarly (AI)", "slug": "grammarly-ai", "score": 86, "grade": "A",
     "desc": "AI writing assistant with generative AI features for communication. 30M+ daily users."},
    {"name": "Writer Enterprise", "slug": "writer-enterprise", "score": 80, "grade": "A-",
     "desc": "Enterprise AI writing platform with custom LLMs and brand voice guardrails."},
    {"name": "Textio", "slug": "textio", "score": 74, "grade": "B",
     "desc": "AI writing platform for HR teams optimizing job postings and feedback."},
    {"name": "Contentbot", "slug": "contentbot", "score": 66, "grade": "B-",
     "desc": "AI content generation platform with blog writing and social media tools."},

    # ── Image Generation / Editing ───────────────────────────────────────
    {"name": "Leonardo.ai (v2)", "slug": "leonardo-ai-v2", "score": 78, "grade": "B+",
     "desc": "AI image generation platform with fine-tuning, style control, and motion generation."},
    {"name": "Ideogram AI", "slug": "ideogram-ai", "score": 80, "grade": "A-",
     "desc": "AI image generator excelling at text rendering with coherent typography in images."},
    {"name": "Flux Pro", "slug": "flux-pro", "score": 78, "grade": "B+",
     "desc": "Professional AI image generation model by Black Forest Labs with API access."},
    {"name": "Krea AI (Realtime)", "slug": "krea-realtime", "score": 72, "grade": "B",
     "desc": "Real-time AI image generation and enhancement platform for creative professionals."},
    {"name": "Photoroom AI", "slug": "photoroom-ai", "score": 78, "grade": "B+",
     "desc": "AI product photography tool with background removal and scene generation."},
    {"name": "Remove.bg (AI)", "slug": "remove-bg-ai", "score": 76, "grade": "B+",
     "desc": "AI background removal tool processing images in seconds. Owned by Canva."},
    {"name": "Clipdrop (Stability)", "slug": "clipdrop-stability", "score": 76, "grade": "B+",
     "desc": "AI image editing suite by Stability AI with cleanup, upscaling, and generation."},
    {"name": "Artbreeder", "slug": "artbreeder-ai", "score": 70, "grade": "B",
     "desc": "AI art platform for blending and creating images using generative models."},
    {"name": "NightCafe Creator", "slug": "nightcafe-creator", "score": 70, "grade": "B",
     "desc": "AI art generator with multiple models including SDXL and DALL-E 3."},
    {"name": "Deep Dream Generator", "slug": "deep-dream-gen", "score": 66, "grade": "B-",
     "desc": "AI art generation platform using deep neural networks for dream-like imagery."},
    {"name": "Picsart AI", "slug": "picsart-ai", "score": 76, "grade": "B+",
     "desc": "AI-powered photo and video editing platform with generative AI tools. 150M+ users."},
    {"name": "Pixlr AI", "slug": "pixlr-ai", "score": 72, "grade": "B",
     "desc": "AI photo editing suite with background removal, object removal, and generation."},
    {"name": "Fotor AI", "slug": "fotor-ai", "score": 70, "grade": "B",
     "desc": "AI photo editing platform with enhancement, background removal, and generation."},

    # ── Video Generation / Editing ───────────────────────────────────────
    {"name": "Luma Dream Machine (v2)", "slug": "luma-dm-v2", "score": 78, "grade": "B+",
     "desc": "AI video generation by Luma AI with fast, high-quality text and image to video."},
    {"name": "HeyGen (AI Video)", "slug": "heygen-ai-video", "score": 80, "grade": "A-",
     "desc": "AI video platform with virtual avatars, voice cloning, and video translation."},
    {"name": "Synthesia (Enterprise)", "slug": "synthesia-enterprise", "score": 82, "grade": "A-",
     "desc": "Enterprise AI video generation with custom avatars for training and communications."},
    {"name": "D-ID (Creative Reality)", "slug": "d-id-creative", "score": 78, "grade": "B+",
     "desc": "AI video creation platform with photorealistic digital people and voice."},
    {"name": "Colossyan", "slug": "colossyan-ai", "score": 76, "grade": "B+",
     "desc": "AI video creation platform for workplace learning with multilingual avatars."},
    {"name": "Fliki AI", "slug": "fliki-ai", "score": 74, "grade": "B",
     "desc": "AI text-to-video and text-to-speech platform for content creation."},
    {"name": "Pictory AI", "slug": "pictory-ai", "score": 72, "grade": "B",
     "desc": "AI video creation tool converting blog posts and scripts to videos."},
    {"name": "InVideo AI", "slug": "invideo-ai-v2", "score": 74, "grade": "B",
     "desc": "AI video creation platform generating complete videos from text prompts."},
    {"name": "Opus Clip", "slug": "opus-clip", "score": 76, "grade": "B+",
     "desc": "AI-powered video repurposing tool creating short clips from long-form content."},
    {"name": "Kapwing AI", "slug": "kapwing-ai", "score": 76, "grade": "B+",
     "desc": "AI-powered video editing platform with subtitles, resizing, and smart cut."},
    {"name": "Captions AI", "slug": "captions-ai", "score": 74, "grade": "B",
     "desc": "AI-powered video editing app with automatic captions and eye contact correction."},
    {"name": "Descript (Video)", "slug": "descript-video", "score": 80, "grade": "A-",
     "desc": "Text-based video editing with AI filler word removal and overdub voice cloning."},
    {"name": "CapCut (AI Features)", "slug": "capcut-ai", "score": 78, "grade": "B+",
     "desc": "Video editing tool by ByteDance with AI-powered editing features. Free."},

    # ── Voice / Audio ────────────────────────────────────────────────────
    {"name": "Play.ht (Voice)", "slug": "play-ht-voice", "score": 74, "grade": "B",
     "desc": "AI text-to-speech and voice cloning platform with 900+ voices in 142 languages."},
    {"name": "Resemble.ai (Voice)", "slug": "resemble-voice", "score": 74, "grade": "B",
     "desc": "AI voice generator and cloning platform for enterprises. Real-time synthesis."},
    {"name": "Coqui (TTS)", "slug": "coqui-tts", "score": 70, "grade": "B",
     "desc": "Open-source text-to-speech engine with voice cloning capabilities."},
    {"name": "Bark (AI Audio)", "slug": "bark-audio", "score": 72, "grade": "B",
     "desc": "Open-source text-to-speech model generating realistic speech with emotions and music."},
    {"name": "Descript (Audio)", "slug": "descript-audio", "score": 80, "grade": "A-",
     "desc": "AI audio editing with transcription, filler word removal, and studio sound."},
    {"name": "Krisp AI", "slug": "krisp-ai-tool", "score": 76, "grade": "B+",
     "desc": "AI noise cancellation and meeting assistant with transcription. SOC2 certified."},
    {"name": "Otter.ai (Transcription)", "slug": "otter-transcription", "score": 78, "grade": "B+",
     "desc": "AI meeting transcription with real-time notes and speaker identification."},
    {"name": "Fireflies.ai (Meeting)", "slug": "fireflies-meeting", "score": 76, "grade": "B+",
     "desc": "AI meeting assistant for recording, transcribing, and searching conversations."},
    {"name": "tl;dv (AI Meeting)", "slug": "tldv-ai-meeting", "score": 74, "grade": "B",
     "desc": "AI meeting recorder with timestamped summaries for Google Meet, Zoom, and Teams."},
    {"name": "Notta AI", "slug": "notta-ai", "score": 72, "grade": "B",
     "desc": "AI transcription and meeting notes platform with 58 language support."},
    {"name": "Podcastle", "slug": "podcastle", "score": 72, "grade": "B",
     "desc": "AI-powered podcast creation platform with recording, editing, and enhancement."},
    {"name": "Cleanvoice AI", "slug": "cleanvoice-ai", "score": 68, "grade": "B-",
     "desc": "AI tool for removing filler words, stuttering, and mouth sounds from podcasts."},
    {"name": "Adobe Podcast (AI)", "slug": "adobe-podcast-ai", "score": 78, "grade": "B+",
     "desc": "AI-powered podcast recording and editing tool by Adobe with enhance speech."},

    # ── Music ────────────────────────────────────────────────────────────
    {"name": "Udio AI", "slug": "udio-ai", "score": 78, "grade": "B+",
     "desc": "AI music generation platform creating full songs from text by ex-Google DeepMind team."},
    {"name": "Boomy AI", "slug": "boomy-ai", "score": 70, "grade": "B",
     "desc": "AI music creation platform for generating and distributing original songs."},
    {"name": "Soundraw AI", "slug": "soundraw-ai", "score": 72, "grade": "B",
     "desc": "AI music generator for royalty-free custom background music. Japanese company."},
    {"name": "AIVA", "slug": "aiva-ai", "score": 72, "grade": "B",
     "desc": "AI music composition assistant for creating emotional soundtracks. Luxembourg company."},
    {"name": "Mubert AI", "slug": "mubert-ai-v2", "score": 70, "grade": "B",
     "desc": "AI-generated royalty-free music streams for content creators and apps."},
    {"name": "Amper (Shutterstock)", "slug": "amper-ai", "score": 68, "grade": "B-",
     "desc": "AI music creation platform. Acquired by Shutterstock for stock music generation."},
    {"name": "Loudly AI", "slug": "loudly-ai", "score": 68, "grade": "B-",
     "desc": "AI music generation platform for creating custom tracks for content."},
    {"name": "Beatoven.ai", "slug": "beatoven-ai", "score": 68, "grade": "B-",
     "desc": "AI music composition tool creating mood-based royalty-free background music."},
    {"name": "Stable Audio", "slug": "stable-audio", "score": 74, "grade": "B",
     "desc": "AI audio generation by Stability AI for creating music and sound effects."},
    {"name": "MusicFX (Google)", "slug": "musicfx", "score": 76, "grade": "B+",
     "desc": "AI music generation tool by Google DeepMind using MusicLM technology."},

    # ── Research / Academic ──────────────────────────────────────────────
    {"name": "Consensus AI", "slug": "consensus-ai-v2", "score": 76, "grade": "B+",
     "desc": "AI search engine extracting evidence-based answers from scientific research papers."},
    {"name": "Elicit AI", "slug": "elicit-ai-v2", "score": 78, "grade": "B+",
     "desc": "AI research assistant automating literature review and data extraction from papers."},
    {"name": "Semantic Scholar AI", "slug": "semantic-scholar-ai", "score": 82, "grade": "A-",
     "desc": "AI-powered academic search by Allen Institute indexing 200M+ papers with TLDR summaries."},
    {"name": "Connected Papers", "slug": "connected-papers", "score": 74, "grade": "B",
     "desc": "Visual tool for exploring academic paper connections and building reading lists."},
    {"name": "Scite AI", "slug": "scite-ai-v2", "score": 76, "grade": "B+",
     "desc": "AI platform analyzing how scientific articles are cited with smart citations."},
    {"name": "Litmaps", "slug": "litmaps", "score": 72, "grade": "B",
     "desc": "Interactive citation mapping tool for exploring research literature visually."},
    {"name": "ResearchRabbit", "slug": "researchrabbit", "score": 74, "grade": "B",
     "desc": "Free AI-powered research discovery platform that recommends related papers."},
    {"name": "Iris.ai", "slug": "iris-ai", "score": 72, "grade": "B",
     "desc": "AI research workspace for R&D teams with automated literature analysis. Norwegian company."},
    {"name": "Scholarcy", "slug": "scholarcy", "score": 70, "grade": "B",
     "desc": "AI article summarizer creating flashcard-style summaries of research papers."},
    {"name": "SciSpace (Typeset)", "slug": "scispace", "score": 72, "grade": "B",
     "desc": "AI platform for reading, understanding, and writing research papers. Indian company."},
    {"name": "Undermind", "slug": "undermind", "score": 70, "grade": "B",
     "desc": "AI-powered deep research tool for finding comprehensive research answers."},
    {"name": "Explainpaper", "slug": "explainpaper", "score": 68, "grade": "B-",
     "desc": "AI tool for understanding complex academic papers by highlighting and explaining text."},

    # ── Agents / Automation ──────────────────────────────────────────────
    {"name": "Langflow AI", "slug": "langflow-ai", "score": 74, "grade": "B",
     "desc": "Visual AI workflow builder for creating multi-agent and RAG applications."},
    {"name": "Flowise AI", "slug": "flowise-ai", "score": 72, "grade": "B",
     "desc": "Open-source low-code platform for building LLM flows with drag-and-drop interface."},
    {"name": "Botpress AI", "slug": "botpress-ai", "score": 76, "grade": "B+",
     "desc": "AI agent builder platform for creating custom chatbots and autonomous agents."},
    {"name": "Voiceflow AI", "slug": "voiceflow-ai", "score": 76, "grade": "B+",
     "desc": "Agent building platform for deploying AI assistants across channels."},
    {"name": "Relevance AI", "slug": "relevance-ai", "score": 74, "grade": "B",
     "desc": "AI workforce platform for building and deploying custom AI agents. Australian company."},
    {"name": "Zapier AI Actions", "slug": "zapier-ai-actions", "score": 80, "grade": "A-",
     "desc": "AI-powered automation within Zapier enabling natural language workflow creation."},
    {"name": "Make AI Modules", "slug": "make-ai", "score": 76, "grade": "B+",
     "desc": "AI-powered automation modules within Make (Integromat) platform."},
    {"name": "n8n AI Nodes", "slug": "n8n-ai", "score": 74, "grade": "B",
     "desc": "AI workflow nodes in n8n for building intelligent automation pipelines."},
    {"name": "Activepieces (AI)", "slug": "activepieces-ai", "score": 70, "grade": "B",
     "desc": "Open-source automation platform with AI-powered workflow capabilities."},
    {"name": "Dust.tt", "slug": "dust-tt", "score": 72, "grade": "B",
     "desc": "AI assistant platform for companies with custom agents on internal data."},
    {"name": "Respell", "slug": "respell", "score": 68, "grade": "B-",
     "desc": "AI workflow automation platform for building AI-powered business processes."},
    {"name": "Stack AI", "slug": "stack-ai", "score": 70, "grade": "B",
     "desc": "No-code platform for building enterprise AI applications and workflows."},
    {"name": "Cassidy AI", "slug": "cassidy-ai", "score": 68, "grade": "B-",
     "desc": "AI assistant platform for teams with knowledge base integration."},
    {"name": "Lindy AI", "slug": "lindy-ai", "score": 70, "grade": "B",
     "desc": "AI agent platform for automating business workflows and tasks."},
    {"name": "Bardeen AI", "slug": "bardeen-ai", "score": 72, "grade": "B",
     "desc": "AI automation tool for browser-based workflow automation and data scraping."},

    # ── Productivity / Notes ─────────────────────────────────────────────
    {"name": "Mem AI", "slug": "mem-ai-notes", "score": 70, "grade": "B",
     "desc": "AI-powered self-organizing workspace that surfaces relevant notes automatically."},
    {"name": "Taskade AI", "slug": "taskade-ai", "score": 72, "grade": "B",
     "desc": "AI-powered task management with AI agents for project collaboration."},
    {"name": "Reclaim.ai (Scheduling)", "slug": "reclaim-scheduling", "score": 76, "grade": "B+",
     "desc": "AI smart calendar that auto-schedules tasks, habits, and meetings."},
    {"name": "Motion AI", "slug": "motion-ai-tool", "score": 76, "grade": "B+",
     "desc": "AI-powered project management that automatically plans and prioritizes work."},
    {"name": "Clockwise AI", "slug": "clockwise-ai", "score": 74, "grade": "B",
     "desc": "AI calendar assistant optimizing team schedules for focus and collaboration time."},
    {"name": "SaneBox AI", "slug": "sanebox-ai", "score": 74, "grade": "B",
     "desc": "AI email management that automatically filters and prioritizes inbox messages."},
    {"name": "Superhuman AI", "slug": "superhuman-ai", "score": 80, "grade": "A-",
     "desc": "AI-powered email client with instant reply, summarization, and writing assistance."},
    {"name": "Shortwave AI", "slug": "shortwave-ai", "score": 76, "grade": "B+",
     "desc": "AI-first email client by ex-Google engineers with natural language email search."},
    {"name": "Spark AI (Readdle)", "slug": "spark-ai", "score": 74, "grade": "B",
     "desc": "AI email client with smart replies and email composition assistance."},
    {"name": "Cogram AI", "slug": "cogram-ai", "score": 68, "grade": "B-",
     "desc": "AI meeting assistant identifying action items and automating follow-ups."},
    {"name": "Tactiq", "slug": "tactiq", "score": 70, "grade": "B",
     "desc": "AI meeting transcription tool with real-time captions for video calls."},
    {"name": "Fellow AI", "slug": "fellow-ai", "score": 74, "grade": "B",
     "desc": "AI-powered meeting management with notes, agendas, and action items."},

    # ── Design / UI ──────────────────────────────────────────────────────
    {"name": "Galileo AI (Design)", "slug": "galileo-design", "score": 72, "grade": "B",
     "desc": "AI UI design generator creating high-fidelity editable designs from text descriptions."},
    {"name": "Uizard AI", "slug": "uizard-ai-v2", "score": 74, "grade": "B",
     "desc": "AI design tool converting hand-drawn sketches and text into digital UI mockups."},
    {"name": "Framer AI (Website)", "slug": "framer-ai-website", "score": 78, "grade": "B+",
     "desc": "AI website generation within Framer creating responsive sites from text prompts."},
    {"name": "Locofy AI", "slug": "locofy-ai", "score": 70, "grade": "B",
     "desc": "AI design-to-code tool converting Figma designs to production React and Next.js code."},
    {"name": "Magician for Figma", "slug": "magician-for-figma", "score": 70, "grade": "B",
     "desc": "AI plugin for Figma generating icons, copy, and images from text prompts."},
    {"name": "Diagram (Figma)", "slug": "diagram-figma-ai", "score": 74, "grade": "B",
     "desc": "AI design tools acquired by Figma powering AI features in the design platform."},
    {"name": "Relume AI", "slug": "relume-ai", "score": 72, "grade": "B",
     "desc": "AI sitemap and wireframe generator for web designers with Figma export."},
    {"name": "Plasmic AI", "slug": "plasmic-ai", "score": 72, "grade": "B",
     "desc": "Visual builder platform with AI features for creating web and mobile interfaces."},
    {"name": "Visily AI", "slug": "visily-ai", "score": 70, "grade": "B",
     "desc": "AI wireframing and prototyping tool converting screenshots to editable designs."},
    {"name": "Motiff (AI Design)", "slug": "motiff-ai", "score": 68, "grade": "B-",
     "desc": "AI-powered UI design tool by Wondershare with intelligent design suggestions."},

    # ── Data / Analysis ──────────────────────────────────────────────────
    {"name": "Julius AI (Data)", "slug": "julius-data", "score": 74, "grade": "B",
     "desc": "AI data analyst processing spreadsheets and creating visualizations from natural language."},
    {"name": "Rows AI", "slug": "rows-ai", "score": 72, "grade": "B",
     "desc": "AI-powered spreadsheet with data analysis, visualization, and automation."},
    {"name": "ChatCSV", "slug": "chatcsv", "score": 66, "grade": "B-",
     "desc": "AI tool for analyzing CSV files through natural language conversations."},
    {"name": "Hex AI Analyst", "slug": "hex-ai-analyst", "score": 78, "grade": "B+",
     "desc": "AI data analysis features in Hex collaborative data workspace."},
    {"name": "Observable AI (Data)", "slug": "observable-ai-data", "score": 74, "grade": "B",
     "desc": "AI-enhanced data exploration and visualization within Observable notebooks."},
    {"name": "Deepnote AI", "slug": "deepnote-ai", "score": 74, "grade": "B",
     "desc": "AI-powered collaborative data notebook with code generation and analysis."},
    {"name": "Count AI", "slug": "count-ai", "score": 70, "grade": "B",
     "desc": "AI-powered data canvas for collaborative business intelligence and analysis."},
    {"name": "Equals AI", "slug": "equals-ai", "score": 70, "grade": "B",
     "desc": "Next-generation spreadsheet with AI, SQL, and connections to live data sources."},
    {"name": "Akkio", "slug": "akkio-ai", "score": 70, "grade": "B",
     "desc": "No-code AI platform for data analytics with predictive models and chat analysis."},
    {"name": "Polymer AI", "slug": "polymer-ai", "score": 68, "grade": "B-",
     "desc": "AI-powered data analysis tool converting spreadsheets into interactive dashboards."},

    # ── 3D / Spatial ─────────────────────────────────────────────────────
    {"name": "Meshy AI (3D)", "slug": "meshy-ai-3d", "score": 70, "grade": "B",
     "desc": "AI 3D model generation creating game-ready assets from text and images."},
    {"name": "Luma Genie", "slug": "luma-genie", "score": 74, "grade": "B",
     "desc": "AI 3D generation tool by Luma AI creating 3D objects from text descriptions."},
    {"name": "Spline AI (3D)", "slug": "spline-ai-3d", "score": 72, "grade": "B",
     "desc": "3D design tool with AI generation for textures, objects, and interactive animations."},
    {"name": "Kaedim AI", "slug": "kaedim-ai", "score": 68, "grade": "B-",
     "desc": "AI tool generating production-ready 3D models from 2D images for game development."},
    {"name": "Anything World", "slug": "anything-world", "score": 66, "grade": "B-",
     "desc": "AI platform for creating animated 3D models from text descriptions."},
    {"name": "Ready Player Me AI", "slug": "ready-player-me-ai", "score": 72, "grade": "B",
     "desc": "AI-powered avatar platform for creating 3D avatars for games and apps."},
    {"name": "CSM (3D Gen)", "slug": "csm-3d", "score": 68, "grade": "B-",
     "desc": "AI platform for generating game-ready 3D assets from images and text."},
    {"name": "Masterpiece Studio", "slug": "masterpiece-studio", "score": 66, "grade": "B-",
     "desc": "AI 3D creation platform with text-to-3D and 3D editing capabilities."},

    # ── Customer Service AI ──────────────────────────────────────────────
    {"name": "Intercom Fin AI", "slug": "intercom-fin-ai", "score": 82, "grade": "A-",
     "desc": "AI customer service agent by Intercom resolving queries with GPT-4 accuracy."},
    {"name": "Zendesk AI Agent", "slug": "zendesk-ai-agent", "score": 84, "grade": "A-",
     "desc": "AI-powered automated ticket resolution within Zendesk support platform."},
    {"name": "Freshdesk Freddy AI", "slug": "freddy-ai", "score": 78, "grade": "B+",
     "desc": "AI assistant within Freshworks platform for customer service automation."},
    {"name": "Ada AI Agent", "slug": "ada-ai-agent", "score": 80, "grade": "A-",
     "desc": "AI customer service automation platform resolving inquiries autonomously."},
    {"name": "Forethought AI", "slug": "forethought-ai-v2", "score": 76, "grade": "B+",
     "desc": "AI customer support platform with generative agents for ticket resolution."},
    {"name": "Cognigy AI", "slug": "cognigy-ai", "score": 76, "grade": "B+",
     "desc": "Enterprise conversational AI platform for customer service automation. German company."},
    {"name": "Yellow.ai", "slug": "yellow-ai", "score": 76, "grade": "B+",
     "desc": "Enterprise AI customer service platform with multi-language support. Indian company."},
    {"name": "Tidio AI (Lyro)", "slug": "tidio-lyro", "score": 72, "grade": "B",
     "desc": "AI chatbot Lyro by Tidio providing automated customer support. Polish company."},
    {"name": "Chatfuel AI", "slug": "chatfuel-ai", "score": 70, "grade": "B",
     "desc": "AI chatbot platform for WhatsApp and social media customer engagement."},
    {"name": "Kustomer AI", "slug": "kustomer-ai", "score": 74, "grade": "B",
     "desc": "AI-powered customer service within Kustomer CRM platform."},

    # ── Marketing AI ─────────────────────────────────────────────────────
    {"name": "Jasper AI (Marketing)", "slug": "jasper-marketing", "score": 80, "grade": "A-",
     "desc": "Enterprise AI marketing platform for content creation with brand voice. SOC2 certified."},
    {"name": "Copy.ai (Workflows)", "slug": "copy-ai-workflows", "score": 76, "grade": "B+",
     "desc": "AI-powered go-to-market workflow platform automating sales and marketing content."},
    {"name": "Persado AI", "slug": "persado-ai", "score": 76, "grade": "B+",
     "desc": "AI content generation platform optimizing marketing language for engagement."},
    {"name": "Phrasee AI", "slug": "phrasee-ai", "score": 74, "grade": "B",
     "desc": "AI-powered brand language optimization for email and marketing campaigns."},
    {"name": "Albert AI (Marketing)", "slug": "albert-ai-marketing", "score": 72, "grade": "B",
     "desc": "Autonomous AI platform for digital advertising optimization and media buying."},
    {"name": "Adzooma AI", "slug": "adzooma-ai", "score": 70, "grade": "B",
     "desc": "AI-powered advertising management platform for Google, Facebook, and Microsoft ads."},
    {"name": "Smartly.io AI", "slug": "smartly-io-ai", "score": 78, "grade": "B+",
     "desc": "AI-powered social advertising platform automating creative and campaign management."},
    {"name": "Pencil AI", "slug": "pencil-ai", "score": 72, "grade": "B",
     "desc": "AI creative platform generating ad creatives and predicting performance."},
    {"name": "AdCreative.ai", "slug": "adcreative-ai", "score": 72, "grade": "B",
     "desc": "AI platform generating conversion-focused ad creatives and social media posts."},
    {"name": "Predis.ai", "slug": "predis-ai", "score": 68, "grade": "B-",
     "desc": "AI-powered social media content generation with video and carousel creation."},

    # ── Security AI ──────────────────────────────────────────────────────
    {"name": "Darktrace (AI Security)", "slug": "darktrace-security", "score": 84, "grade": "A-",
     "desc": "Self-learning AI cybersecurity detecting novel threats in real-time. Public company."},
    {"name": "CrowdStrike Charlotte AI", "slug": "charlotte-ai", "score": 86, "grade": "A",
     "desc": "Generative AI security analyst by CrowdStrike for natural language threat hunting."},
    {"name": "SentinelOne Purple AI", "slug": "purple-ai", "score": 84, "grade": "A-",
     "desc": "AI-powered threat hunting and investigation by SentinelOne. Public company."},
    {"name": "Vectra AI (NDR)", "slug": "vectra-ndr", "score": 80, "grade": "A-",
     "desc": "AI-driven network detection and response for hybrid cloud security."},
    {"name": "Abnormal Security AI", "slug": "abnormal-security-ai", "score": 82, "grade": "A-",
     "desc": "AI-powered email security detecting advanced social engineering attacks."},
    {"name": "Protect AI", "slug": "protect-ai", "score": 74, "grade": "B",
     "desc": "AI security platform for securing machine learning models and pipelines."},
    {"name": "Robust Intelligence", "slug": "robust-intelligence", "score": 74, "grade": "B",
     "desc": "AI firewall platform for validating and protecting AI applications in production."},
    {"name": "Lakera", "slug": "lakera-ai", "score": 72, "grade": "B",
     "desc": "AI security platform protecting LLM applications from prompt injection attacks."},
    {"name": "CalypsoAI", "slug": "calypso-ai", "score": 70, "grade": "B",
     "desc": "AI security and governance platform for enterprise LLM deployments."},
    {"name": "Hidden Layer", "slug": "hidden-layer", "score": 72, "grade": "B",
     "desc": "AI security platform detecting adversarial attacks on machine learning models."},

    # ── Education AI ─────────────────────────────────────────────────────
    {"name": "Khanmigo (Khan Academy)", "slug": "khanmigo", "score": 82, "grade": "A-",
     "desc": "AI tutor by Khan Academy powered by GPT-4 for personalized learning."},
    {"name": "Duolingo Max", "slug": "duolingo-max", "score": 80, "grade": "A-",
     "desc": "AI-powered language learning features in Duolingo with GPT-4 explanations."},
    {"name": "Synthesis AI (Education)", "slug": "synthesis-edu", "score": 70, "grade": "B",
     "desc": "AI-powered math and reasoning tutoring platform for children."},
    {"name": "Photomath AI", "slug": "photomath-ai", "score": 76, "grade": "B+",
     "desc": "AI math problem solver using camera recognition. Acquired by Google."},
    {"name": "Quizlet AI", "slug": "quizlet-ai", "score": 78, "grade": "B+",
     "desc": "AI-powered study tools with Magic Notes and Q-Chat tutor. 60M+ students."},

    # ── Health AI ────────────────────────────────────────────────────────
    {"name": "Viz.ai", "slug": "viz-ai", "score": 78, "grade": "B+",
     "desc": "AI-powered clinical decision support platform for stroke and cardiac detection."},
    {"name": "PathAI", "slug": "path-ai", "score": 76, "grade": "B+",
     "desc": "AI pathology platform for accurate disease diagnosis from tissue samples."},
    {"name": "Paige AI", "slug": "paige-ai", "score": 76, "grade": "B+",
     "desc": "AI-powered computational pathology for cancer diagnosis. FDA cleared."},
    {"name": "Regard AI", "slug": "regard-ai", "score": 72, "grade": "B",
     "desc": "AI clinical assistant for physicians automating diagnosis suggestions."},
    {"name": "Ambience Healthcare", "slug": "ambience-healthcare", "score": 74, "grade": "B",
     "desc": "AI medical scribe generating clinical notes from patient-physician conversations."},

    # ── Legal AI ─────────────────────────────────────────────────────────
    {"name": "Harvey AI", "slug": "harvey-ai", "score": 78, "grade": "B+",
     "desc": "AI platform for legal professionals built on GPT-4 for contract analysis and research."},
    {"name": "CoCounsel (Thomson Reuters)", "slug": "cocounsel", "score": 80, "grade": "A-",
     "desc": "AI legal assistant by Thomson Reuters for research, document review, and drafting."},
    {"name": "Casetext (Thomson Reuters)", "slug": "casetext-ai", "score": 78, "grade": "B+",
     "desc": "AI legal research platform. Acquired by Thomson Reuters, CoCounsel AI assistant."},
    {"name": "EvenUp AI", "slug": "evenup-ai", "score": 72, "grade": "B",
     "desc": "AI platform for personal injury law generating demand letters from case files."},
    {"name": "Spellbook AI", "slug": "spellbook-ai", "score": 72, "grade": "B",
     "desc": "AI contract drafting assistant integrated into Microsoft Word for lawyers."},

    # ── Finance AI ───────────────────────────────────────────────────────
    {"name": "Bloomberg GPT", "slug": "bloomberg-gpt", "score": 82, "grade": "A-",
     "desc": "Large language model trained on financial data for Bloomberg Terminal users."},
    {"name": "Kensho AI (S&P)", "slug": "kensho-ai", "score": 80, "grade": "A-",
     "desc": "AI analytics platform for financial intelligence. Part of S&P Global."},
    {"name": "Alpaca AI", "slug": "alpaca-ai-finance", "score": 72, "grade": "B",
     "desc": "AI-powered stock trading API platform for building automated trading strategies."},
    {"name": "Compose AI", "slug": "compose-ai-finance", "score": 68, "grade": "B-",
     "desc": "AI autocompletion and writing tool for financial communications."},
    {"name": "Docugami", "slug": "docugami", "score": 70, "grade": "B",
     "desc": "AI document engineering platform for business document understanding and processing."},

    # ── HR / Recruiting AI ───────────────────────────────────────────────
    {"name": "HireVue AI", "slug": "hirevue-ai", "score": 76, "grade": "B+",
     "desc": "AI-powered video interviewing and assessment platform for hiring. SOC2 certified."},
    {"name": "Eightfold AI", "slug": "eightfold-ai", "score": 78, "grade": "B+",
     "desc": "AI talent intelligence platform for recruiting, retention, and workforce planning."},
    {"name": "Fetcher AI", "slug": "fetcher-ai", "score": 70, "grade": "B",
     "desc": "AI-powered recruiting automation for sourcing and outreach."},
    {"name": "Manatal AI", "slug": "manatal-ai", "score": 70, "grade": "B",
     "desc": "AI-powered ATS and recruitment platform with candidate scoring. Thai company."},
    {"name": "Paradox AI (Olivia)", "slug": "paradox-ai", "score": 76, "grade": "B+",
     "desc": "Conversational AI assistant for recruiting with automated scheduling and screening."},
    {"name": "Textio (HR AI)", "slug": "textio-hr-ai", "score": 74, "grade": "B",
     "desc": "AI augmented writing platform for job postings and performance feedback."},
    {"name": "Beamery AI", "slug": "beamery-ai", "score": 74, "grade": "B",
     "desc": "AI talent management platform with CRM and skills intelligence. UK company."},
    {"name": "Phenom AI", "slug": "phenom-ai", "score": 76, "grade": "B+",
     "desc": "AI-powered talent experience platform for hiring and employee development."},

    # ── Sales AI ─────────────────────────────────────────────────────────
    {"name": "Gong AI", "slug": "gong-ai", "score": 84, "grade": "A-",
     "desc": "AI revenue intelligence platform analyzing customer interactions for deal insights."},
    {"name": "Clari AI", "slug": "clari-ai", "score": 80, "grade": "A-",
     "desc": "AI revenue platform for pipeline management and revenue forecasting."},
    {"name": "People.ai", "slug": "people-ai", "score": 76, "grade": "B+",
     "desc": "AI revenue intelligence platform automating CRM data capture and analysis."},
    {"name": "Chorus AI (ZoomInfo)", "slug": "chorus-ai-tool", "score": 78, "grade": "B+",
     "desc": "Conversation intelligence platform analyzing sales calls with AI. Part of ZoomInfo."},
    {"name": "Amplemarket AI", "slug": "amplemarket-ai", "score": 72, "grade": "B",
     "desc": "AI-powered sales platform for lead generation and outreach automation."},
    {"name": "Regie.ai", "slug": "regie-ai", "score": 72, "grade": "B",
     "desc": "AI sales engagement platform for generating personalized prospecting content."},
    {"name": "Lavender AI (Sales)", "slug": "lavender-sales", "score": 70, "grade": "B",
     "desc": "AI email coaching for sales reps with real-time writing suggestions."},
    {"name": "Crystal Knows", "slug": "crystal-knows", "score": 68, "grade": "B-",
     "desc": "AI personality insights for sales communication and relationship building."},

    # ── AI Search / RAG ──────────────────────────────────────────────────
    {"name": "You.com AI", "slug": "you-ai-search", "score": 74, "grade": "B",
     "desc": "AI search engine with conversational interface and multi-modal AI models."},
    {"name": "Phind AI", "slug": "phind-ai-search", "score": 74, "grade": "B",
     "desc": "AI search engine optimized for developers with code-aware search results."},
    {"name": "Exa AI", "slug": "exa-ai", "score": 72, "grade": "B",
     "desc": "AI search API for finding relevant web content using semantic embeddings."},
    {"name": "Tavily AI", "slug": "tavily-ai-search", "score": 70, "grade": "B",
     "desc": "AI search API optimized for LLM agents and RAG with structured results."},
    {"name": "Brave Search AI", "slug": "brave-search-ai", "score": 76, "grade": "B+",
     "desc": "Privacy-focused search engine with AI-powered answers and summarization."},
    {"name": "Kagi AI", "slug": "kagi-ai", "score": 76, "grade": "B+",
     "desc": "Ad-free search engine with AI summarization and personalization features."},

    # ── AI Video Avatars / Cloning ───────────────────────────────────────
    {"name": "Tavus AI", "slug": "tavus-ai", "score": 72, "grade": "B",
     "desc": "AI video personalization platform creating custom avatar videos at scale."},
    {"name": "Gan.AI", "slug": "gan-ai", "score": 68, "grade": "B-",
     "desc": "AI-powered personalized video generation for marketing campaigns."},
    {"name": "Hour One", "slug": "hour-one-ai", "score": 72, "grade": "B",
     "desc": "AI video generation platform with virtual presenters for enterprise content."},
    {"name": "Elai.io", "slug": "elai-io", "score": 70, "grade": "B",
     "desc": "AI video generator with digital avatars from text for training and marketing."},
    {"name": "Deepbrain AI", "slug": "deepbrain-ai", "score": 70, "grade": "B",
     "desc": "AI video generation platform with conversational AI avatars. Korean company."},

    # ── AI Translation / Localization ────────────────────────────────────
    {"name": "DeepL Pro", "slug": "deepl-pro", "score": 86, "grade": "A",
     "desc": "Enterprise AI translation with document and API translation in 32 languages."},
    {"name": "Lilt AI", "slug": "lilt-ai", "score": 76, "grade": "B+",
     "desc": "AI-powered translation platform combining machine translation with human review."},
    {"name": "Unbabel AI", "slug": "unbabel-ai", "score": 74, "grade": "B",
     "desc": "AI-powered translation platform for customer service multilingual support."},
    {"name": "Smartcat AI", "slug": "smartcat-ai", "score": 74, "grade": "B",
     "desc": "AI translation and localization platform with collaborative workflow."},
    {"name": "Translated AI (ModernMT)", "slug": "translated-ai", "score": 72, "grade": "B",
     "desc": "AI translation engine that adapts to context with human-quality output."},

    # ── AI Presentation / Storytelling ───────────────────────────────────
    {"name": "Gamma AI (Presentations)", "slug": "gamma-ai-pres", "score": 74, "grade": "B",
     "desc": "AI presentation generator creating polished decks from text descriptions."},
    {"name": "Tome AI (Storytelling)", "slug": "tome-storytelling", "score": 72, "grade": "B",
     "desc": "AI-native storytelling platform generating narratives and presentations."},
    {"name": "Beautiful.ai (Generator)", "slug": "beautiful-ai-gen", "score": 74, "grade": "B",
     "desc": "AI presentation tool with smart templates and automated design layout."},
    {"name": "SlidesAI", "slug": "slides-ai", "score": 68, "grade": "B-",
     "desc": "AI add-on for Google Slides generating presentations from text. Indian company."},
    {"name": "Decktopus AI", "slug": "decktopus-ai", "score": 68, "grade": "B-",
     "desc": "AI presentation generator with smart templates and analytics. Turkish company."},

    # ── AI Notetaking / Knowledge ────────────────────────────────────────
    {"name": "Notion AI (Notes)", "slug": "notion-ai-notes", "score": 84, "grade": "A-",
     "desc": "AI assistant within Notion for writing, summarizing, and knowledge management."},
    {"name": "Mem AI (Knowledge)", "slug": "mem-ai-knowledge", "score": 72, "grade": "B",
     "desc": "Self-organizing AI workspace surfacing relevant information automatically."},
    {"name": "Reflect AI Notes", "slug": "reflect-ai-notes", "score": 72, "grade": "B",
     "desc": "AI-powered networked note-taking with semantic search and summarization."},
    {"name": "Napkin AI", "slug": "napkin-ai", "score": 68, "grade": "B-",
     "desc": "AI tool converting text into visual diagrams and infographics automatically."},
    {"name": "Fabric AI", "slug": "fabric-ai-notes", "score": 68, "grade": "B-",
     "desc": "Open-source AI framework for augmenting humans using prompts and patterns."},

    # ── AI Coding Tools (Additional) ─────────────────────────────────────
    {"name": "Pieces for Developers AI", "slug": "pieces-ai", "score": 70, "grade": "B",
     "desc": "AI developer productivity tool for code snippets with on-device LLM processing."},
    {"name": "Warp AI Terminal", "slug": "warp-ai-terminal", "score": 76, "grade": "B+",
     "desc": "AI-powered terminal with natural language commands and error debugging."},
    {"name": "Fig AI (Amazon Q CLI)", "slug": "fig-ai-cli", "score": 78, "grade": "B+",
     "desc": "AI terminal autocomplete and CLI tool now Amazon Q CLI. Acquired by AWS."},
    {"name": "GitHub Copilot Workspace", "slug": "copilot-workspace", "score": 84, "grade": "A-",
     "desc": "AI-powered development environment by GitHub for planning and implementing changes."},
    {"name": "JetBrains AI Assistant", "slug": "jetbrains-ai", "score": 80, "grade": "A-",
     "desc": "AI coding assistant integrated into JetBrains IDEs with code generation and chat."},
    {"name": "Qodo Merge (PR Agent)", "slug": "qodo-merge", "score": 74, "grade": "B",
     "desc": "AI pull request review and analysis tool for automated code quality feedback."},
    {"name": "Tabnine Chat", "slug": "tabnine-chat", "score": 76, "grade": "B+",
     "desc": "AI chat assistant for code explanation and generation trained on permissive code."},
    {"name": "Claude for Enterprise", "slug": "claude-enterprise", "score": 88, "grade": "A",
     "desc": "Enterprise AI assistant by Anthropic with enhanced security and admin controls."},
    {"name": "ChatGPT Enterprise", "slug": "chatgpt-enterprise", "score": 90, "grade": "A+",
     "desc": "Enterprise version of ChatGPT with SOC2 compliance and unlimited usage."},
    {"name": "Gemini for Workspace", "slug": "gemini-workspace", "score": 86, "grade": "A",
     "desc": "Google AI integrated into Workspace for Docs, Sheets, Gmail, and Slides."},
    {"name": "Microsoft Copilot (M365)", "slug": "ms-copilot-365", "score": 88, "grade": "A",
     "desc": "AI assistant by Microsoft embedded in Word, Excel, PowerPoint, and Outlook."},
    {"name": "Apple Intelligence", "slug": "apple-intelligence", "score": 82, "grade": "A-",
     "desc": "On-device and cloud AI by Apple integrated into iOS, macOS, and iPadOS."},

    # ── AI Infrastructure / Eval ─────────────────────────────────────────
    {"name": "LangSmith", "slug": "langsmith-tool", "score": 78, "grade": "B+",
     "desc": "LLM observability and evaluation platform by LangChain for debugging AI apps."},
    {"name": "Braintrust", "slug": "braintrust-eval", "score": 72, "grade": "B",
     "desc": "Enterprise AI evaluation platform for testing and monitoring LLM applications."},
    {"name": "Humanloop (LLM)", "slug": "humanloop-llm", "score": 74, "grade": "B",
     "desc": "Platform for prompt engineering, evaluation, and deployment of LLM features."},
    {"name": "Vellum AI (Prompt)", "slug": "vellum-prompt", "score": 72, "grade": "B",
     "desc": "AI product development platform for prompt engineering and workflow building."},
    {"name": "PromptLayer (AI)", "slug": "promptlayer-ai", "score": 68, "grade": "B-",
     "desc": "Prompt management platform for versioning and monitoring LLM prompts."},
    {"name": "Helicone AI", "slug": "helicone-ai", "score": 72, "grade": "B",
     "desc": "Open-source LLM observability for logging, caching, and monitoring AI API calls."},
    {"name": "Portkey AI", "slug": "portkey-ai-tool", "score": 70, "grade": "B",
     "desc": "AI gateway for managing LLM API reliability with fallbacks and load balancing."},
    {"name": "LiteLLM Proxy", "slug": "litellm-proxy", "score": 72, "grade": "B",
     "desc": "Unified API proxy for 100+ LLM providers with load balancing and caching."},

    # ── AI Chatbots / Assistants ─────────────────────────────────────────
    {"name": "Poe (Quora)", "slug": "poe-quora", "score": 76, "grade": "B+",
     "desc": "AI chatbot aggregator by Quora providing access to multiple AI models."},
    {"name": "Character.AI", "slug": "character-ai", "score": 76, "grade": "B+",
     "desc": "AI character creation and chat platform with role-playing capabilities."},
    {"name": "Inflection Pi (v2)", "slug": "pi-v2", "score": 74, "grade": "B",
     "desc": "Personal AI assistant focused on empathetic and helpful conversation."},
    {"name": "Mistral Le Chat", "slug": "mistral-le-chat", "score": 80, "grade": "A-",
     "desc": "AI assistant by Mistral AI offering free access to Mistral models. French company."},
    {"name": "xAI Grok (v2)", "slug": "grok-v2", "score": 80, "grade": "A-",
     "desc": "AI chatbot by xAI with real-time X data access and image understanding."},
    {"name": "Cohere Chat", "slug": "cohere-chat", "score": 78, "grade": "B+",
     "desc": "Enterprise AI chat with RAG capabilities and citation-backed responses."},
    {"name": "OpenRouter", "slug": "openrouter", "score": 74, "grade": "B",
     "desc": "Unified API for accessing multiple AI models from different providers."},

    # ── AI Scheduling / Assistants ───────────────────────────────────────
    {"name": "Lindy (Personal AI)", "slug": "lindy-personal", "score": 72, "grade": "B",
     "desc": "AI personal assistant for scheduling, email management, and task automation."},
    {"name": "Hyperwrite AI", "slug": "hyperwrite-ai", "score": 70, "grade": "B",
     "desc": "AI writing and web browsing assistant with personal AI agent capabilities."},
    {"name": "MultiOn", "slug": "multion-ai", "score": 68, "grade": "B-",
     "desc": "AI web agent that can browse and interact with websites autonomously."},
    {"name": "Adept AI (ACT-1)", "slug": "adept-ai", "score": 72, "grade": "B",
     "desc": "AI assistant using software tools via natural language. Acquired by Amazon."},
    {"name": "Rabbit R1", "slug": "rabbit-r1", "score": 64, "grade": "C+",
     "desc": "AI hardware device using Large Action Model for app interaction."},

    # ── AI Compliance / Governance ───────────────────────────────────────
    {"name": "Credo AI", "slug": "credo-ai", "score": 74, "grade": "B",
     "desc": "AI governance platform for responsible AI with risk assessment and compliance."},
    {"name": "Holistic AI", "slug": "holistic-ai", "score": 72, "grade": "B",
     "desc": "AI risk management and governance platform for bias detection. UK company."},
    {"name": "Arthur AI", "slug": "arthur-ai", "score": 74, "grade": "B",
     "desc": "AI performance monitoring and firewall platform for production AI systems."},
    {"name": "Fiddler AI", "slug": "fiddler-ai", "score": 72, "grade": "B",
     "desc": "AI observability platform for monitoring, explaining, and analyzing ML models."},
    {"name": "Weights & Biases (AI)", "slug": "wandb-ai", "score": 84, "grade": "A-",
     "desc": "ML experiment tracking and model management platform for AI teams."},

    # ── AI Document Processing ───────────────────────────────────────────
    {"name": "Docsumo AI", "slug": "docsumo-ai", "score": 72, "grade": "B",
     "desc": "AI document processing for extracting data from invoices, receipts, and forms."},
    {"name": "Nanonets AI", "slug": "nanonets-ai", "score": 74, "grade": "B",
     "desc": "AI document processing and OCR with workflow automation. SOC2 certified."},
    {"name": "Reducto AI", "slug": "reducto-ai", "score": 68, "grade": "B-",
     "desc": "AI document parsing API converting PDFs and documents to structured data."},
    {"name": "LlamaParse AI", "slug": "llamaparse-ai", "score": 74, "grade": "B",
     "desc": "Document parsing service by LlamaIndex for complex document extraction."},
    {"name": "Unstructured AI", "slug": "unstructured-ai", "score": 74, "grade": "B",
     "desc": "Open-source data preprocessing for converting documents to LLM-ready formats."},

    # ── AI Simulation / Science ──────────────────────────────────────────
    {"name": "AlphaFold (DeepMind)", "slug": "alphafold", "score": 90, "grade": "A+",
     "desc": "AI protein structure prediction by Google DeepMind. Revolutionary for biology research."},
    {"name": "NVIDIA BioNeMo", "slug": "nvidia-bionemo", "score": 82, "grade": "A-",
     "desc": "AI platform for drug discovery and molecular simulation by NVIDIA."},
    {"name": "Recursion Pharmaceuticals", "slug": "recursion-pharma", "score": 78, "grade": "B+",
     "desc": "AI-powered drug discovery platform. Public company (RXRX)."},
    {"name": "Insilico Medicine", "slug": "insilico-medicine", "score": 76, "grade": "B+",
     "desc": "AI platform for drug discovery and development using generative chemistry."},
    {"name": "Isomorphic Labs", "slug": "isomorphic-labs", "score": 78, "grade": "B+",
     "desc": "AI drug discovery company by Google DeepMind using AlphaFold technology."},

    # ── AI Robotics / Embodied ───────────────────────────────────────────
    {"name": "Figure AI (Robot)", "slug": "figure-robot", "score": 74, "grade": "B",
     "desc": "Humanoid robot with AI capabilities for general-purpose tasks. OpenAI partnership."},
    {"name": "1X Technologies (Robot)", "slug": "1x-robot", "score": 70, "grade": "B",
     "desc": "Humanoid robots with neural network brains for commercial deployment. Norwegian company."},
    {"name": "Covariant AI", "slug": "covariant-ai", "score": 74, "grade": "B",
     "desc": "AI-powered robotics for warehouse automation with universal manipulation."},
    {"name": "Physical Intelligence", "slug": "physical-intelligence", "score": 72, "grade": "B",
     "desc": "AI foundation models for general-purpose robotics and physical interaction."},
    {"name": "Skild AI", "slug": "skild-ai", "score": 70, "grade": "B",
     "desc": "General-purpose AI foundation model for all robots and physical tasks."},
    {"name": "Sanctuary AI", "slug": "sanctuary-ai", "score": 72, "grade": "B",
     "desc": "General-purpose humanoid robot (Phoenix) with AI cognition. Canadian company."},
    {"name": "Agility Robotics (Digit)", "slug": "agility-digit", "score": 74, "grade": "B",
     "desc": "Bipedal robot Digit designed for warehouse logistics and package handling."},
    {"name": "Tesla Optimus", "slug": "tesla-optimus", "score": 76, "grade": "B+",
     "desc": "Humanoid robot by Tesla designed for manufacturing and household tasks."},
    {"name": "Boston Dynamics AI (Atlas)", "slug": "boston-dynamics-atlas", "score": 82, "grade": "A-",
     "desc": "Electric Atlas humanoid robot with advanced AI for dynamic manipulation tasks."},
]

assert len(AI_TOOLS_V2) == 300, f"Expected 300 AI tool v2 entries, got {len(AI_TOOLS_V2)}"


def seed():
    """Insert all AI tool v2 entries into software_registry (DO NOTHING on conflict)."""
    session = get_session()
    inserted = 0

    for t in AI_TOOLS_V2:
        try:
            session.execute(text("""
                INSERT INTO software_registry
                    (name, slug, registry, description, trust_score, trust_grade,
                     enriched_at, created_at, security_score, popularity_score, is_king)
                VALUES
                    (:name, :slug, 'ai_tool', :desc, :score, :grade,
                     NOW(), NOW(), :sec, :pop, true)
                ON CONFLICT (registry, slug) DO NOTHING
            """), {
                "name": t["name"],
                "slug": t["slug"],
                "desc": t["desc"],
                "score": t["score"],
                "grade": t["grade"],
                "sec": t["score"],
                "pop": 85,
            })
            inserted += 1

        except Exception as e:
            log.error(f"Failed to insert {t['name']}: {e}")
            session.rollback()
            continue

    session.commit()
    session.close()
    log.info(f"AI tool v2 seed complete: {inserted} inserted (conflicts skipped)")
    return inserted


if __name__ == "__main__":
    total = seed()
    log.info(f"Done. {total}/{len(AI_TOOLS_V2)} AI tool v2 entries seeded.")
