#!/usr/bin/env python3
"""AI Tool Seeds — seed 200 AI tools into software_registry."""
import logging
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from agentindex.db.models import get_session
from sqlalchemy import text

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)-6s %(message)s")
log = logging.getLogger("ai_tool_seeds")

AI_TOOLS = [
    # ── LLMs/Chatbots ────────────────────────────────────────────────────
    {"name": "ChatGPT", "slug": "chatgpt", "score": 92, "grade": "A+",
     "desc": "AI chatbot and assistant powered by GPT-4 and GPT-4o. Developed by OpenAI, 200M+ weekly users."},
    {"name": "Claude", "slug": "claude", "score": 90, "grade": "A+",
     "desc": "AI assistant by Anthropic focused on safety and helpfulness. Constitutional AI approach, enterprise-ready."},
    {"name": "Gemini", "slug": "gemini", "score": 90, "grade": "A+",
     "desc": "Multimodal AI model and assistant by Google DeepMind. Integrated into Google products, Alphabet (GOOGL)."},
    {"name": "Grok", "slug": "grok", "score": 78, "grade": "B+",
     "desc": "AI chatbot by xAI with real-time access to X (Twitter) data. Founded by Elon Musk."},
    {"name": "Llama (Meta)", "slug": "llama-meta", "score": 88, "grade": "A",
     "desc": "Open-source large language model by Meta. Free for commercial use, widely adopted by developers."},
    {"name": "Mistral AI", "slug": "mistral-ai", "score": 85, "grade": "A",
     "desc": "Open-weight AI models from French AI company. Mistral Large and Mixtral, EU AI leader."},
    {"name": "Cohere", "slug": "cohere", "score": 82, "grade": "A-",
     "desc": "Enterprise AI platform for NLP with Command and Embed models. SOC2 Type II certified."},
    {"name": "Pi (Inflection)", "slug": "pi-inflection", "score": 75, "grade": "B+",
     "desc": "Personal AI assistant by Inflection AI. Conversational and empathetic, acquired by Microsoft."},
    {"name": "Perplexity AI", "slug": "perplexity-ai", "score": 82, "grade": "A-",
     "desc": "AI-powered search engine combining LLMs with real-time web search. Backed by Amazon, NVIDIA."},
    {"name": "DeepSeek", "slug": "deepseek", "score": 78, "grade": "B+",
     "desc": "Open-source AI models by Chinese AI lab. DeepSeek-V2 competitive with top models at lower cost."},
    {"name": "Qwen (Alibaba)", "slug": "qwen-alibaba", "score": 80, "grade": "A-",
     "desc": "Open-source LLM series by Alibaba Cloud. Multilingual, strong on Chinese and English tasks."},
    {"name": "Gemma (Google)", "slug": "gemma-google", "score": 84, "grade": "A-",
     "desc": "Open-source lightweight AI models by Google. Built from Gemini technology for developer use."},
    {"name": "Phi (Microsoft)", "slug": "phi-microsoft", "score": 83, "grade": "A-",
     "desc": "Small language model series by Microsoft Research. Strong performance for size, open-source."},
    {"name": "Command R+ (Cohere)", "slug": "command-r-plus", "score": 80, "grade": "A-",
     "desc": "Enterprise RAG-optimized LLM by Cohere. Designed for retrieval-augmented generation workflows."},
    {"name": "Yi (01.AI)", "slug": "yi-01ai", "score": 74, "grade": "B",
     "desc": "Open-source bilingual LLM by 01.AI, founded by Kai-Fu Lee. Strong multilingual capabilities."},

    # ── Coding Assistants ─────────────────────────────────────────────────
    {"name": "Cursor", "slug": "cursor", "score": 84, "grade": "A-",
     "desc": "AI-first code editor built on VS Code with inline AI editing and chat. Rapidly growing developer tool."},
    {"name": "GitHub Copilot", "slug": "github-copilot", "score": 90, "grade": "A+",
     "desc": "AI pair programmer by GitHub/Microsoft using OpenAI models. Integrated into VS Code and IDEs."},
    {"name": "Windsurf (Codeium)", "slug": "windsurf", "score": 80, "grade": "A-",
     "desc": "AI-powered code editor by Codeium with agentic coding capabilities. Free tier available."},
    {"name": "Tabnine", "slug": "tabnine", "score": 78, "grade": "B+",
     "desc": "AI code completion tool trained on permissively licensed code. Privacy-focused, on-prem option."},
    {"name": "Amazon CodeWhisperer (Q Developer)", "slug": "amazon-codewhisperer", "score": 84, "grade": "A-",
     "desc": "AI coding companion by AWS. Free for individual use, security scanning included."},
    {"name": "Devin", "slug": "devin", "score": 72, "grade": "B",
     "desc": "Autonomous AI software engineer by Cognition Labs. Can plan, code, and debug independently."},
    {"name": "Lovable", "slug": "lovable", "score": 72, "grade": "B",
     "desc": "AI-powered full-stack app builder generating React and Supabase applications from prompts."},
    {"name": "v0", "slug": "v0-vercel", "score": 76, "grade": "B+",
     "desc": "AI UI component generator by Vercel. Creates React/Next.js components from text and image prompts."},
    {"name": "Bolt", "slug": "bolt-new", "score": 74, "grade": "B",
     "desc": "AI-powered full-stack web development tool by StackBlitz. Generates and deploys apps in-browser."},
    {"name": "Replit AI", "slug": "replit-ai", "score": 78, "grade": "B+",
     "desc": "AI coding assistant integrated into Replit IDE with code generation and debugging."},
    {"name": "Continue", "slug": "continue-dev", "score": 72, "grade": "B",
     "desc": "Open-source AI code assistant for VS Code and JetBrains. Connects to any LLM."},
    {"name": "Cline", "slug": "cline", "score": 72, "grade": "B",
     "desc": "Open-source autonomous AI coding agent for VS Code. Can edit files, run commands, and browse."},
    {"name": "Aider", "slug": "aider", "score": 74, "grade": "B",
     "desc": "Open-source AI pair programming tool for terminal. Works with any LLM, Git-aware."},
    {"name": "Sweep", "slug": "sweep-ai", "score": 68, "grade": "B-",
     "desc": "AI-powered code review and bug fix tool. Generates pull requests from GitHub issues."},
    {"name": "Sourcegraph Cody", "slug": "sourcegraph-cody", "score": 78, "grade": "B+",
     "desc": "AI coding assistant by Sourcegraph with codebase-aware context. Enterprise-focused."},
    {"name": "Supermaven", "slug": "supermaven", "score": 72, "grade": "B",
     "desc": "Fast AI code completion tool with 1M token context window. Low latency predictions."},
    {"name": "Pieces for Developers", "slug": "pieces-dev", "score": 68, "grade": "B-",
     "desc": "AI-powered developer productivity tool for code snippets and context management."},
    {"name": "Claude Code", "slug": "claude-code", "score": 82, "grade": "A-",
     "desc": "Agentic coding tool by Anthropic for terminal-based AI development. Understands full codebases."},
    {"name": "OpenHands (OpenDevin)", "slug": "openhands", "score": 70, "grade": "B",
     "desc": "Open-source AI software developer agent. Can write code, run commands, and browse the web."},

    # ── Image Generation ──────────────────────────────────────────────────
    {"name": "Midjourney", "slug": "midjourney", "score": 82, "grade": "A-",
     "desc": "AI image generation tool known for high-quality artistic outputs. Independent research lab."},
    {"name": "DALL-E 3", "slug": "dall-e-3", "score": 86, "grade": "A",
     "desc": "AI image generation model by OpenAI. Integrated into ChatGPT and Microsoft products."},
    {"name": "Stable Diffusion", "slug": "stable-diffusion", "score": 80, "grade": "A-",
     "desc": "Open-source image generation model by Stability AI. Widely adopted, runs locally."},
    {"name": "Leonardo AI", "slug": "leonardo-ai", "score": 76, "grade": "B+",
     "desc": "AI image generation platform for creative professionals. Fine-tuning and style control."},
    {"name": "Ideogram", "slug": "ideogram", "score": 78, "grade": "B+",
     "desc": "AI image generator excelling at text rendering in images. Founded by ex-Google Brain researchers."},
    {"name": "Flux", "slug": "flux-ai", "score": 76, "grade": "B+",
     "desc": "Open-source image generation model by Black Forest Labs. State-of-the-art quality, flexible licensing."},
    {"name": "Adobe Firefly", "slug": "adobe-firefly", "score": 86, "grade": "A",
     "desc": "AI image generation model by Adobe trained on licensed content. Integrated into Creative Cloud."},
    {"name": "Canva AI (Magic Design)", "slug": "canva-ai", "score": 82, "grade": "A-",
     "desc": "AI-powered design features in Canva including text-to-image and Magic Eraser."},
    {"name": "Playground AI", "slug": "playground-ai", "score": 70, "grade": "B",
     "desc": "Free AI image generation and editing platform. Mixed models approach."},
    {"name": "Recraft", "slug": "recraft", "score": 72, "grade": "B",
     "desc": "AI design tool for generating and editing vector and raster images. Professional design focus."},
    {"name": "Krea AI", "slug": "krea-ai", "score": 68, "grade": "B-",
     "desc": "Real-time AI image generation and enhancement platform. Creative tools for designers."},
    {"name": "NightCafe", "slug": "nightcafe", "score": 68, "grade": "B-",
     "desc": "AI art generator using multiple models including Stable Diffusion and DALL-E."},
    {"name": "Tensor.Art", "slug": "tensor-art", "score": 64, "grade": "C+",
     "desc": "AI image generation platform with model hosting and community features."},

    # ── Video Generation ──────────────────────────────────────────────────
    {"name": "RunwayML", "slug": "runwayml", "score": 82, "grade": "A-",
     "desc": "AI creative suite for video generation and editing. Gen-3 Alpha video model, used in Hollywood."},
    {"name": "Pika", "slug": "pika", "score": 76, "grade": "B+",
     "desc": "AI video generation platform creating and editing videos from text and images. Stanford-founded."},
    {"name": "Sora (OpenAI)", "slug": "sora", "score": 82, "grade": "A-",
     "desc": "AI video generation model by OpenAI creating realistic videos from text prompts."},
    {"name": "Kling", "slug": "kling-ai", "score": 72, "grade": "B",
     "desc": "AI video generation model by Kuaishou Technology. High-quality video from text and images."},
    {"name": "Luma Dream Machine", "slug": "luma-dream-machine", "score": 76, "grade": "B+",
     "desc": "AI video generation tool by Luma AI. Fast, high-quality video generation from text."},
    {"name": "Synthesia", "slug": "synthesia", "score": 80, "grade": "A-",
     "desc": "AI video generation platform with virtual avatars for business communications. SOC2 certified."},
    {"name": "HeyGen", "slug": "heygen", "score": 78, "grade": "B+",
     "desc": "AI video generator with virtual avatars and voice cloning. Used for marketing and training."},
    {"name": "D-ID", "slug": "d-id", "score": 76, "grade": "B+",
     "desc": "AI-powered video creation platform with talking avatars. Israeli company, enterprise features."},
    {"name": "Haiper", "slug": "haiper", "score": 68, "grade": "B-",
     "desc": "AI video generation tool by former Google DeepMind researchers. Text-to-video and image-to-video."},
    {"name": "Invideo AI", "slug": "invideo-ai", "score": 72, "grade": "B",
     "desc": "AI-powered video creation tool that generates full videos from text prompts."},
    {"name": "Veo (Google)", "slug": "veo-google", "score": 82, "grade": "A-",
     "desc": "AI video generation model by Google DeepMind. High-fidelity, cinematic-quality video from text."},
    {"name": "Minimax (Hailuo)", "slug": "minimax-hailuo", "score": 72, "grade": "B",
     "desc": "AI video generation platform by Chinese AI company Minimax. Free high-quality video generation."},

    # ── Audio/Voice ───────────────────────────────────────────────────────
    {"name": "ElevenLabs", "slug": "elevenlabs", "score": 82, "grade": "A-",
     "desc": "AI voice synthesis and cloning platform. Realistic text-to-speech in multiple languages."},
    {"name": "Suno", "slug": "suno", "score": 78, "grade": "B+",
     "desc": "AI music generation platform creating full songs from text prompts. Cambridge-based startup."},
    {"name": "Udio", "slug": "udio", "score": 76, "grade": "B+",
     "desc": "AI music generation tool by former Google DeepMind researchers. High-quality audio from text."},
    {"name": "Mubert", "slug": "mubert", "score": 68, "grade": "B-",
     "desc": "AI-generated royalty-free music platform for content creators and businesses."},
    {"name": "Descript AI", "slug": "descript-ai", "score": 80, "grade": "A-",
     "desc": "AI-powered audio and video editing with transcription and voice cloning by Descript."},
    {"name": "AssemblyAI", "slug": "assemblyai", "score": 80, "grade": "A-",
     "desc": "Speech-to-text API with AI-powered audio intelligence. SOC2 Type II certified."},
    {"name": "Whisper (OpenAI)", "slug": "whisper-openai", "score": 86, "grade": "A",
     "desc": "Open-source speech recognition model by OpenAI. Multi-language support, runs locally."},
    {"name": "Speechify", "slug": "speechify", "score": 74, "grade": "B",
     "desc": "AI text-to-speech platform for reading articles, PDFs, and documents aloud."},
    {"name": "Resemble AI", "slug": "resemble-ai", "score": 72, "grade": "B",
     "desc": "AI voice generator and cloning platform for enterprises. SOC2 certified."},
    {"name": "Play.ht", "slug": "play-ht", "score": 72, "grade": "B",
     "desc": "AI text-to-speech and voice cloning platform. 900+ AI voices in 142 languages."},
    {"name": "Bark (Suno)", "slug": "bark-suno", "score": 72, "grade": "B",
     "desc": "Open-source text-to-speech model by Suno AI. Generates realistic speech with emotions."},

    # ── AI Writing ────────────────────────────────────────────────────────
    {"name": "Jasper", "slug": "jasper-ai", "score": 78, "grade": "B+",
     "desc": "AI writing and marketing platform for enterprise content creation. SOC2 Type II certified."},
    {"name": "Copy.ai", "slug": "copy-ai", "score": 74, "grade": "B",
     "desc": "AI-powered copywriting and content generation platform. Enterprise workflow automation."},
    {"name": "Writesonic", "slug": "writesonic", "score": 70, "grade": "B",
     "desc": "AI writing platform for articles, ads, and product descriptions. Multiple AI models."},
    {"name": "Anyword", "slug": "anyword", "score": 72, "grade": "B",
     "desc": "AI copywriting platform with predictive performance scoring for marketing content."},
    {"name": "Rytr", "slug": "rytr", "score": 66, "grade": "B-",
     "desc": "AI writing assistant for generating content across use cases. Affordable pricing."},
    {"name": "Sudowrite", "slug": "sudowrite", "score": 70, "grade": "B",
     "desc": "AI writing tool designed for fiction writers and storytelling. Creative writing focus."},
    {"name": "Wordtune", "slug": "wordtune", "score": 74, "grade": "B",
     "desc": "AI writing companion by AI21 Labs for rewriting and improving text."},
    {"name": "Writer", "slug": "writer-ai", "score": 78, "grade": "B+",
     "desc": "Enterprise AI writing platform with brand voice and compliance controls. SOC2 Type II certified."},
    {"name": "Lex", "slug": "lex-ai", "score": 66, "grade": "B-",
     "desc": "AI-powered writing tool for long-form content with intelligent suggestions."},

    # ── Research/Search ───────────────────────────────────────────────────
    {"name": "NotebookLM", "slug": "notebooklm", "score": 84, "grade": "A-",
     "desc": "AI research assistant by Google that analyzes uploaded documents. Generates audio overviews."},
    {"name": "Elicit", "slug": "elicit", "score": 76, "grade": "B+",
     "desc": "AI research assistant for finding and analyzing academic papers. Ought (nonprofit) developed."},
    {"name": "Consensus", "slug": "consensus-ai", "score": 74, "grade": "B",
     "desc": "AI-powered academic search engine extracting findings from scientific papers."},
    {"name": "Scite", "slug": "scite-ai", "score": 74, "grade": "B",
     "desc": "AI platform for discovering and evaluating scientific articles with smart citations."},
    {"name": "Semantic Scholar", "slug": "semantic-scholar", "score": 82, "grade": "A-",
     "desc": "AI-powered academic search engine by Allen Institute for AI. Free, indexes 200M+ papers."},
    {"name": "You.com", "slug": "you-com", "score": 72, "grade": "B",
     "desc": "AI search engine with conversational interface and multiple AI models."},
    {"name": "Phind", "slug": "phind", "score": 72, "grade": "B",
     "desc": "AI search engine optimized for developers and programming questions."},
    {"name": "Tavily", "slug": "tavily", "score": 68, "grade": "B-",
     "desc": "AI search API optimized for LLM agents and RAG applications. Developer-focused."},

    # ── Design AI ─────────────────────────────────────────────────────────
    {"name": "Galileo AI", "slug": "galileo-ai", "score": 70, "grade": "B",
     "desc": "AI UI design generator creating editable designs from text descriptions."},
    {"name": "Uizard", "slug": "uizard", "score": 72, "grade": "B",
     "desc": "AI-powered UI design tool converting sketches and text to digital designs. Danish company."},
    {"name": "Framer AI", "slug": "framer-ai", "score": 76, "grade": "B+",
     "desc": "AI-powered website generation within Framer platform. Creates responsive sites from prompts."},
    {"name": "Locofy", "slug": "locofy", "score": 68, "grade": "B-",
     "desc": "AI tool converting Figma and Adobe XD designs to production-ready code."},
    {"name": "Builder.io (Visual Copilot)", "slug": "builder-io-ai", "score": 72, "grade": "B",
     "desc": "AI-powered design-to-code tool converting Figma designs to clean code."},
    {"name": "Magician (Figma)", "slug": "magician-figma", "score": 68, "grade": "B-",
     "desc": "AI design plugin for Figma generating icons, copy, and images from text prompts."},
    {"name": "Diagram (Figma AI)", "slug": "diagram-ai", "score": 72, "grade": "B",
     "desc": "AI design tools acquired by Figma. Powers AI features in Figma platform."},
    {"name": "Relume", "slug": "relume", "score": 70, "grade": "B",
     "desc": "AI-powered sitemap and wireframe generator for web designers. Figma integration."},

    # ── Data/Analytics AI ─────────────────────────────────────────────────
    {"name": "Julius", "slug": "julius-ai", "score": 72, "grade": "B",
     "desc": "AI data analyst that can analyze spreadsheets and create visualizations from natural language."},
    {"name": "Hex AI", "slug": "hex-ai", "score": 76, "grade": "B+",
     "desc": "AI-powered data analysis features within Hex collaborative data workspace."},
    {"name": "Observable AI", "slug": "observable-ai", "score": 72, "grade": "B",
     "desc": "AI-enhanced data exploration and visualization platform built on Observable notebooks."},
    {"name": "Databricks AI", "slug": "databricks-ai", "score": 88, "grade": "A",
     "desc": "AI and ML capabilities within Databricks platform including MosaicML and Dolly models."},
    {"name": "Obviously AI", "slug": "obviously-ai", "score": 66, "grade": "B-",
     "desc": "No-code AI platform for building predictive models from CSV data."},
    {"name": "MindsDB", "slug": "mindsdb", "score": 72, "grade": "B",
     "desc": "Open-source AI layer for databases enabling ML predictions via SQL queries."},

    # ── Agent Frameworks ──────────────────────────────────────────────────
    {"name": "AutoGPT", "slug": "autogpt", "score": 70, "grade": "B",
     "desc": "Open-source autonomous AI agent framework. Pioneered the AI agent concept, large community."},
    {"name": "CrewAI", "slug": "crewai", "score": 74, "grade": "B",
     "desc": "Framework for orchestrating role-playing AI agents working as a team. Open-source."},
    {"name": "LangChain", "slug": "langchain", "score": 82, "grade": "A-",
     "desc": "Framework for building applications powered by LLMs. Most popular LLM framework, Python and JS."},
    {"name": "LlamaIndex", "slug": "llamaindex", "score": 80, "grade": "A-",
     "desc": "Data framework for LLM applications with RAG capabilities. Widely adopted for knowledge retrieval."},
    {"name": "Haystack", "slug": "haystack", "score": 76, "grade": "B+",
     "desc": "Open-source LLM framework for building NLP pipelines by deepset. Production-ready."},
    {"name": "Semantic Kernel", "slug": "semantic-kernel", "score": 82, "grade": "A-",
     "desc": "AI orchestration SDK by Microsoft for integrating LLMs into applications. Open-source."},
    {"name": "Mastra", "slug": "mastra", "score": 66, "grade": "B-",
     "desc": "TypeScript framework for building AI agents and workflows. Open-source, early stage."},
    {"name": "Agno", "slug": "agno", "score": 66, "grade": "B-",
     "desc": "Framework for building multimodal AI agents. Open-source, Python-based."},
    {"name": "AutoGen (Microsoft)", "slug": "autogen", "score": 78, "grade": "B+",
     "desc": "Multi-agent conversation framework by Microsoft Research. Open-source, enterprise patterns."},
    {"name": "Langflow", "slug": "langflow", "score": 72, "grade": "B",
     "desc": "Visual framework for building multi-agent and RAG applications. DataStax-backed."},
    {"name": "Flowise", "slug": "flowise", "score": 70, "grade": "B",
     "desc": "Open-source low-code tool for building LLM flows and chatbots with drag-and-drop."},
    {"name": "Dify", "slug": "dify", "score": 74, "grade": "B",
     "desc": "Open-source LLM app development platform combining AI workflow and RAG pipeline."},
    {"name": "Vercel AI SDK", "slug": "vercel-ai-sdk", "score": 80, "grade": "A-",
     "desc": "TypeScript toolkit for building AI-powered applications. By Vercel, supports multiple providers."},

    # ── MLOps ─────────────────────────────────────────────────────────────
    {"name": "Weights & Biases", "slug": "weights-biases", "score": 84, "grade": "A-",
     "desc": "ML experiment tracking, dataset versioning, and model management platform. SOC2 Type II certified."},
    {"name": "MLflow", "slug": "mlflow", "score": 82, "grade": "A-",
     "desc": "Open-source ML lifecycle management platform by Databricks. Model tracking and deployment."},
    {"name": "Comet ML", "slug": "comet-ml", "score": 76, "grade": "B+",
     "desc": "ML experiment management and model production monitoring platform. SOC2 certified."},
    {"name": "Neptune.ai", "slug": "neptune-ai", "score": 74, "grade": "B",
     "desc": "Experiment tracking and model management for ML teams. SOC2 Type II certified."},
    {"name": "Determined AI", "slug": "determined-ai", "score": 72, "grade": "B",
     "desc": "Open-source deep learning training platform. Acquired by Hewlett Packard Enterprise."},
    {"name": "Hugging Face", "slug": "hugging-face", "score": 88, "grade": "A",
     "desc": "AI community platform hosting 500K+ models and 100K+ datasets. The GitHub of machine learning."},
    {"name": "Replicate", "slug": "replicate", "score": 78, "grade": "B+",
     "desc": "Platform for running open-source AI models via API. SOC2 Type II certified."},
    {"name": "Modal", "slug": "modal", "score": 76, "grade": "B+",
     "desc": "Cloud platform for running AI/ML workloads with serverless GPU infrastructure."},
    {"name": "Together AI", "slug": "together-ai", "score": 78, "grade": "B+",
     "desc": "Cloud platform for running and fine-tuning open-source AI models. Fast inference."},
    {"name": "Anyscale", "slug": "anyscale", "score": 78, "grade": "B+",
     "desc": "Platform for scaling AI applications built on Ray. SOC2 Type II certified."},

    # ── Speech/NLP ────────────────────────────────────────────────────────
    {"name": "AI21 Labs", "slug": "ai21-labs", "score": 78, "grade": "B+",
     "desc": "AI company building enterprise-grade LLMs including Jamba model. Israeli company, B2B focus."},
    {"name": "Deepgram", "slug": "deepgram", "score": 78, "grade": "B+",
     "desc": "AI speech recognition and text-to-speech platform. SOC2 Type II certified, enterprise-grade."},
    {"name": "Rev AI", "slug": "rev-ai", "score": 76, "grade": "B+",
     "desc": "Speech-to-text API powered by AI. Part of Rev.com, widely used for transcription."},
    {"name": "Glean", "slug": "glean", "score": 80, "grade": "A-",
     "desc": "AI-powered enterprise search platform connecting all company knowledge. SOC2/ISO 27001 certified."},
    {"name": "Unstructured", "slug": "unstructured", "score": 72, "grade": "B",
     "desc": "Open-source data preprocessing for LLMs. Converts PDFs, images, and docs to LLM-ready data."},

    # ── Robotics/Embodied AI ──────────────────────────────────────────────
    {"name": "Figure", "slug": "figure-ai", "score": 72, "grade": "B",
     "desc": "Humanoid robot company developing general-purpose robots. Backed by Microsoft, OpenAI, NVIDIA."},
    {"name": "Boston Dynamics (AI)", "slug": "boston-dynamics-ai", "score": 82, "grade": "A-",
     "desc": "Advanced robotics company with Atlas and Spot robots. Owned by Hyundai, AI-powered locomotion."},
    {"name": "Waymo", "slug": "waymo", "score": 85, "grade": "A",
     "desc": "Autonomous driving technology company by Alphabet. Operating robotaxi service in multiple US cities."},
    {"name": "Tesla FSD", "slug": "tesla-fsd", "score": 76, "grade": "B+",
     "desc": "Full Self-Driving AI system by Tesla using vision-only neural networks. Beta in customer vehicles."},
    {"name": "Cruise", "slug": "cruise", "score": 70, "grade": "B",
     "desc": "Autonomous vehicle company, subsidiary of General Motors. Paused operations, restructuring."},
    {"name": "1X Technologies", "slug": "1x-technologies", "score": 68, "grade": "B-",
     "desc": "Norwegian robotics company developing humanoid robots. Backed by OpenAI, commercial deployments."},

    # ── Security AI ───────────────────────────────────────────────────────
    {"name": "Darktrace", "slug": "darktrace-ai", "score": 82, "grade": "A-",
     "desc": "AI cybersecurity platform using self-learning AI for threat detection. Public company (DARK.L)."},
    {"name": "CrowdStrike AI", "slug": "crowdstrike-ai", "score": 86, "grade": "A",
     "desc": "AI-powered endpoint security by CrowdStrike. Charlotte AI for natural language security queries."},
    {"name": "SentinelOne AI", "slug": "sentinelone-ai", "score": 84, "grade": "A-",
     "desc": "AI-powered cybersecurity platform with Purple AI for threat hunting. Public company (S)."},
    {"name": "Vectra AI", "slug": "vectra-ai", "score": 78, "grade": "B+",
     "desc": "AI-driven network detection and response platform for cybersecurity."},
    {"name": "Abnormal Security", "slug": "abnormal-security", "score": 80, "grade": "A-",
     "desc": "AI-powered email security platform detecting advanced attacks. SOC2 Type II certified."},

    # ── AI Productivity/Misc ──────────────────────────────────────────────
    {"name": "Notion AI", "slug": "notion-ai-tool", "score": 82, "grade": "A-",
     "desc": "AI assistant integrated into Notion workspace for writing, summarizing, and brainstorming."},
    {"name": "Otter.ai", "slug": "otter-ai", "score": 76, "grade": "B+",
     "desc": "AI meeting transcription and note-taking assistant. Real-time transcription for meetings."},
    {"name": "Fireflies.ai", "slug": "fireflies-ai", "score": 74, "grade": "B",
     "desc": "AI meeting assistant for recording, transcribing, and searching voice conversations."},
    {"name": "tl;dv", "slug": "tldv", "score": 72, "grade": "B",
     "desc": "AI meeting recorder and transcription tool for Google Meet, Zoom, and Teams."},
    {"name": "Krisp", "slug": "krisp", "score": 74, "grade": "B",
     "desc": "AI-powered noise cancellation and meeting assistant. SOC2 Type II certified."},
    {"name": "Gamma AI", "slug": "gamma-ai", "score": 72, "grade": "B",
     "desc": "AI-powered presentation, document, and webpage creator from text prompts."},
    {"name": "Tome AI", "slug": "tome-ai", "score": 70, "grade": "B",
     "desc": "AI-powered storytelling and presentation generation platform."},
    {"name": "Beautiful.ai (AI)", "slug": "beautiful-ai-tool", "score": 72, "grade": "B",
     "desc": "AI presentation tool with smart slide templates and automated design suggestions."},
    {"name": "Mem AI", "slug": "mem-ai-tool", "score": 68, "grade": "B-",
     "desc": "AI-powered self-organizing workspace and knowledge management tool."},
    {"name": "Cogram", "slug": "cogram", "score": 66, "grade": "B-",
     "desc": "AI meeting assistant that takes notes and identifies action items. German startup."},
    {"name": "Reclaim AI", "slug": "reclaim-ai-tool", "score": 72, "grade": "B",
     "desc": "AI-powered smart calendar and scheduling assistant. Acquired by Dropbox in 2024."},
    {"name": "Granola", "slug": "granola-ai", "score": 68, "grade": "B-",
     "desc": "AI notepad for meetings that enhances your notes with AI transcription context."},
    {"name": "Raycast AI", "slug": "raycast-ai", "score": 76, "grade": "B+",
     "desc": "AI-powered productivity launcher for macOS with built-in ChatGPT and API access."},
    {"name": "Liner AI", "slug": "liner-ai", "score": 66, "grade": "B-",
     "desc": "AI-powered search and content curation tool highlighting relevant web information."},
    {"name": "Warp AI", "slug": "warp-ai", "score": 74, "grade": "B",
     "desc": "AI-powered terminal with built-in AI for command suggestions and error debugging."},
    {"name": "Fig (Amazon Q CLI)", "slug": "fig-ai", "score": 78, "grade": "B+",
     "desc": "AI-powered terminal autocomplete and CLI tool. Acquired by AWS, now Amazon Q CLI."},

    # ── AI Translation ────────────────────────────────────────────────────
    {"name": "DeepL", "slug": "deepl", "score": 86, "grade": "A",
     "desc": "AI-powered translation service known for natural-sounding translations. German company, 32 languages."},
    {"name": "Google Translate (AI)", "slug": "google-translate-ai", "score": 88, "grade": "A",
     "desc": "Neural machine translation service by Google supporting 130+ languages. Free and API access."},
    {"name": "Papago (Naver)", "slug": "papago", "score": 74, "grade": "B",
     "desc": "AI translation service by Naver, strong in Asian languages. Korean tech company."},

    # ── AI Photo/Image Editing ────────────────────────────────────────────
    {"name": "Photoroom", "slug": "photoroom", "score": 76, "grade": "B+",
     "desc": "AI photo editing app for background removal and product photography. French company."},
    {"name": "Remove.bg", "slug": "remove-bg", "score": 76, "grade": "B+",
     "desc": "AI-powered background removal tool for images. Owned by Canva (Kaleido.ai)."},
    {"name": "Lensa AI", "slug": "lensa-ai", "score": 64, "grade": "C+",
     "desc": "AI photo editing app known for AI avatar generation. Developed by Prisma Labs."},
    {"name": "Luminar Neo", "slug": "luminar-neo", "score": 74, "grade": "B",
     "desc": "AI-powered photo editing software by Skylum. Creative AI tools for photographers."},
    {"name": "Topaz Labs", "slug": "topaz-labs", "score": 76, "grade": "B+",
     "desc": "AI image and video enhancement tools for upscaling, denoising, and sharpening."},
    {"name": "Magnific AI", "slug": "magnific-ai", "score": 72, "grade": "B",
     "desc": "AI image upscaler and enhancer using generative AI for hallucinated detail."},
    {"name": "ClipDrop", "slug": "clipdrop", "score": 76, "grade": "B+",
     "desc": "AI-powered image editing suite by Stability AI. Background removal, cleanup, and generation."},

    # ── AI 3D/Spatial ─────────────────────────────────────────────────────
    {"name": "Meshy", "slug": "meshy", "score": 68, "grade": "B-",
     "desc": "AI 3D model generation tool creating 3D assets from text and images. Game dev focused."},
    {"name": "Luma AI (3D)", "slug": "luma-ai-3d", "score": 74, "grade": "B",
     "desc": "AI-powered 3D capture and NeRF platform for creating photorealistic 3D scenes."},
    {"name": "Spline AI", "slug": "spline-ai", "score": 70, "grade": "B",
     "desc": "3D design tool with AI generation capabilities for textures, objects, and animations."},
    {"name": "Kaedim", "slug": "kaedim", "score": 66, "grade": "B-",
     "desc": "AI tool for generating production-ready 3D models from 2D images."},
    {"name": "Tripo AI", "slug": "tripo-ai", "score": 64, "grade": "C+",
     "desc": "AI 3D model generation from text and images. Fast generation, growing community."},

    # ── AI Customer Service ───────────────────────────────────────────────
    {"name": "Ada", "slug": "ada-ai", "score": 78, "grade": "B+",
     "desc": "AI-powered customer service automation platform. SOC2 Type II certified."},
    {"name": "Forethought", "slug": "forethought", "score": 74, "grade": "B",
     "desc": "AI-powered customer support automation with generative AI agents. SOC2 certified."},
    {"name": "Intercom Fin", "slug": "intercom-fin", "score": 80, "grade": "A-",
     "desc": "AI customer service agent by Intercom using GPT-4. Resolves support queries automatically."},
    {"name": "Zendesk AI", "slug": "zendesk-ai", "score": 82, "grade": "A-",
     "desc": "AI-powered customer service features within Zendesk platform. Automated ticket resolution."},
    {"name": "Sierra AI", "slug": "sierra-ai", "score": 74, "grade": "B",
     "desc": "Conversational AI platform for customer experience. Founded by ex-Salesforce and ex-Google leaders."},

    # ── AI Marketing ──────────────────────────────────────────────────────
    {"name": "Synthflow", "slug": "synthflow", "score": 66, "grade": "B-",
     "desc": "AI voice agent platform for automated phone calls and customer interactions."},
    {"name": "Bland AI", "slug": "bland-ai", "score": 64, "grade": "C+",
     "desc": "AI phone calling platform for automating business phone conversations at scale."},
    {"name": "Instantly", "slug": "instantly-ai", "score": 70, "grade": "B",
     "desc": "AI-powered cold email outreach platform with unlimited email accounts and warmup."},
    {"name": "Lavender", "slug": "lavender-ai", "score": 68, "grade": "B-",
     "desc": "AI email coaching tool helping sales reps write better emails with real-time suggestions."},

    # ── AI Knowledge/RAG ──────────────────────────────────────────────────
    {"name": "Pinecone", "slug": "pinecone", "score": 82, "grade": "A-",
     "desc": "Vector database for building AI applications with semantic search. SOC2 Type II certified."},
    {"name": "Weaviate", "slug": "weaviate", "score": 78, "grade": "B+",
     "desc": "Open-source vector database for AI applications and semantic search. SOC2 certified."},
    {"name": "Chroma", "slug": "chroma-db", "score": 74, "grade": "B",
     "desc": "Open-source embedding database for AI applications. Simple, lightweight vector store."},
    {"name": "Qdrant", "slug": "qdrant", "score": 76, "grade": "B+",
     "desc": "Open-source vector similarity search engine. Rust-based, high performance, cloud and self-hosted."},
    {"name": "Milvus (Zilliz)", "slug": "milvus", "score": 78, "grade": "B+",
     "desc": "Open-source vector database for AI applications. Cloud-managed by Zilliz, CNCF project."},

    # ── AI Document Processing ────────────────────────────────────────────
    {"name": "Docsumo", "slug": "docsumo", "score": 70, "grade": "B",
     "desc": "AI document processing platform for extracting data from invoices and forms. SOC2 certified."},
    {"name": "Nanonets", "slug": "nanonets", "score": 72, "grade": "B",
     "desc": "AI document processing and OCR platform with workflow automation. SOC2 certified."},
    {"name": "Reducto", "slug": "reducto", "score": 66, "grade": "B-",
     "desc": "AI-powered document parsing API converting PDFs and documents to structured data."},
    {"name": "LlamaParse", "slug": "llamaparse", "score": 72, "grade": "B",
     "desc": "Document parsing service by LlamaIndex for extracting data from complex documents."},
    {"name": "Mathpix", "slug": "mathpix", "score": 72, "grade": "B",
     "desc": "AI-powered tool for converting images of math equations and documents to LaTeX and text."},
    {"name": "ChatPDF", "slug": "chatpdf", "score": 66, "grade": "B-",
     "desc": "AI tool for chatting with PDF documents using natural language questions."},

    # ── AI Hardware/Chips ─────────────────────────────────────────────────
    {"name": "Groq", "slug": "groq", "score": 78, "grade": "B+",
     "desc": "AI inference company with custom LPU chips for ultra-fast LLM inference. GroqCloud API."},
    {"name": "Cerebras", "slug": "cerebras", "score": 76, "grade": "B+",
     "desc": "AI compute company with wafer-scale chips for training and inference. Cloud inference API."},
    {"name": "SambaNova", "slug": "sambanova", "score": 74, "grade": "B",
     "desc": "AI platform company with custom hardware and software for enterprise AI. SOC2 certified."},

    # ── AI Coding/No-Code Builders ────────────────────────────────────────
    {"name": "Galileo (LLM Eval)", "slug": "galileo-llm", "score": 70, "grade": "B",
     "desc": "LLM evaluation and observability platform for monitoring AI application quality."},
    {"name": "Braintrustdata", "slug": "braintrustdata", "score": 70, "grade": "B",
     "desc": "Enterprise AI evaluation platform for testing and monitoring LLM applications."},
    {"name": "Promptlayer", "slug": "promptlayer", "score": 66, "grade": "B-",
     "desc": "Prompt engineering platform for managing, versioning, and monitoring LLM prompts."},
    {"name": "Helicone", "slug": "helicone", "score": 70, "grade": "B",
     "desc": "Open-source LLM observability platform for logging, monitoring, and debugging AI apps."},
    {"name": "Portkey", "slug": "portkey", "score": 68, "grade": "B-",
     "desc": "AI gateway and observability platform for managing LLM API calls and reliability."},
    {"name": "LiteLLM", "slug": "litellm", "score": 72, "grade": "B",
     "desc": "Open-source unified API for calling 100+ LLM providers with load balancing and fallbacks."},
]

assert len(AI_TOOLS) == 200, f"Expected 200 AI tool entries, got {len(AI_TOOLS)}"


def seed():
    """Upsert all AI tool entries into software_registry."""
    session = get_session()
    inserted = 0

    for t in AI_TOOLS:
        try:
            session.execute(text("""
                INSERT INTO software_registry
                    (name, slug, registry, description, trust_score, trust_grade,
                     enriched_at, created_at, security_score, popularity_score, is_king)
                VALUES
                    (:name, :slug, 'ai_tool', :desc, :score, :grade,
                     NOW(), NOW(), :sec, :pop, true)
                ON CONFLICT (registry, slug) DO UPDATE SET
                    description = EXCLUDED.description,
                    trust_score = EXCLUDED.trust_score,
                    trust_grade = EXCLUDED.trust_grade,
                    security_score = EXCLUDED.security_score,
                    popularity_score = EXCLUDED.popularity_score,
                    is_king = true,
                    enriched_at = NOW()
            """), {
                "name": t["name"],
                "slug": t["slug"],
                "desc": t["desc"],
                "score": t["score"],
                "grade": t["grade"],
                "sec": t["score"],
                "pop": 85,
            })
            inserted += 1

        except Exception as e:
            log.error(f"Failed to upsert {t['name']}: {e}")
            session.rollback()
            continue

    session.commit()
    session.close()
    log.info(f"AI tool seed complete: {inserted} upserted")
    return inserted


if __name__ == "__main__":
    total = seed()
    log.info(f"Done. {total}/{len(AI_TOOLS)} AI tools seeded.")
