#!/usr/bin/env python3
"""Chrome Seeds — seed top 500 Chrome extensions into software_registry as Kings.
No public API exists, so we use a curated seed list with trust scores."""
import logging, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from agentindex.db.models import get_session
from sqlalchemy import text

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)-6s %(message)s")
log = logging.getLogger("chrome_seeds")


def _grade(score: int) -> str:
    if score >= 90: return "A+"
    if score >= 80: return "A"
    if score >= 70: return "B+"
    if score >= 60: return "B"
    if score >= 50: return "C+"
    if score >= 40: return "C"
    return "D"


# fmt: off
# Each: (name, slug, description, trust_score, security_score, popularity_score)
EXTENSIONS = [
    # ── Ad Blockers ──────────────────────────────────────────────────────
    ("uBlock Origin", "ublock-origin",
     "Efficient wide-spectrum content blocker. Open source, lightweight, uses less memory than other blockers. By Raymond Hill.",
     90, 92, 95),
    ("Adblock Plus", "adblock-plus",
     "Free ad blocker for Chrome. Blocks banners, pop-ups, tracking, and malware. 'Acceptable Ads' program. By eyeo GmbH.",
     82, 80, 92),
    ("AdGuard AdBlocker", "adguard-adblocker",
     "Ad blocker that effectively blocks all types of ads including video ads, pop-ups, and banners. By AdGuard Software Ltd.",
     84, 85, 88),
    ("Ghostery", "ghostery",
     "Privacy-focused ad and tracker blocker. Visualizes trackers on every website. Open source. By Ghostery GmbH.",
     86, 88, 82),
    ("AdBlock", "adblock",
     "Most popular Chrome ad blocker. Blocks ads on YouTube, Facebook, and across the web. By getadblock.com.",
     80, 78, 90),
    ("Stands Fair AdBlocker", "stands-fair-adblocker",
     "Free ad blocker that blocks video ads, banners, and pop-ups. Donates part of revenue to charity.",
     68, 65, 62),
    ("uBlock", "ublock",
     "General purpose content blocker forked from uBlock Origin. Lightweight and efficient.",
     72, 74, 58),
    ("Adblocker Ultimate", "adblocker-ultimate",
     "Free ad blocker with no 'acceptable ads'. Removes all ads including YouTube video ads.",
     70, 68, 65),
    ("Poper Blocker", "poper-blocker",
     "Pop-up and overlay blocker for Chrome. Blocks pop-ups, pop-unders, and overlays.",
     66, 64, 68),
    ("Fair AdBlocker", "fair-adblocker",
     "Blocks annoying ads, pop-ups, and trackers. Whitelists non-intrusive ads by default.",
     65, 63, 60),

    # ── Password Managers ────────────────────────────────────────────────
    ("1Password", "1password",
     "Secure password manager by AgileBits. Stores passwords, credit cards, and secure notes. SOC2 certified.",
     88, 92, 82),
    ("Bitwarden", "bitwarden",
     "Open-source password manager. End-to-end encrypted. Free tier available. SOC2 and SOC3 audited.",
     90, 94, 80),
    ("LastPass", "lastpass",
     "Password manager with autofill and password generator. By LogMeIn/GoTo. Freemium model.",
     75, 70, 88),
    ("Dashlane", "dashlane",
     "Password manager and digital wallet. Includes VPN and dark web monitoring. SOC2 Type II certified.",
     82, 85, 78),
    ("NordPass", "nordpass",
     "Password manager by Nord Security. Zero-knowledge architecture. Audited by Cure53.",
     80, 84, 72),
    ("Keeper", "keeper",
     "Enterprise password manager with zero-knowledge security. SOC2 and ISO 27001 certified.",
     82, 88, 70),
    ("RoboForm", "roboform",
     "Password manager and form filler. AES-256 encryption. Available since 1999.",
     74, 76, 68),
    ("Enpass", "enpass",
     "Offline password manager. Data stored locally or in your own cloud. One-time purchase option.",
     76, 80, 58),
    ("Norton Password Manager", "norton-password-manager",
     "Free password manager by Gen Digital (formerly NortonLifeLock). Cloud-synced vault.",
     72, 74, 72),
    ("Zoho Vault", "zoho-vault",
     "Password manager for teams and enterprises. Part of Zoho suite. SOC2 certified.",
     74, 78, 55),

    # ── Privacy ──────────────────────────────────────────────────────────
    ("Privacy Badger", "privacy-badger",
     "Tracker blocker by EFF. Learns to block invisible trackers automatically. Open source.",
     88, 90, 78),
    ("DuckDuckGo Privacy Essentials", "duckduckgo-privacy-essentials",
     "Privacy protection by DuckDuckGo. Tracker blocking, encryption enforcement, and private search.",
     86, 88, 82),
    ("HTTPS Everywhere", "https-everywhere",
     "Forces HTTPS connections where available. By EFF. Note: largely superseded by browser built-ins.",
     82, 88, 75),
    ("ClearURLs", "clearurls",
     "Removes tracking elements from URLs. Open source. Strips UTM parameters and tracking tokens.",
     84, 86, 62),
    ("Decentraleyes", "decentraleyes",
     "Local CDN emulator protecting privacy by intercepting CDN requests. Open source.",
     82, 84, 60),
    ("Cookie AutoDelete", "cookie-autodelete",
     "Automatically deletes cookies from closed tabs. Whitelist support. Open source.",
     78, 80, 65),
    ("uMatrix", "umatrix",
     "Advanced firewall and privacy tool by Raymond Hill. Point-and-click matrix-based filtering.",
     85, 88, 55),
    ("NoScript", "noscript",
     "JavaScript, Flash, and plugin blocker for security. Ported from Firefox. Open source.",
     84, 88, 58),
    ("Disconnect", "disconnect",
     "Tracker blocker and private search tool. Visualizes and blocks invisible trackers.",
     78, 80, 62),
    ("TrackMeNot", "trackmenot",
     "Protects against search data profiling by issuing randomized search queries. Open source.",
     72, 74, 45),
    ("Canvas Blocker", "canvas-blocker",
     "Blocks canvas fingerprinting used to track users across websites.",
     76, 80, 48),
    ("Privacy Possum", "privacy-possum",
     "Reduces and falsifies data gathered by tracking companies. Open source.",
     74, 76, 42),

    # ── Productivity ─────────────────────────────────────────────────────
    ("Grammarly", "grammarly",
     "AI-powered writing assistant. Grammar, spelling, punctuation, and style checking. By Grammarly Inc.",
     82, 75, 95),
    ("Todoist", "todoist",
     "Task management and to-do list extension. Add tasks from any website. By Doist.",
     78, 80, 75),
    ("Notion Web Clipper", "notion-web-clipper",
     "Save web pages and content directly to Notion workspace. By Notion Labs.",
     80, 82, 78),
    ("Evernote Web Clipper", "evernote-web-clipper",
     "Clip web pages, articles, and PDFs to Evernote. Annotate and organize clippings.",
     76, 78, 80),
    ("Momentum", "momentum",
     "New tab dashboard with focus, to-do, and daily inspiration. Customizable background photos.",
     74, 72, 82),
    ("Google Keep", "google-keep",
     "Quick note-taking extension by Google. Save pages, images, and text to Google Keep.",
     82, 85, 80),
    ("Pocket", "pocket",
     "Save articles, videos, and web pages for later reading. By Mozilla. Offline access.",
     80, 82, 78),
    ("Toggl Track", "toggl-track",
     "Time tracking extension. One-click timer integrates with 100+ tools. By Toggl.",
     76, 78, 68),
    ("Clockify", "clockify",
     "Free time tracker and timesheet. Track work hours across projects. 100% free tier.",
     74, 76, 65),
    ("Loom", "loom",
     "Screen and video recorder for async communication. Record, share, and get feedback. By Loom/Atlassian.",
     80, 78, 82),
    ("Calendly", "calendly",
     "Meeting scheduling extension. Detect available times and insert scheduling links.",
     78, 80, 72),
    ("Pushbullet", "pushbullet",
     "Connect devices for notifications, file sharing, and messaging between phone and computer.",
     72, 68, 70),
    ("StayFocusd", "stayfocusd",
     "Productivity extension that restricts time spent on time-wasting websites.",
     70, 72, 65),
    ("Forest", "forest",
     "Gamified focus timer. Plant virtual trees while staying focused. Pomodoro-style.",
     72, 74, 62),
    ("Marinara Pomodoro Timer", "marinara-pomodoro",
     "Flexible Pomodoro technique timer. Customizable work and break intervals.",
     68, 70, 55),
    ("RescueTime", "rescuetime",
     "Automatic time tracking and productivity monitoring. Detailed reports and insights.",
     74, 70, 60),
    ("Session Buddy", "session-buddy",
     "Tab and session manager. Save, restore, and organize browser sessions.",
     72, 74, 68),
    ("Taskade", "taskade",
     "AI-powered workspace for tasks, notes, and collaboration. Real-time sync across devices.",
     70, 72, 58),
    ("Any.do", "any-do",
     "Task management and to-do list extension. Calendar integration and daily planner.",
     72, 74, 62),
    ("Workflowy", "workflowy",
     "Infinitely nested list tool for notes, tasks, and brainstorming. Simple and powerful.",
     70, 72, 55),

    # ── Developer Tools ──────────────────────────────────────────────────
    ("React Developer Tools", "react-developer-tools",
     "Official React debugging tools by Meta. Inspect React component hierarchy, props, and state.",
     88, 85, 88),
    ("Vue.js Devtools", "vuejs-devtools",
     "Official Vue.js debugging extension. Inspect components, Vuex store, and Vue Router.",
     86, 84, 78),
    ("Redux DevTools", "redux-devtools",
     "Debug Redux state changes. Time-travel debugging and action replay. Open source.",
     84, 82, 75),
    ("Angular DevTools", "angular-devtools",
     "Official Angular debugging tools by Google. Component explorer and profiler.",
     82, 84, 68),
    ("Lighthouse", "lighthouse",
     "Web page quality auditor by Google. Performance, accessibility, SEO, and best practices analysis.",
     88, 90, 78),
    ("JSON Viewer", "json-viewer",
     "Format and syntax-highlight JSON responses in the browser. Collapsible tree view.",
     78, 76, 82),
    ("JSON Formatter", "json-formatter",
     "Auto-format JSON data with syntax highlighting. Makes API responses readable.",
     76, 74, 78),
    ("Wappalyzer", "wappalyzer",
     "Technology profiler that identifies frameworks, CMS, and tools used on websites.",
     80, 76, 78),
    ("Postman Interceptor", "postman-interceptor",
     "Capture and sync cookies and requests with Postman. API development companion.",
     78, 75, 72),
    ("Tampermonkey", "tampermonkey",
     "Userscript manager for custom JavaScript injection. Most popular userscript manager for Chrome.",
     80, 68, 88),
    ("Stylus", "stylus",
     "Custom CSS manager. Apply user styles to websites. Open source fork of Stylish.",
     82, 80, 72),
    ("ColorZilla", "colorzilla",
     "Color picker and eyedropper. Extract colors from any web page. Gradient generator.",
     76, 74, 80),
    ("WhatFont", "whatfont",
     "Identify fonts on web pages with a single click. Shows font family, size, and weight.",
     74, 72, 75),
    ("Web Developer", "web-developer",
     "Toolbar with various web development tools. Disable JavaScript, inspect CSS, validate HTML.",
     78, 76, 70),
    ("Octotree", "octotree",
     "GitHub code tree browser. Navigate repositories with a sidebar file explorer.",
     76, 74, 62),
    ("GitHub File Icons", "github-file-icons",
     "Add file type icons to GitHub repositories. Visual identification of file types.",
     70, 72, 55),
    ("Refined GitHub", "refined-github",
     "Enhances GitHub interface with dozens of improvements. Open source. By Sindre Sorhus.",
     82, 80, 60),
    ("GitLens", "gitlens",
     "Git supercharged for VS Code web and GitHub. Blame, history, and comparison tools.",
     78, 76, 58),
    ("Window Resizer", "window-resizer",
     "Resize browser window to test responsive designs. Preset and custom resolution sizes.",
     72, 70, 62),
    ("EditThisCookie", "editthiscookie",
     "Cookie manager. Add, delete, edit, search, and protect cookies. Open source.",
     74, 68, 65),
    ("User-Agent Switcher", "user-agent-switcher",
     "Spoof browser user agent string. Test sites across different browsers and devices.",
     70, 68, 60),
    ("Pesticide", "pesticide",
     "CSS layout debugging. Outlines every element to visualize box model and layout issues.",
     72, 74, 48),
    ("PerfectPixel", "perfectpixel",
     "Overlay design mockups on web pages for pixel-perfect development. Semi-transparent overlay.",
     70, 72, 55),
    ("VisBug", "visbug",
     "Visual debugging tool by Google Chrome team. Edit any page visually in the browser.",
     76, 80, 48),
    ("axe DevTools", "axe-devtools",
     "Accessibility testing by Deque Systems. Find and fix WCAG accessibility issues.",
     84, 86, 62),
    ("Svelte DevTools", "svelte-devtools",
     "Debugging tools for Svelte applications. Inspect component state and hierarchy.",
     78, 76, 45),
    ("Apollo Client DevTools", "apollo-client-devtools",
     "GraphQL debugging for Apollo Client. Inspect cache, queries, and mutations.",
     76, 74, 42),
    ("Ember Inspector", "ember-inspector",
     "Official Ember.js debugging extension. Component tree and data inspector.",
     74, 72, 38),
    ("Immutable.js Object Formatter", "immutablejs-object-formatter",
     "Format Immutable.js objects in Chrome DevTools console for readability.",
     66, 68, 32),
    ("CSS Peeper", "css-peeper",
     "Smart CSS viewer. Extract styles, colors, and assets from any website visually.",
     72, 70, 55),

    # ── Communication ────────────────────────────────────────────────────
    ("Google Translate", "google-translate",
     "Translate entire pages or selected text. Supports 100+ languages. By Google.",
     85, 82, 92),
    ("Zoom", "zoom",
     "Schedule and join Zoom meetings from Chrome. By Zoom Video Communications.",
     78, 75, 85),
    ("Slack", "slack",
     "Quick access to Slack workspaces. Share links and manage notifications. By Salesforce.",
     80, 78, 82),
    ("Microsoft Teams", "microsoft-teams",
     "Join Teams meetings and share content from Chrome. By Microsoft.",
     78, 80, 78),
    ("Cisco Webex", "cisco-webex",
     "Join Webex meetings and schedule from browser. Enterprise video conferencing by Cisco.",
     76, 78, 70),
    ("Google Meet Enhancement Suite", "google-meet-enhancement-suite",
     "Enhance Google Meet with grid view, push to talk, and auto-join features.",
     68, 65, 72),
    ("Telegram Web", "telegram-web",
     "Telegram messaging in Chrome sidebar. Encrypted messaging platform.",
     74, 72, 68),
    ("WhatsApp Web Plus", "whatsapp-web-plus",
     "Enhancements for WhatsApp Web. Dark mode, privacy features, and customization.",
     62, 55, 72),
    ("Discord", "discord",
     "Quick access to Discord communities from browser. Voice, video, and text chat.",
     76, 72, 78),
    ("Krisp", "krisp",
     "AI-powered noise cancellation for calls and meetings. Removes background noise.",
     74, 72, 60),

    # ── Shopping ─────────────────────────────────────────────────────────
    ("Honey (PayPal)", "honey",
     "Automatic coupon finder and price tracker. Owned by PayPal. Finds deals at checkout.",
     72, 65, 92),
    ("Rakuten (Ebates)", "rakuten",
     "Cash-back rewards and coupon extension. Earn cash back at 3500+ stores.",
     70, 65, 85),
    ("Capital One Shopping", "capital-one-shopping",
     "Price comparison and coupon finder by Capital One (formerly Wikibuy).",
     68, 62, 78),
    ("CamelCamelCamel", "camelcamelcamel",
     "Amazon price tracker. View price history charts and set price drop alerts.",
     76, 78, 72),
    ("Keepa", "keepa",
     "Amazon price tracker with detailed price history graphs. International Amazon support.",
     74, 72, 70),
    ("RetailMeNot", "retailmenot",
     "Coupon and cash-back extension. Auto-apply coupons at checkout for savings.",
     66, 60, 68),
    ("PriceBlink", "priceblink",
     "Price comparison tool. Alerts when lower prices are found at other retailers.",
     68, 65, 58),
    ("ShopSavvy", "shopsavvy",
     "Barcode scanner and price comparison. Find best deals across retailers.",
     62, 58, 55),
    ("Klarna", "klarna",
     "Buy now, pay later extension. Price drop alerts and wish lists. By Klarna Bank.",
     66, 62, 72),
    ("Cently", "cently",
     "Automatic coupon code finder. Tests and applies discount codes at checkout.",
     64, 60, 55),
    ("Invisible Hand", "invisible-hand",
     "Background price comparison. Alerts when cheaper prices are found elsewhere.",
     66, 64, 52),
    ("Avail", "avail",
     "Aggregates coupons and cash-back offers from multiple sources.",
     60, 58, 48),

    # ── Social Media ─────────────────────────────────────────────────────
    ("Buffer", "buffer",
     "Social media scheduling and management. Schedule posts across platforms. By Buffer Inc.",
     76, 74, 72),
    ("Hootsuite", "hootsuite",
     "Social media management extension. Schedule and publish to multiple platforms.",
     74, 72, 68),
    ("Social Blade", "social-blade",
     "Social media statistics and analytics. Track YouTube, Twitch, Instagram, and Twitter stats.",
     70, 65, 72),
    ("Bitly", "bitly",
     "URL shortener and link management. Track clicks and engagement on shortened links.",
     74, 72, 70),
    ("Nimbus Screenshot", "nimbus-screenshot",
     "Screenshot and screen recording tool. Full page capture, annotation, and cloud storage.",
     72, 68, 68),
    ("Later", "later",
     "Instagram and social media scheduling. Visual content calendar and analytics.",
     70, 68, 60),
    ("Sprout Social", "sprout-social",
     "Enterprise social media management. Publishing, analytics, and engagement tools.",
     76, 78, 55),
    ("Publer", "publer",
     "Social media scheduling for multiple platforms. Auto-scheduling and recycling posts.",
     68, 66, 48),
    ("Crowdfire", "crowdfire",
     "Social media management and content curation. Schedule posts and discover content.",
     66, 64, 55),
    ("TweetDeck", "tweetdeck",
     "Twitter/X multi-column dashboard. Real-time tracking of multiple timelines. By Twitter/X.",
     72, 68, 70),

    # ── VPN / Proxy ──────────────────────────────────────────────────────
    ("NordVPN", "nordvpn",
     "VPN extension by Nord Security. Lightweight proxy with threat protection. Audited by PwC.",
     80, 82, 78),
    ("ExpressVPN", "expressvpn",
     "VPN extension by Kape Technologies. WebRTC leak blocking and location spoofing.",
     78, 80, 75),
    ("Windscribe", "windscribe",
     "Free VPN with 10GB/month. Ad and tracker blocking. By Windscribe Limited.",
     76, 78, 68),
    ("ProtonVPN", "protonvpn",
     "VPN by Proton AG (makers of ProtonMail). Swiss privacy, open source client. Free tier.",
     82, 85, 65),
    ("Surfshark", "surfshark",
     "VPN extension with CleanWeb ad blocking. Unlimited devices. By Surfshark B.V.",
     76, 78, 68),
    ("TunnelBear", "tunnelbear",
     "Simple VPN with bear-themed interface. 2GB free/month. By McAfee.",
     72, 70, 62),
    ("Hotspot Shield", "hotspot-shield",
     "VPN with Hydra protocol. Free tier with ads. By Pango (Aura).",
     68, 65, 70),
    ("ZenMate", "zenmate",
     "VPN browser extension. Free basic tier. By Kape Technologies.",
     66, 64, 60),
    ("Hola VPN", "hola-vpn",
     "Free peer-to-peer VPN. Caution: uses user bandwidth as exit nodes. Controversial privacy model.",
     55, 45, 78),
    ("CyberGhost", "cyberghost",
     "VPN extension with WebRTC leak protection. By Kape Technologies.",
     72, 74, 58),

    # ── AI Tools ─────────────────────────────────────────────────────────
    ("ChatGPT for Chrome", "chatgpt-for-chrome",
     "Access ChatGPT alongside search results. Display AI answers next to Google search. By OpenAI community.",
     72, 65, 82),
    ("Perplexity", "perplexity",
     "AI search companion. Summarize pages and get AI answers. By Perplexity AI.",
     76, 74, 72),
    ("Monica AI", "monica-ai",
     "AI assistant powered by GPT-4 and Claude. Chat, translate, compose, and summarize.",
     72, 65, 75),
    ("Merlin", "merlin",
     "AI assistant with GPT-4, Claude, and Gemini access. Works on any website.",
     70, 62, 72),
    ("MaxAI", "maxai",
     "AI copilot for reading and writing. Summarize, translate, and explain any content.",
     68, 60, 68),
    ("Sider AI", "sider-ai",
     "AI sidebar with ChatGPT, Claude, and Gemini. Summarize, translate, and chat anywhere.",
     70, 62, 72),
    ("UseChatGPT", "usechatgpt",
     "Use ChatGPT on any website without copy-pasting. AI writing, rewriting, and summarizing.",
     66, 58, 68),
    ("Wordtune", "wordtune",
     "AI writing companion. Rewrite, rephrase, and improve text. By AI21 Labs.",
     74, 70, 70),
    ("Jasper", "jasper",
     "AI content creation platform. Generate marketing copy, blog posts, and social content.",
     72, 68, 62),
    ("Copy.ai", "copy-ai",
     "AI copywriting assistant. Generate marketing copy, product descriptions, and emails.",
     68, 64, 58),
    ("Writesonic", "writesonic",
     "AI content generator. Blog posts, ads, and product descriptions powered by GPT.",
     66, 62, 55),
    ("Otter.ai", "otter-ai",
     "AI meeting transcription and notes. Real-time transcription for meetings and lectures.",
     76, 74, 65),
    ("Compose AI", "compose-ai",
     "AI autocomplete for email and writing. Suggests sentences as you type.",
     64, 60, 55),
    ("Fireflies.ai", "fireflies-ai",
     "AI meeting assistant. Transcribe, summarize, and search across meetings.",
     72, 68, 58),
    ("Phind", "phind",
     "AI search engine for developers. Code-focused answers with sources.",
     74, 72, 52),

    # ── Reading & Appearance ─────────────────────────────────────────────
    ("Dark Reader", "dark-reader",
     "Dark mode for every website. Adjustable brightness, contrast, and sepia filter. Open source.",
     85, 82, 90),
    ("Mercury Reader", "mercury-reader",
     "Distraction-free reading view. Remove ads and clutter from articles. By Postlight.",
     78, 80, 65),
    ("Reader View", "reader-view",
     "Clean reading mode for web pages. Strips formatting for comfortable reading.",
     76, 78, 58),
    ("Just Read", "just-read",
     "Customizable reader view. Remove ads, popups, and comments. Clean article layout.",
     74, 76, 52),
    ("Clearly (by Evernote)", "clearly",
     "Distraction-free reading by reformatting web articles into a clean layout.",
     68, 70, 45),
    ("Readwise Highlighter", "readwise-highlighter",
     "Highlight and save passages from web articles. Sync with Readwise for spaced repetition.",
     76, 78, 55),
    ("Weava Highlighter", "weava-highlighter",
     "Research tool for highlighting and organizing web content. Color-coded highlights.",
     70, 68, 52),
    ("Liner", "liner",
     "Web highlighter and AI assistant. Highlight, save, and organize web content.",
     68, 64, 58),
    ("Night Eye", "night-eye",
     "Dark mode for all websites. Smooth dark theme that preserves colors. Premium model.",
     72, 70, 62),
    ("Turn Off the Lights", "turn-off-the-lights",
     "Dim the page around YouTube and other video players. Cinema-like experience.",
     70, 68, 65),

    # ── Tab Management ───────────────────────────────────────────────────
    ("OneTab", "onetab",
     "Convert all tabs to a list. Reduces memory usage up to 95%. Restore tabs individually or all.",
     80, 78, 85),
    ("The Great Suspender (maintained fork)", "the-great-suspender",
     "Suspend inactive tabs to free memory. Auto-suspend after configurable timeout.",
     72, 65, 72),
    ("Tab Wrangler", "tab-wrangler",
     "Auto-close inactive tabs and save them for later. Configurable idle time. Open source.",
     76, 78, 62),
    ("Workona", "workona",
     "Tab and workspace manager. Organize tabs into workspaces with cloud sync.",
     74, 72, 60),
    ("Toby", "toby",
     "Visual tab manager. Organize tabs into collections on a beautiful new tab page.",
     72, 70, 62),
    ("Tab Manager Plus", "tab-manager-plus",
     "Advanced tab manager with search, group, and sort. Handle hundreds of tabs. Open source.",
     74, 76, 55),
    ("Cluster", "cluster",
     "Window and tab manager. Group tabs into shareable clusters. Sync across devices.",
     68, 66, 48),
    ("Tabli", "tabli",
     "Simple tab manager for Chrome. Search and manage open tabs and saved windows.",
     66, 68, 42),
    ("xTab", "xtab",
     "Limit the number of open tabs. Automatically close oldest tabs when limit is reached.",
     64, 66, 38),
    ("Tabs Outliner", "tabs-outliner",
     "Tree-style tab manager. Organize tabs in a hierarchical outline structure.",
     70, 68, 48),

    # ── Screenshot & Recording ───────────────────────────────────────────
    ("Lightshot", "lightshot",
     "Screenshot tool for selected areas. Quick editing and sharing. By Skillbrains.",
     72, 65, 82),
    ("GoFullPage", "gofullpage",
     "Full page screenshot capture. One click to capture entire scrolling page as image or PDF.",
     76, 78, 75),
    ("Awesome Screenshot", "awesome-screenshot",
     "Screen capture and annotation. Full page, selected area, or visible part. Cloud storage.",
     72, 68, 78),
    ("Screencastify", "screencastify",
     "Screen recorder and video editor. Record screen, webcam, or both. Cloud-based editing.",
     74, 70, 75),
    ("Vidyard", "vidyard",
     "Video recording and sharing for sales and marketing. Screen and webcam recording.",
     74, 72, 62),
    ("CloudApp (Zight)", "cloudapp",
     "Screen recording, GIF creation, and screenshot tool. Team collaboration features.",
     70, 68, 58),
    ("Scribe", "scribe",
     "Automatic step-by-step guide creator. Records clicks and generates how-to documentation.",
     76, 74, 62),
    ("Markup Hero", "markup-hero",
     "Screenshot, annotation, and markup tool. Always editable. Team collaboration.",
     68, 66, 48),
    ("Droplr", "droplr",
     "Screenshot and screen recording with instant sharing. Short link generation.",
     70, 68, 52),
    ("Gyazo", "gyazo",
     "Instant screenshot and GIF capture. Automatic upload and shareable link. By Nota Inc.",
     70, 66, 65),

    # ── Download Tools ───────────────────────────────────────────────────
    ("Video DownloadHelper", "video-downloadhelper",
     "Download videos from web pages. Supports hundreds of video sites. Companion app for conversion.",
     66, 58, 78),
    ("SaveFrom.net Helper", "savefrom-net-helper",
     "Download videos from YouTube, Vimeo, and other video platforms. Multiple format options.",
     58, 50, 72),
    ("Internet Download Manager (IDM)", "idm-integration",
     "Integration module for Internet Download Manager. Accelerates downloads with segmentation.",
     65, 60, 70),
    ("FetchV", "fetchv",
     "Video and audio downloader. Detect and download media from streaming sites.",
     60, 55, 55),
    ("Download All Images", "download-all-images",
     "Batch download all images from a web page. Filter by size and type.",
     62, 60, 55),
    ("Image Downloader", "image-downloader",
     "Browse and download images from any web page. Filter, select, and batch download.",
     64, 62, 58),
    ("SingleFile", "singlefile",
     "Save complete web pages as single HTML files. Preserves formatting and images. Open source.",
     78, 80, 55),
    ("Web Clipper by Notion", "notion-clipper",
     "Save any web page to Notion with one click. Preserve formatting and add to database.",
     80, 82, 72),
    ("DownThemAll", "downthemall",
     "Download manager for Chrome. Batch download links and images. Open source port from Firefox.",
     72, 70, 48),
    ("Save to Google Drive", "save-to-google-drive",
     "Save web content, screenshots, and files directly to Google Drive. By Google.",
     80, 82, 72),

    # ── Email ────────────────────────────────────────────────────────────
    ("Mailtrack", "mailtrack",
     "Email tracking for Gmail. Real-time read notifications and link click tracking.",
     68, 60, 78),
    ("Boomerang for Gmail", "boomerang-for-gmail",
     "Schedule emails, set reminders, and snooze messages. AI-assisted writing. By Baydin.",
     74, 70, 72),
    ("Checker Plus for Gmail", "checker-plus-for-gmail",
     "Gmail notifier with quick actions. Read, reply, and manage email without opening Gmail.",
     72, 68, 70),
    ("Clearbit Connect", "clearbit-connect",
     "Find email addresses and company information in Gmail. B2B data enrichment. By HubSpot.",
     70, 65, 62),
    ("Streak", "streak",
     "CRM in Gmail. Pipeline management, mail merge, and email tracking inside Gmail.",
     74, 70, 65),
    ("Mixmax", "mixmax",
     "Email tracking, scheduling, and automation for Gmail. Templates and sequences.",
     72, 68, 58),
    ("Gmelius", "gmelius",
     "Shared inbox and collaboration for Gmail. Kanban boards and email delegation.",
     70, 68, 55),
    ("Right Inbox", "right-inbox",
     "Gmail productivity tools. Email scheduling, tracking, reminders, and recurring emails.",
     68, 65, 58),
    ("Simplify Gmail", "simplify-gmail",
     "Minimalist Gmail redesign. Clean interface with simplified navigation. By Michael Leggett.",
     72, 74, 52),
    ("Unroll.me", "unroll-me",
     "Unsubscribe from unwanted emails. Bundle remaining subscriptions into a daily digest.",
     62, 55, 65),

    # ── SEO Tools ────────────────────────────────────────────────────────
    ("MozBar", "mozbar",
     "SEO toolbar by Moz. Domain authority, page authority, and link metrics on any page.",
     78, 74, 72),
    ("SEOquake", "seoquake",
     "SEO audit tool by Semrush. On-page SEO audit, keyword density, and SERP overlay.",
     76, 72, 70),
    ("Keywords Everywhere", "keywords-everywhere",
     "Keyword research tool. Search volume, CPC, and competition data on Google and YouTube.",
     74, 70, 68),
    ("SimilarWeb", "similarweb",
     "Website traffic and analytics. Estimate visits, engagement, and traffic sources. By Similarweb Ltd.",
     76, 72, 72),
    ("Ahrefs SEO Toolbar", "ahrefs-seo-toolbar",
     "On-page SEO report and SERP metrics. Broken link checker. By Ahrefs.",
     78, 76, 65),
    ("Ubersuggest", "ubersuggest",
     "SEO and keyword research by Neil Patel. Domain overview, keyword suggestions, and backlinks.",
     72, 68, 65),
    ("SEO Minion", "seo-minion",
     "SEO assistant with on-page analysis, broken link checking, and SERP preview.",
     70, 68, 58),
    ("Redirect Path", "redirect-path",
     "HTTP header and redirect checker. Detect 301, 302, 404, and 500 status codes.",
     72, 74, 52),
    ("Tag Assistant", "tag-assistant",
     "Google Tag debugging by Google. Verify Google Analytics, GTM, and Ads tags.",
     80, 82, 65),
    ("Link Redirect Trace", "link-redirect-trace",
     "Trace link redirects and detect cloaking. HTTP header analysis by Link Research Tools.",
     70, 68, 48),
    ("Detailed SEO", "detailed-seo",
     "Detailed on-page SEO analysis. Headings, links, images, and meta tag inspection.",
     72, 70, 52),
    ("META SEO Inspector", "meta-seo-inspector",
     "Inspect meta tags, open graph, and structured data on any web page.",
     70, 72, 48),

    # ── Automation ───────────────────────────────────────────────────────
    ("Bardeen", "bardeen",
     "AI automation and workflow builder. Automate repetitive tasks across web apps. No code.",
     76, 70, 65),
    ("Zapier", "zapier",
     "Automation platform extension. Connect 5000+ apps and automate workflows. By Zapier Inc.",
     78, 76, 72),
    ("IFTTT", "ifttt",
     "If This Then That automation. Connect apps and devices with simple conditional logic.",
     74, 72, 68),
    ("Axiom.ai", "axiom-ai",
     "Browser automation without code. Record and replay actions. Scraping and form filling.",
     72, 66, 55),
    ("iMacros", "imacros",
     "Browser automation and web testing. Record and replay macros for repetitive tasks.",
     70, 64, 62),
    ("Automa", "automa",
     "Browser automation with flowchart interface. Open source. Scraping, form filling, and more.",
     74, 70, 48),
    ("Selenium IDE", "selenium-ide",
     "Record and playback browser automation. Official Selenium project. Open source.",
     78, 76, 58),
    ("Web Scraper", "web-scraper",
     "Point-and-click web scraping. Build scrapers visually with CSS selectors.",
     72, 66, 60),
    ("Data Miner", "data-miner",
     "Web scraping extension. Extract data from web pages into CSV or Excel. Pre-built recipes.",
     70, 64, 62),
    ("Instant Data Scraper", "instant-data-scraper",
     "AI-powered web scraper. Automatically detects data on web pages. One-click extraction.",
     68, 62, 55),

    # ── Accessibility ────────────────────────────────────────────────────
    ("High Contrast", "high-contrast",
     "Adjust web page colors for improved readability. Multiple color schemes. By Google.",
     82, 85, 62),
    ("Screen Reader", "screen-reader",
     "ChromeVox screen reader by Google. Navigate web pages with spoken feedback.",
     84, 85, 58),
    ("ColorZilla", "colorzilla-acc",
     "Advanced eyedropper, color picker, and gradient generator. Accessibility color analysis.",
     76, 74, 72),
    ("NaturalReader", "naturalreader",
     "Text-to-speech reader. Convert web pages and documents to spoken audio.",
     74, 72, 62),
    ("Dyslexia Friendly", "dyslexia-friendly",
     "Make web pages easier to read for people with dyslexia. Font and spacing adjustments.",
     72, 74, 42),
    ("WAVE Evaluation Tool", "wave-evaluation-tool",
     "Web accessibility evaluation by WebAIM. WCAG compliance checking and error detection.",
     84, 86, 55),
    ("Accessibility Insights", "accessibility-insights",
     "Accessibility testing by Microsoft. Automated and manual WCAG 2.1 compliance checks.",
     85, 88, 52),
    ("HeadingsMap", "headingsmap",
     "Visualize heading structure of web pages. Check heading hierarchy for accessibility.",
     72, 74, 42),
    ("Zoom Page WE", "zoom-page-we",
     "Full page zoom with custom zoom levels. Persist zoom settings per domain.",
     68, 70, 48),
    ("Text Spacing Editor", "text-spacing-editor",
     "Adjust letter spacing, word spacing, and line height for better readability. WCAG tool.",
     70, 72, 38),

    # ── Security ─────────────────────────────────────────────────────────
    ("Avast Online Security", "avast-online-security",
     "Website reputation checker and phishing protection. By Gen Digital (Avast).",
     72, 74, 75),
    ("Norton Safe Web", "norton-safe-web",
     "Website safety ratings and phishing protection. By Gen Digital (NortonLifeLock).",
     70, 72, 72),
    ("McAfee WebAdvisor", "mcafee-webadvisor",
     "Safe browsing and download protection. Warns about risky websites. By McAfee.",
     68, 70, 70),
    ("Malwarebytes Browser Guard", "malwarebytes-browser-guard",
     "Block malware, scams, and trackers. Phishing protection. By Malwarebytes.",
     76, 80, 68),
    ("Bitdefender TrafficLight", "bitdefender-trafficlight",
     "Real-time website security scanning. Block phishing, malware, and fraudulent pages.",
     74, 78, 55),
    ("Netcraft", "netcraft",
     "Anti-phishing extension. Reports suspected phishing sites. Community-driven intelligence.",
     78, 82, 48),
    ("ScriptSafe", "scriptsafe",
     "Script and content blocker for advanced users. Control JavaScript, plugins, and iframes.",
     76, 80, 45),
    ("Web of Trust (WOT)", "web-of-trust",
     "Crowd-sourced website reputation ratings. Traffic light safety icons in search results.",
     65, 58, 68),
    ("Webroot", "webroot",
     "Web threat shield by Webroot (OpenText). Anti-phishing and anti-malware browsing.",
     70, 74, 48),
    ("Windows Defender", "windows-defender",
     "Microsoft Defender Browser Protection. Phishing and malware protection by Microsoft.",
     78, 82, 55),

    # ── Crypto ───────────────────────────────────────────────────────────
    ("MetaMask", "metamask",
     "Ethereum wallet and dApp browser. Industry standard for Web3. By Consensys.",
     72, 68, 85),
    ("Phantom", "phantom",
     "Multi-chain crypto wallet. Solana, Ethereum, Polygon, and Bitcoin support.",
     70, 66, 75),
    ("Coinbase Wallet", "coinbase-wallet",
     "Self-custody crypto wallet by Coinbase. Multi-chain support and dApp browser.",
     72, 70, 72),
    ("Rabby Wallet", "rabby-wallet",
     "Open-source Ethereum wallet by DeBank. Pre-transaction risk scanning. Security-focused.",
     74, 72, 55),
    ("Trust Wallet", "trust-wallet",
     "Multi-chain crypto wallet by Binance. Support for 100+ blockchains. Mobile-first.",
     68, 65, 70),
    ("Keplr", "keplr",
     "Cosmos ecosystem wallet. IBC transfers and staking across Cosmos chains.",
     66, 64, 52),
    ("Temple Wallet", "temple-wallet",
     "Tezos wallet for Chrome. DeFi, NFTs, and staking on Tezos blockchain.",
     62, 62, 38),
    ("Sui Wallet", "sui-wallet",
     "Official Sui blockchain wallet by Mysten Labs. Manage SUI tokens and dApps.",
     64, 66, 42),
    ("Solflare", "solflare",
     "Solana wallet with staking support. Hardware wallet integration. Non-custodial.",
     66, 64, 48),
    ("Backpack", "backpack",
     "Multi-chain wallet and xNFT platform. Solana and Ethereum. By Coral/Armada.",
     64, 62, 45),

    # ── Google Ecosystem ─────────────────────────────────────────────────
    ("Google Docs Offline", "google-docs-offline",
     "Edit Google Docs, Sheets, and Slides without internet connection. By Google.",
     85, 88, 85),
    ("Google Scholar Button", "google-scholar-button",
     "Quick access to Google Scholar search. Find scholarly articles from any page. By Google.",
     82, 85, 70),
    ("Google Arts & Culture", "google-arts-culture",
     "Explore art, history, and culture from 2000+ museums worldwide. By Google.",
     80, 85, 55),
    ("Google Input Tools", "google-input-tools",
     "Type in 90+ languages using virtual keyboard, transliteration, and handwriting. By Google.",
     82, 85, 62),
    ("Google Dictionary", "google-dictionary",
     "Double-click any word for instant definition. Pronunciation and word history. By Google.",
     80, 82, 75),
    ("Google Mail Checker", "google-mail-checker",
     "Unread Gmail count in toolbar. Quick access to Gmail inbox. By Google.",
     78, 82, 68),
    ("Google Calendar", "google-calendar",
     "Quick view and add events to Google Calendar from any page. By Google.",
     82, 85, 72),
    ("Save to Google Drive", "save-to-drive",
     "Save web content, screenshots, and files directly to Google Drive. By Google.",
     82, 85, 72),
    ("Google Analytics Debugger", "ga-debugger",
     "Debug Google Analytics implementation. Print GA data to console. By Google.",
     78, 80, 55),
    ("Tag Assistant Legacy", "tag-assistant-legacy",
     "Verify Google tag installations. Debug Analytics, GTM, Ads tags. By Google.",
     80, 82, 60),

    # ── Microsoft Ecosystem ──────────────────────────────────────────────
    ("Microsoft Editor", "microsoft-editor",
     "AI writing assistant by Microsoft. Grammar, spelling, and style for 20+ languages.",
     82, 80, 78),
    ("Microsoft Outlook", "microsoft-outlook",
     "Outlook email management extension. Quick compose and calendar access. By Microsoft.",
     78, 80, 65),
    ("Microsoft 365", "microsoft-365",
     "Quick access to Office apps (Word, Excel, PowerPoint) online. By Microsoft.",
     80, 82, 72),
    ("Bing Chat / Copilot", "bing-copilot",
     "AI chat assistant in browser sidebar. Powered by GPT-4. By Microsoft.",
     78, 76, 75),
    ("Collections (Edge for Chrome)", "edge-collections",
     "Organize web content into visual collections. Research and comparison tool.",
     72, 74, 45),

    # ── Media & Entertainment ────────────────────────────────────────────
    ("Enhancer for YouTube", "enhancer-for-youtube",
     "YouTube enhancements: custom playback speed, mini player, ad control, and themes.",
     76, 70, 78),
    ("Unhook YouTube", "unhook-youtube",
     "Remove YouTube distractions. Hide recommendations, sidebar, comments, and shorts.",
     74, 76, 62),
    ("SponsorBlock", "sponsorblock",
     "Skip sponsored segments in YouTube videos. Community-submitted timestamps. Open source.",
     82, 80, 72),
    ("Return YouTube Dislike", "return-youtube-dislike",
     "Restore dislike count on YouTube videos. Community-driven estimates. Open source.",
     74, 72, 70),
    ("Video Speed Controller", "video-speed-controller",
     "Custom playback speed for any HTML5 video. Keyboard shortcuts. Open source.",
     78, 76, 68),
    ("Picture-in-Picture", "picture-in-picture",
     "Floating video player for any HTML5 video. Watch while browsing other tabs. By Google.",
     80, 82, 65),
    ("Netflix Party (Teleparty)", "teleparty",
     "Synchronized streaming with friends. Chat while watching Netflix, Disney+, and more.",
     68, 62, 75),
    ("Shazam", "shazam",
     "Identify songs playing in browser tabs. Music recognition by Apple.",
     76, 78, 60),
    ("Spotify Web Player Hotkeys", "spotify-hotkeys",
     "Keyboard shortcuts for Spotify web player. Play, pause, skip without switching tabs.",
     66, 68, 52),
    ("Volume Master", "volume-master",
     "Volume booster and controller. Amplify tab audio up to 600%. Per-tab volume control.",
     68, 62, 75),

    # ── Writing & Language ───────────────────────────────────────────────
    ("LanguageTool", "languagetool",
     "Grammar, style, and spell checker. Supports 30+ languages. Open source engine.",
     82, 80, 72),
    ("DeepL Translate", "deepl-translate",
     "Neural machine translation. Higher quality than Google for European languages. By DeepL.",
     84, 82, 68),
    ("Mate Translate", "mate-translate",
     "Translate text and web pages. 103 languages. Speak translations. By Twopeople Software.",
     72, 70, 60),
    ("QuillBot", "quillbot",
     "AI paraphrasing tool. Rewrite sentences while preserving meaning. Grammar checker included.",
     74, 68, 70),
    ("ProWritingAid", "prowritingaid",
     "Advanced writing assistant. Style, readability, and grammar analysis. For long-form writing.",
     76, 74, 58),
    ("Hemingway Editor", "hemingway-editor",
     "Readability analysis tool. Highlights complex sentences and passive voice.",
     72, 74, 52),
    ("Reverso", "reverso",
     "Translation and language learning. Contextual translation and conjugation. 15+ languages.",
     72, 70, 62),
    ("Google Translate (sidebar)", "google-translate-sidebar",
     "Translate selected text in sidebar panel. Quick access to Google Translate. By Google.",
     82, 85, 70),
    ("Linguee", "linguee",
     "Dictionary with contextual examples. See translations in real sentences. By DeepL.",
     74, 76, 48),
    ("Papaly", "papaly",
     "Visual bookmark manager with customizable boards. Organize and share bookmarks.",
     66, 68, 42),

    # ── Clipboard & Notes ────────────────────────────────────────────────
    ("Clipboard History Pro", "clipboard-history-pro",
     "Clipboard manager for Chrome. Search and reuse clipboard history. Encrypted storage.",
     72, 70, 58),
    ("Ditto Clipboard", "ditto-clipboard",
     "Enhanced clipboard with history. Copy multiple items and paste later.",
     68, 66, 52),
    ("Google Keep (notes)", "google-keep-notes",
     "Quick notes from any page. Save text, images, and links to Google Keep. By Google.",
     82, 85, 75),
    ("Nimbus Notes", "nimbus-notes",
     "Note-taking and screenshot tool. Organize notes with folders and tags. Cloud sync.",
     70, 68, 58),
    ("Bear Notes", "bear-notes",
     "Beautiful note-taking with markdown support. Tag-based organization.",
     72, 74, 48),

    # ── Forms & Data Entry ───────────────────────────────────────────────
    ("Autofill", "autofill",
     "Form autofill beyond browser defaults. Custom rules for any form field.",
     68, 62, 60),
    ("Form Filler", "form-filler",
     "Auto-fill forms with pre-configured data. Testing and productivity tool.",
     64, 60, 48),
    ("Fake Filler", "fake-filler",
     "Fill forms with random dummy data. Useful for testing. Open source.",
     70, 68, 42),
    ("DocuSign", "docusign",
     "Sign documents electronically in browser. Enterprise e-signature. By DocuSign Inc.",
     80, 82, 72),
    ("HelloSign", "hellosign",
     "Free electronic signature extension. Sign and request signatures. By Dropbox.",
     78, 80, 62),

    # ── Cloud Storage ────────────────────────────────────────────────────
    ("Dropbox", "dropbox",
     "Share and save files to Dropbox from browser. Quick access to cloud storage.",
     80, 78, 78),
    ("OneDrive", "onedrive",
     "Microsoft OneDrive integration. Save and share files from browser. By Microsoft.",
     80, 82, 72),
    ("Box", "box",
     "Enterprise cloud storage integration. Share and manage files from browser. By Box Inc.",
     78, 80, 60),
    ("pCloud", "pcloud",
     "Cloud storage integration. Save files and screenshots to pCloud. Swiss privacy.",
     72, 74, 48),

    # ── Design & Color ───────────────────────────────────────────────────
    ("Muzli", "muzli",
     "Design inspiration in new tab. Curated design content from Dribbble, Behance, and more.",
     72, 70, 62),
    ("ColorPick Eyedropper", "colorpick-eyedropper",
     "Simple color picker. Get HEX values from any pixel on the page.",
     70, 68, 65),
    ("Fonts Ninja", "fonts-ninja",
     "Identify fonts on any website. Preview, bookmark, and try fonts. Typography tool.",
     72, 70, 58),
    ("Muzli Colors", "muzli-colors",
     "Color palette generator. Create and explore color combinations for design.",
     68, 66, 48),
    ("SVG Export", "svg-export",
     "Download SVG images from any web page. Export, copy, and edit SVGs.",
     66, 68, 42),
    ("Site Palette", "site-palette",
     "Extract color palette from any website. Generate CSS and design palettes.",
     70, 68, 48),

    # ── Bookmarks & Organization ─────────────────────────────────────────
    ("Raindrop.io", "raindrop-io",
     "All-in-one bookmark manager. Visual organization, full-text search, and tags.",
     78, 76, 62),
    ("Pocket (save for later)", "pocket-save",
     "Save articles and videos for later. Offline reading and discovery. By Mozilla.",
     80, 82, 75),
    ("Pinboard", "pinboard",
     "Bookmarking service with fast, no-nonsense interface. Full-text search. Paid service.",
     74, 76, 42),
    ("Start.me", "start-me",
     "Customizable start page with bookmarks, feeds, and widgets. Organize the web.",
     70, 68, 52),
    ("Speed Dial 2", "speed-dial-2",
     "Visual bookmark new tab page. Organize bookmarks with thumbnails and folders.",
     68, 66, 58),

    # ── Privacy (additional) ─────────────────────────────────────────────
    ("Blur (by Abine)", "blur",
     "Password manager and privacy tool. Masked emails, phone numbers, and credit cards.",
     76, 78, 55),
    ("Click&Clean", "click-and-clean",
     "Clean browsing data with one click. Delete history, cache, cookies, and downloads.",
     72, 68, 68),
    ("History Eraser", "history-eraser",
     "Delete browsing history, cookies, and cache. Selective and automatic cleaning.",
     66, 64, 55),
    ("Facebook Container", "facebook-container",
     "Isolate Facebook activity from other browsing. Prevent tracking. By Mozilla (Firefox port).",
     80, 84, 48),
    ("Mailvelope", "mailvelope",
     "OpenPGP encryption for webmail (Gmail, Outlook.com). End-to-end encrypted email. Open source.",
     82, 88, 42),

    # ── Utility ──────────────────────────────────────────────────────────
    ("Marinara Timer", "marinara-timer",
     "Pomodoro technique timer. Customizable work and break intervals with notifications.",
     68, 70, 52),
    ("Nimbus Capture", "nimbus-capture",
     "Screenshot and video recording. Full page capture, annotation, and editing.",
     72, 68, 65),
    ("Emoji Keyboard", "emoji-keyboard",
     "Emoji picker for Chrome. Browse, search, and copy emojis to clipboard.",
     66, 64, 65),
    ("WhatRuns", "whatruns",
     "Identify web technologies, frameworks, and tools used on any website.",
     72, 68, 55),
    ("Page Ruler Redux", "page-ruler-redux",
     "Measure pixel dimensions on web pages. Ruler overlay with element detection.",
     70, 72, 48),
    ("Print Friendly", "print-friendly",
     "Print or save clean web pages. Remove ads, navigation, and clutter before printing.",
     72, 70, 62),
    ("Papier", "papier",
     "Minimalist note-taking in new tab page. Simple text editor that persists locally.",
     68, 70, 48),
    ("Earth View", "earth-view",
     "Satellite imagery from Google Earth on new tab. Beautiful aerial photography. By Google.",
     78, 82, 58),
    ("Cursor Style", "cursor-style",
     "Custom cursor themes and styles for web browsing. Fun cursor collections.",
     55, 50, 58),
    ("Eye Dropper", "eye-dropper",
     "Open source color picker. Pick colors from web pages and get HEX, RGB, and HSL values.",
     72, 74, 55),

    # ── News & RSS ───────────────────────────────────────────────────────
    ("Feedly", "feedly",
     "RSS reader and news aggregator. Follow blogs, news sites, and YouTube channels.",
     78, 76, 68),
    ("Inoreader", "inoreader",
     "Advanced RSS reader with rules, filters, and automation. Power user news reader.",
     76, 74, 55),
    ("RSS Feed Reader", "rss-feed-reader",
     "Simple RSS and Atom feed reader. Subscribe and read feeds in browser.",
     70, 72, 52),
    ("News Feed Eradicator", "news-feed-eradicator",
     "Replace Facebook, Twitter, and Reddit feeds with inspirational quotes. Reduce distractions.",
     74, 76, 55),
    ("Google News", "google-news",
     "Quick access to personalized Google News. Trending stories and topics. By Google.",
     80, 82, 65),

    # ── Education & Research ─────────────────────────────────────────────
    ("Zotero Connector", "zotero-connector",
     "Save references from the web to Zotero. Academic citation management. Open source.",
     84, 82, 62),
    ("Mendeley Web Importer", "mendeley-web-importer",
     "Import references to Mendeley library. Academic reference manager. By Elsevier.",
     76, 74, 55),
    ("Cite This For Me", "cite-this-for-me",
     "Auto-generate citations and bibliographies. APA, MLA, Chicago formats. By Chegg.",
     68, 66, 60),
    ("Hypothesis", "hypothesis",
     "Web annotation tool for collaborative reading. Annotate any web page. Open source.",
     80, 82, 52),
    ("Equatio", "equatio",
     "Math equation editor by Texthelp. Type, handwrite, or speak math equations. STEM accessibility.",
     76, 78, 48),
    ("Kami", "kami",
     "PDF and document annotation. Mark up PDFs, images, and documents in browser. EDU focused.",
     74, 72, 62),
    ("Diigo", "diigo",
     "Social bookmarking and annotation. Highlight, tag, and share web content.",
     70, 68, 52),
    ("Brainly", "brainly",
     "Homework help and learning community. Ask questions and get answers from peers.",
     66, 62, 65),
    ("Quizlet", "quizlet",
     "Flashcard and study tool extension. Quick access to study sets from any page.",
     72, 70, 68),
    ("Scholarly", "scholarly",
     "Academic paper reader enhancement. Better reading experience for research papers.",
     70, 72, 42),

    # ── Project Management ───────────────────────────────────────────────
    ("Asana", "asana",
     "Task and project management extension. Create tasks from any web page. By Asana Inc.",
     78, 80, 72),
    ("Trello", "trello",
     "Create Trello cards from any web page. Quick add with attachment. By Atlassian.",
     78, 80, 72),
    ("ClickUp", "clickup",
     "Create tasks from any page. Time tracking and quick actions. By ClickUp Inc.",
     74, 72, 65),
    ("Monday.com", "monday-com",
     "Create items and manage boards from browser. Quick actions for Monday.com.",
     74, 72, 62),
    ("Jira Cloud", "jira-cloud",
     "Create Jira issues from any web page. Quick task creation. By Atlassian.",
     78, 80, 65),
    ("Linear", "linear",
     "Issue tracker extension. Create Linear issues from any web page.",
     76, 78, 55),
    ("Basecamp", "basecamp",
     "Save content to Basecamp projects. Quick todo creation from browser.",
     72, 74, 55),
    ("Wrike", "wrike",
     "Enterprise project management extension. Create tasks and share content.",
     72, 74, 52),
    ("Smartsheet", "smartsheet",
     "Create rows and manage sheets from Chrome. Enterprise work management.",
     70, 72, 52),
    ("Height", "height",
     "Modern project management extension. Create tasks from any page.",
     68, 70, 42),

    # ── CRM & Sales ──────────────────────────────────────────────────────
    ("HubSpot Sales", "hubspot-sales",
     "Email tracking, templates, and CRM sidebar for Gmail. By HubSpot.",
     78, 76, 72),
    ("Salesforce Lightning", "salesforce-lightning",
     "Access Salesforce records and create leads from browser. By Salesforce.",
     76, 78, 65),
    ("Apollo.io", "apollo-io",
     "B2B sales intelligence. Find emails, phone numbers, and company data.",
     72, 65, 62),
    ("LinkedIn Sales Navigator", "linkedin-sales-navigator",
     "Enhanced LinkedIn prospecting. InMail and lead management. By Microsoft.",
     76, 74, 68),
    ("ZoomInfo", "zoominfo",
     "B2B contact and company data. Prospect directly from LinkedIn and web. By ZoomInfo.",
     74, 70, 58),
    ("Lusha", "lusha",
     "B2B contact finder. Phone numbers and email addresses from LinkedIn profiles.",
     68, 60, 62),
    ("Hunter.io", "hunter-io",
     "Find email addresses associated with any website. Email verification. By Hunter.",
     72, 68, 60),
    ("Snov.io", "snov-io",
     "Email finder and drip campaign tool. Find and verify email addresses.",
     68, 64, 52),
    ("SalesLoft", "salesloft",
     "Sales engagement platform extension. Email tracking and cadence management.",
     74, 72, 55),
    ("Outreach", "outreach",
     "Sales execution platform extension. Sequence management and email tracking.",
     74, 72, 52),

    # ── Testing & QA ─────────────────────────────────────────────────────
    ("BrowserStack", "browserstack",
     "Cross-browser testing. Test websites on real browsers and devices. By BrowserStack.",
     78, 80, 58),
    ("LambdaTest", "lambdatest",
     "Cross-browser testing platform. Screenshot testing and real-time debugging.",
     72, 70, 52),
    ("Bug Magnet", "bug-magnet",
     "Exploratory testing assistant. Generate boundary values, edge cases, and test data.",
     72, 74, 42),
    ("Sauce Labs", "sauce-labs",
     "Cross-browser testing integration. Automated and manual testing on cloud browsers.",
     74, 76, 45),
    ("Testsigma", "testsigma",
     "AI-driven test automation recorder. Record and playback browser tests.",
     68, 66, 38),
    ("Ghost Inspector", "ghost-inspector",
     "Automated browser testing. Record and run regression tests. Cloud-based.",
     70, 68, 42),
    ("Katalon Recorder", "katalon-recorder",
     "Selenium IDE alternative for recording automated tests. Export to multiple frameworks.",
     72, 70, 48),
    ("Checkbot", "checkbot",
     "SEO, speed, and security checker. Crawl site and find broken links and issues.",
     74, 72, 52),
    ("Responsive Viewer", "responsive-viewer",
     "View multiple responsive screen sizes simultaneously. Compare layouts side by side.",
     72, 70, 55),
    ("Resolution Test", "resolution-test",
     "Test web pages at different screen resolutions. Quick resolution switching.",
     66, 68, 42),

    # ── Analytics & Marketing ────────────────────────────────────────────
    ("Google Analytics Opt-out", "google-analytics-optout",
     "Opt out of Google Analytics tracking. Prevents data collection. By Google.",
     80, 85, 62),
    ("Facebook Pixel Helper", "facebook-pixel-helper",
     "Debug Facebook Pixel implementation. Verify events and parameters. By Meta.",
     76, 74, 68),
    ("Hotjar", "hotjar",
     "Heatmaps and user behavior analytics. See how visitors interact with your site.",
     74, 70, 62),
    ("Mixpanel", "mixpanel",
     "Product analytics extension. Track events and user behavior. By Mixpanel.",
     74, 72, 55),
    ("Heap", "heap",
     "Autocapture analytics. Track user interactions without code changes.",
     72, 70, 48),
    ("FullStory", "fullstory",
     "Session replay and analytics. Watch user sessions and identify issues.",
     74, 72, 52),
    ("Lucky Orange", "lucky-orange",
     "Heatmaps, session recordings, and chat. Conversion optimization tool.",
     68, 66, 48),
    ("Amplitude", "amplitude",
     "Product analytics browser extension. Debug events and user properties.",
     72, 70, 48),
    ("Segment", "segment",
     "Customer data infrastructure debugger. Verify Segment tracking implementation.",
     74, 72, 45),
    ("PostHog", "posthog",
     "Open-source product analytics. Session recording, feature flags, and A/B testing.",
     76, 74, 48),

    # ── PDF & Documents ──────────────────────────────────────────────────
    ("Adobe Acrobat", "adobe-acrobat",
     "View, fill, sign, and convert PDFs in browser. By Adobe. Industry standard.",
     82, 80, 78),
    ("Smallpdf", "smallpdf",
     "PDF tools: compress, convert, merge, and split PDFs. Swiss company. SOC2 certified.",
     76, 74, 68),
    ("PDF Viewer", "pdf-viewer",
     "Enhanced PDF viewing in Chrome. Annotations, highlights, and bookmarks.",
     70, 72, 60),
    ("Lumin PDF", "lumin-pdf",
     "PDF editor and annotator. Sign, merge, and collaborate on PDFs in browser.",
     68, 66, 55),
    ("Xodo PDF", "xodo-pdf",
     "PDF reader and annotator. Merge, reorder, and collaborate on documents.",
     70, 68, 52),
    ("ILovePDF", "ilovepdf",
     "Complete PDF toolkit. Merge, split, compress, convert, and edit PDFs.",
     72, 70, 62),
    ("PDFfiller", "pdffiller",
     "Fill, sign, and edit PDF forms in browser. Cloud-based document management.",
     70, 68, 55),
    ("Sejda PDF Editor", "sejda-pdf",
     "Edit PDF text, images, and links directly in browser. OCR support.",
     68, 66, 48),

    # ── Remote Work ──────────────────────────────────────────────────────
    ("Miro", "miro",
     "Online whiteboard extension. Capture and share content to Miro boards.",
     76, 74, 62),
    ("Figma", "figma",
     "Inspect Figma designs in browser. Quick access to design files. By Figma.",
     80, 78, 68),
    ("Whereby", "whereby",
     "Video conferencing extension. Quick meeting links without downloads. Norwegian company.",
     72, 70, 52),
    ("Around", "around",
     "Minimalist video calling with floating bubble interface. Noise cancellation.",
     68, 66, 42),
    ("Tandem", "tandem",
     "Virtual office for remote teams. See who is available and start instant calls.",
     66, 64, 42),
    ("Gather", "gather",
     "Virtual workspace with spatial video chat. Customizable virtual offices.",
     68, 66, 48),

    # ── Finance & Budgeting ──────────────────────────────────────────────
    ("Mint (by Intuit)", "mint",
     "Personal finance tracking. Budget management and spending insights. By Intuit.",
     72, 70, 65),
    ("YNAB Toolkit", "ynab-toolkit",
     "Enhancements for You Need A Budget. Additional reports and UI improvements. Open source.",
     74, 76, 48),
    ("Personal Capital", "personal-capital",
     "Investment tracking and financial planning. Net worth dashboard. By Empower.",
     72, 70, 55),
    ("Wealthfront", "wealthfront",
     "Automated investing extension. Quick access to portfolio and planning tools.",
     70, 72, 48),
    ("Robinhood", "robinhood",
     "Stock and crypto trading notifications. Quick market access from browser.",
     66, 62, 62),

    # ── Health & Wellness ────────────────────────────────────────────────
    ("Noisli", "noisli",
     "Background noise generator for focus and relaxation. Nature sounds and white noise.",
     70, 72, 52),
    ("Break Timer", "break-timer",
     "Reminder to take breaks while working. Customizable intervals and break activities.",
     68, 70, 48),
    ("Calm", "calm",
     "Meditation and relaxation. Breathing exercises and calming scenes. By Calm Inc.",
     72, 70, 55),
    ("f.lux", "flux-web",
     "Blue light filter for web browsing. Reduce eye strain with warm color temperature.",
     72, 74, 55),
    ("Eye Care 20 20 20", "eye-care-20-20-20",
     "Eye health reminder following 20-20-20 rule. Take breaks to prevent eye strain.",
     66, 68, 42),

    # ── Gaming & Fun ─────────────────────────────────────────────────────
    ("Steam Inventory Helper", "steam-inventory-helper",
     "Tools for Steam marketplace. Quick sell, buy orders, and inventory management.",
     66, 60, 62),
    ("Augmented Steam", "augmented-steam",
     "Steam store enhancements. Price history, region comparisons, and feature highlights.",
     72, 70, 58),
    ("ProtonDB", "protondb",
     "Show Linux/Steam Deck compatibility ratings on Steam store pages.",
     70, 72, 45),
    ("IsThereAnyDeal", "isthereanydeal",
     "Game price comparison across stores. Historical lowest prices. Deal alerts.",
     72, 70, 52),
    ("GG.deals", "gg-deals",
     "Game deal finder. Compare prices across Steam, Epic, GOG, and more.",
     68, 66, 48),

    # ── Maps & Travel ────────────────────────────────────────────────────
    ("Google Maps Platform", "google-maps-platform",
     "Quick access to Google Maps. Directions and location sharing from any page.",
     82, 85, 68),
    ("Skyscanner", "skyscanner",
     "Flight price comparison. Find cheap flights directly from browser.",
     72, 70, 62),
    ("TripAdvisor", "tripadvisor",
     "Travel reviews and price comparison for hotels and restaurants. By Tripadvisor Inc.",
     72, 68, 65),
    ("Wanderlust", "wanderlust",
     "Travel inspiration new tab page. Beautiful destination photos and trip planning.",
     64, 66, 45),
    ("Flightradar24", "flightradar24",
     "Real-time flight tracking. View any flight on a live map. By Flightradar24 AB.",
     74, 72, 55),

    # ── Developer (additional) ───────────────────────────────────────────
    ("GitHub Copilot", "github-copilot",
     "AI pair programmer by GitHub/Microsoft. Code suggestions in browser-based editors.",
     82, 78, 72),
    ("Sourcegraph", "sourcegraph",
     "Code intelligence for GitHub. Go-to-definition, find references across repositories.",
     80, 78, 55),
    ("GitPod", "gitpod",
     "One-click cloud development environments. Launch VS Code from any GitHub repo.",
     78, 76, 52),
    ("Codota (Tabnine)", "tabnine",
     "AI code completion. Supports all major languages. Privacy-focused. By Tabnine.",
     76, 72, 55),
    ("WakaTime", "wakatime",
     "Automatic programming metrics. Track coding time across editors and browsers.",
     74, 72, 48),
    ("Daily.dev", "daily-dev",
     "Developer news feed in new tab. Curated dev articles from top sources.",
     72, 70, 62),
    ("GitHub1s", "github1s",
     "Open any GitHub repo in VS Code in browser. One-second GitHub browsing.",
     70, 68, 48),
    ("Gitako", "gitako",
     "File tree for GitHub. Navigate repositories with sidebar file explorer. Open source.",
     72, 70, 42),
    ("OctoLinker", "octolinker",
     "Navigate through import statements on GitHub. Jump to dependency source code.",
     74, 72, 45),
    ("GitHub Hovercard", "github-hovercard",
     "Hover over GitHub links for quick user, repo, and issue previews.",
     70, 68, 42),

    # ── Parental Controls ────────────────────────────────────────────────
    ("BlockSite", "blocksite",
     "Block distracting websites and set browsing schedules. Parental controls included.",
     70, 68, 72),
    ("Bark", "bark",
     "Parental monitoring extension. Content monitoring for child safety. By Bark Technologies.",
     72, 74, 55),
    ("Qustodio", "qustodio",
     "Parental control extension. Monitor and manage children's browsing. By Qustodio.",
     70, 72, 52),
    ("Family Link", "family-link",
     "Google Family Link extension for supervised Chrome profiles. By Google.",
     78, 82, 55),
    ("Net Nanny", "net-nanny",
     "Web filtering and parental controls. Block inappropriate content. By Zift.",
     68, 70, 52),

    # ── Ecommerce ────────────────────────────────────────────────────────
    ("Shopify", "shopify",
     "Shopify store management extension. Quick access to admin and orders.",
     78, 76, 65),
    ("WooCommerce", "woocommerce",
     "Quick access to WooCommerce store management from browser.",
     72, 70, 55),
    ("AliExpress Tools", "aliexpress-tools",
     "Product research and price tracking for AliExpress. Seller ratings and reviews.",
     62, 55, 62),
    ("Amazon Assistant", "amazon-assistant",
     "Price comparison and deals from Amazon. Quick access to wish lists. By Amazon.",
     72, 68, 75),
    ("eBay", "ebay",
     "Quick access to eBay notifications, watch list, and selling tools. By eBay Inc.",
     74, 72, 68),

    # ── Weather & Time ───────────────────────────────────────────────────
    ("Weather Extension", "weather-extension",
     "Current weather and forecast in toolbar. Multiple location support.",
     66, 64, 65),
    ("Timezone Converter", "timezone-converter",
     "Convert times between timezones. World clock in browser toolbar.",
     68, 70, 48),
    ("World Clocks", "world-clocks",
     "Multiple timezone clocks in new tab or popup. Customizable locations.",
     64, 66, 42),
    ("AccuWeather", "accuweather",
     "Weather forecasts and alerts from AccuWeather. Real-time weather data.",
     70, 68, 60),
    ("Weather.com", "weather-com",
     "The Weather Channel extension. Forecasts, radar, and severe weather alerts.",
     70, 68, 62),

    # ── Text Editing & Markdown ──────────────────────────────────────────
    ("StackEdit", "stackedit",
     "In-browser Markdown editor. Live preview, sync with Google Drive and GitHub.",
     74, 76, 52),
    ("Markdown Here", "markdown-here",
     "Write emails in Markdown and convert to HTML. Works with Gmail and Outlook.",
     76, 78, 55),
    ("Docs to Markdown", "docs-to-markdown",
     "Convert Google Docs to clean Markdown. Preserve formatting and links.",
     70, 72, 48),
    ("MarkdownPad", "markdownpad",
     "Markdown preview for text areas. Write Markdown anywhere on the web.",
     66, 68, 38),

    # ── Photo & Image ────────────────────────────────────────────────────
    ("Remove.bg", "remove-bg",
     "Remove image backgrounds with AI. One-click background removal. By Canva/Kaleido.",
     74, 72, 62),
    ("TinEye Reverse Image Search", "tineye",
     "Reverse image search. Find where images appear online. By TinEye.",
     76, 78, 58),
    ("Search by Image", "search-by-image",
     "Reverse image search using Google, Bing, Yandex, and TinEye. Open source.",
     74, 72, 55),
    ("Image Size Info", "image-size-info",
     "Display image dimensions and file size on right-click. Simple and lightweight.",
     66, 68, 45),
    ("Bulk Image Downloader", "bulk-image-downloader",
     "Download multiple images from web pages. Filter by size, type, and URL pattern.",
     64, 60, 52),

    # ── Data & Spreadsheet ───────────────────────────────────────────────
    ("Google Sheets Quick Access", "google-sheets-quick",
     "Quick access to Google Sheets from browser toolbar. Recent files and new sheet.",
     78, 82, 62),
    ("Table Capture", "table-capture",
     "Extract HTML tables to Google Sheets, CSV, or clipboard. One-click table export.",
     72, 70, 55),
    ("Column Copy", "column-copy",
     "Copy columns from HTML tables. Select and copy specific table columns.",
     66, 68, 38),
    ("Airtable Web Clipper", "airtable-web-clipper",
     "Save web content to Airtable bases. Quick data entry from any page.",
     74, 72, 52),

    # ── Calendar & Scheduling ────────────────────────────────────────────
    ("Checker Plus for Calendar", "checker-plus-calendar",
     "View and manage Google Calendar without opening the app. Desktop notifications.",
     74, 72, 62),
    ("Cal.com", "cal-com",
     "Open-source scheduling extension. Create and share meeting links.",
     72, 74, 48),
    ("Fantastical", "fantastical",
     "Quick calendar access and event creation from browser. By Flexibits.",
     70, 72, 42),
    ("Calendso", "calendso",
     "Self-hosted scheduling integration. Open source Calendly alternative.",
     70, 74, 38),

    # ── Networking & Infrastructure ──────────────────────────────────────
    ("Shodan", "shodan",
     "Open ports and vulnerabilities lookup. Server reconnaissance tool. By Shodan.",
     78, 72, 48),
    ("BuiltWith", "builtwith",
     "Technology lookup for websites. Identify hosting, frameworks, and analytics.",
     74, 70, 55),
    ("IPvFoo", "ipvfoo",
     "Display IP address of current site. Show IPv4/IPv6 connections in toolbar.",
     70, 74, 42),
    ("Proxy SwitchyOmega", "proxy-switchyomega",
     "Advanced proxy switcher. Manage and switch between multiple proxy profiles. Open source.",
     78, 74, 62),
    ("ModHeader", "modheader",
     "Modify HTTP request and response headers. Useful for API testing and debugging.",
     74, 68, 55),
    ("CORS Unblock", "cors-unblock",
     "Bypass CORS restrictions for development. Add Access-Control-Allow-Origin headers.",
     68, 58, 52),
    ("Allow CORS", "allow-cors",
     "Toggle CORS headers for local development. Quick enable/disable CORS bypass.",
     66, 56, 48),
    ("HTTP/2 and SPDY Indicator", "http2-indicator",
     "Show HTTP/2 and SPDY protocol support in toolbar. Visual protocol indicator.",
     68, 72, 38),
    ("Requestly", "requestly",
     "HTTP request modifier. Redirect URLs, modify headers, and mock API responses.",
     74, 68, 52),
    ("REST Client", "rest-client",
     "Simple REST API client in browser. Send HTTP requests and inspect responses.",
     70, 68, 48),

    # ── Workflow & Integrations ──────────────────────────────────────────
    ("Make (Integromat)", "make-integromat",
     "Visual automation platform. Connect apps and automate workflows without code.",
     74, 72, 55),
    ("Notion AI", "notion-ai",
     "AI writing and summarization in Notion. Draft, translate, and brainstorm. By Notion Labs.",
     78, 74, 65),
    ("Coda", "coda",
     "Doc-powered workspace extension. Create tasks from any web page. By Coda.",
     72, 70, 52),
    ("Agilix BrainHoney", "agilix-brainhoney",
     "Learning management system integration. Educational content access.",
     62, 64, 35),
    ("Slite", "slite",
     "Team knowledge base extension. Save and organize team documentation.",
     68, 70, 42),

    # ── Survey & Feedback ────────────────────────────────────────────────
    ("Typeform", "typeform",
     "Create and share beautiful forms. Quick access to Typeform workspace. By Typeform.",
     74, 72, 58),
    ("SurveyMonkey", "surveymonkey",
     "Survey creation and management from browser. Quick poll creation. By Momentive.",
     72, 70, 60),
    ("Google Forms", "google-forms",
     "Quick access to Google Forms. Create surveys and quizzes. By Google.",
     82, 85, 65),
    ("JotForm", "jotform",
     "Online form builder extension. Create and manage forms from browser.",
     70, 68, 55),
    ("Tally", "tally",
     "Free form builder extension. Create forms that look and feel native. No account needed.",
     70, 72, 42),

    # ── Communication (additional) ───────────────────────────────────────
    ("Grammarly for Gmail", "grammarly-gmail",
     "Grammar and writing suggestions specifically for Gmail compose. By Grammarly.",
     80, 75, 85),
    ("Mailchimp", "mailchimp",
     "Email marketing extension. Subscribe forms and campaign quick access. By Intuit.",
     74, 72, 62),
    ("Intercom", "intercom",
     "Customer messaging extension. Chat and support integration for SaaS. By Intercom.",
     76, 74, 58),
    ("Drift", "drift",
     "Conversational marketing and sales chatbot. Quick access to conversations.",
     72, 70, 52),
    ("Zendesk", "zendesk",
     "Customer support extension. Quick ticket access and help desk. By Zendesk Inc.",
     76, 74, 60),

    # ── Fonts & Typography ───────────────────────────────────────────────
    ("Google Fonts Previewer", "google-fonts-previewer",
     "Preview Google Fonts on any website. Replace page fonts instantly.",
     70, 72, 48),
    ("Font Swap", "font-swap",
     "Replace fonts on any web page. Compare typography options in real-time.",
     66, 68, 38),
    ("Type Sample", "type-sample",
     "Identify and preview fonts. Click any text to see font details.",
     68, 70, 42),

    # ── Presentation & Content ───────────────────────────────────────────
    ("Beautiful.ai", "beautiful-ai",
     "AI-powered presentation design. Smart formatting and layout suggestions.",
     72, 70, 52),
    ("Pitch", "pitch",
     "Collaborative presentation extension. Create and share decks from browser.",
     70, 68, 48),
    ("Canva", "canva",
     "Quick access to Canva design tools. Create designs from browser content. By Canva.",
     78, 74, 72),
    ("Lumen5", "lumen5",
     "AI video creator. Turn blog posts into videos. Content repurposing tool.",
     68, 66, 48),
    ("Veed.io", "veed-io",
     "Online video editor. Record, edit, and share videos from browser.",
     68, 66, 52),

    # ── Legal & Compliance ───────────────────────────────────────────────
    ("Terms of Service; Didn't Read", "tosdr",
     "Rate and label terms of service. Know your rights before agreeing. Open source.",
     80, 82, 52),
    ("Cookie Notice Blocker", "cookie-notice-blocker",
     "Auto-dismiss cookie consent banners. Clean browsing without cookie popups.",
     72, 70, 68),
    ("I Don't Care About Cookies", "i-dont-care-about-cookies",
     "Remove cookie warnings from websites. Auto-accept or block cookie notices.",
     74, 70, 72),
    ("Consent-O-Matic", "consent-o-matic",
     "Automatic cookie consent handling. Respects your privacy choices. Open source.",
     78, 80, 55),
    ("GDPR Cookie Consent", "gdpr-cookie-consent",
     "Manage GDPR cookie consents across websites. Centralized cookie preferences.",
     68, 70, 45),

    # ── Coupons & Deals (additional) ─────────────────────────────────────
    ("Coupert", "coupert",
     "Automatic coupon finder. Tests and applies codes at checkout. Cash back rewards.",
     66, 60, 62),
    ("PayPal Honey", "paypal-honey",
     "PayPal-integrated coupon finder. Gold status rewards program. By PayPal.",
     70, 65, 80),
    ("Wikibuy", "wikibuy",
     "Price comparison and coupon tool. Now Capital One Shopping. By Capital One.",
     66, 60, 70),
    ("Piggy", "piggy",
     "Automatic coupons and cash back. Apply codes at checkout and earn rewards.",
     62, 58, 55),

    # ── Search Enhancement ───────────────────────────────────────────────
    ("SearchGPT", "searchgpt",
     "AI-enhanced search results. GPT-powered answers alongside Google results.",
     68, 62, 58),
    ("Kagi Search", "kagi-search",
     "Premium search engine extension. Ad-free, privacy-focused search. By Kagi Inc.",
     76, 80, 42),
    ("Startpage Privacy Protection", "startpage-privacy",
     "Private search and anonymous browsing. No tracking or profiling. By Startpage.",
     80, 84, 48),
    ("Ecosia", "ecosia",
     "Search engine that plants trees. Set Ecosia as default search. Carbon-negative.",
     76, 78, 58),
    ("Brave Search", "brave-search",
     "Privacy-focused search by Brave. Independent index without tracking.",
     78, 82, 52),
    ("You.com", "you-com",
     "AI search engine extension. Customizable search with AI chat and apps.",
     70, 68, 48),
    ("Neeva", "neeva",
     "Ad-free, private search engine extension. Subscription-based, no ads.",
     72, 76, 38),
    ("Presearch", "presearch",
     "Decentralized search engine. Earn crypto tokens for searching. Web3 search.",
     62, 58, 42),
    ("Wolfram Alpha", "wolfram-alpha",
     "Computational knowledge engine. Instant answers to factual queries. By Wolfram Research.",
     82, 84, 55),
    ("Vimium", "vimium",
     "Vim-like keyboard navigation for Chrome. Navigate web pages without a mouse. Open source.",
     82, 80, 55),
    ("Pushover", "pushover",
     "Push notification service. Send custom notifications to phone from browser events.",
     68, 70, 42),
]
# fmt: on


def seed():
    log.info(f"Chrome Seeds: inserting {len(EXTENSIONS)} king extensions")
    session = get_session()
    total = 0

    for name, slug, desc, score, sec, pop in EXTENSIONS:
        grade = _grade(score)
        try:
            session.execute(text("""
                INSERT INTO software_registry
                    (name, slug, registry, description, trust_score, trust_grade,
                     enriched_at, created_at, security_score, popularity_score, is_king)
                VALUES
                    (:name, :slug, 'chrome', :desc, :score, :grade,
                     NOW(), NOW(), :sec, :pop, true)
                ON CONFLICT (registry, slug) DO UPDATE SET
                    name = EXCLUDED.name,
                    description = EXCLUDED.description,
                    trust_score = EXCLUDED.trust_score,
                    trust_grade = EXCLUDED.trust_grade,
                    security_score = EXCLUDED.security_score,
                    popularity_score = EXCLUDED.popularity_score,
                    is_king = true,
                    enriched_at = NOW()
            """), {
                "name": name, "slug": slug, "desc": desc,
                "score": score, "grade": grade,
                "sec": sec, "pop": pop,
            })
            total += 1
        except Exception as e:
            log.warning(f"{slug}: {e}")
            session.rollback()

        if total % 100 == 0 and total > 0:
            session.commit()
            log.info(f"  {total} extensions seeded...")

    session.commit()
    session.close()
    log.info(f"Chrome Seeds complete: {total} king extensions seeded")
    return total


if __name__ == "__main__":
    seed()
