#!/usr/bin/env python3
"""SaaS Seeds — seed 500 SaaS/online services into software_registry."""
import logging
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from agentindex.db.models import get_session
from sqlalchemy import text

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)-6s %(message)s")
log = logging.getLogger("saas_seeds")

SAAS = [
    # ── Design ───────────────────────────────────────────────────────────
    {"name": "Canva", "slug": "canva", "score": 85, "grade": "A",
     "desc": "Online graphic design platform with drag-and-drop editor and templates. Australian company valued at $26B."},
    {"name": "Figma", "slug": "figma", "score": 88, "grade": "A",
     "desc": "Collaborative interface design tool used by product teams worldwide. Acquired by Adobe (deal later abandoned), independent company."},
    {"name": "Adobe Creative Cloud", "slug": "adobe-creative-cloud", "score": 92, "grade": "A+",
     "desc": "Suite of creative applications including Photoshop, Illustrator, and Premiere Pro. Adobe Inc. (ADBE), SOC2 certified."},
    {"name": "Sketch", "slug": "sketch", "score": 78, "grade": "B+",
     "desc": "Vector graphics editor and digital design toolkit for macOS. Dutch company, popular among UI/UX designers."},
    {"name": "InVision", "slug": "invision", "score": 65, "grade": "B-",
     "desc": "Digital product design and prototyping platform. Winding down operations as of 2024."},
    {"name": "Miro", "slug": "miro", "score": 83, "grade": "A-",
     "desc": "Online collaborative whiteboard platform for distributed teams. SOC2 Type II certified."},
    {"name": "Framer", "slug": "framer", "score": 76, "grade": "B+",
     "desc": "Web design and publishing platform with no-code capabilities. Dutch company focused on responsive sites."},
    {"name": "Webflow", "slug": "webflow", "score": 80, "grade": "A-",
     "desc": "Visual web development platform enabling designers to build responsive websites without code. SOC2 Type II certified."},
    {"name": "Lucidchart", "slug": "lucidchart", "score": 82, "grade": "A-",
     "desc": "Web-based diagramming and visual collaboration application. Part of Lucid Software, SOC2 certified."},
    {"name": "Balsamiq", "slug": "balsamiq", "score": 74, "grade": "B",
     "desc": "Rapid wireframing tool for UI/UX design. Small independent company focused on low-fidelity mockups."},
    {"name": "Penpot", "slug": "penpot", "score": 70, "grade": "B",
     "desc": "Open-source design and prototyping platform. Backed by Kaleidos, fully web-based."},
    {"name": "Lunacy", "slug": "lunacy", "score": 68, "grade": "B-",
     "desc": "Free graphic design software with AI-powered tools. Developed by Icons8."},
    {"name": "Visme", "slug": "visme", "score": 72, "grade": "B",
     "desc": "Visual content creation platform for presentations, infographics, and documents."},
    {"name": "Crello (VistaCreate)", "slug": "vistacreate", "score": 71, "grade": "B",
     "desc": "Graphic design tool rebranded from Crello. Owned by Vista (formerly Vistaprint)."},
    {"name": "Procreate", "slug": "procreate", "score": 80, "grade": "A-",
     "desc": "Digital illustration app for iPad and iPhone. Australian independent company, one-time purchase model."},
    {"name": "Pixlr", "slug": "pixlr", "score": 67, "grade": "B-",
     "desc": "Cloud-based photo editing suite. Owned by 123RF/Inmagine Group."},
    {"name": "Gravit Designer (Corel Vector)", "slug": "corel-vector", "score": 70, "grade": "B",
     "desc": "Cross-platform vector design application. Acquired by Corel, now part of CorelDRAW suite."},
    {"name": "Whimsical", "slug": "whimsical", "score": 74, "grade": "B",
     "desc": "Visual collaboration tool for flowcharts, wireframes, and mind maps. San Francisco-based startup."},
    {"name": "Marvel App", "slug": "marvel-app", "score": 66, "grade": "B-",
     "desc": "Design and prototyping platform for web and mobile apps. London-based company."},
    {"name": "Zeplin", "slug": "zeplin", "score": 73, "grade": "B",
     "desc": "Design handoff and collaboration tool connecting designers and developers. Integrates with Figma, Sketch."},
    {"name": "Abstract", "slug": "abstract", "score": 64, "grade": "C+",
     "desc": "Design version control and collaboration platform. Acquired by Adobe in 2021."},
    {"name": "Origami Studio", "slug": "origami-studio", "score": 75, "grade": "B+",
     "desc": "Free interactive design prototyping tool developed by Meta for mobile app design."},
    {"name": "Principle", "slug": "principle", "score": 72, "grade": "B",
     "desc": "macOS design tool for creating animated and interactive user interface designs."},
    {"name": "ProtoPie", "slug": "protopie", "score": 71, "grade": "B",
     "desc": "Advanced interaction design prototyping tool. Korean company with global user base."},
    {"name": "UXPin", "slug": "uxpin", "score": 73, "grade": "B",
     "desc": "Full-stack UX design platform with code-based design system capabilities. Polish-American company."},

    # ── Productivity ──────────────────────────────────────────────────────
    {"name": "Notion", "slug": "notion", "score": 85, "grade": "A",
     "desc": "All-in-one workspace combining notes, docs, wikis, and project management. SOC2 Type II certified."},
    {"name": "Airtable", "slug": "airtable", "score": 83, "grade": "A-",
     "desc": "Cloud-based spreadsheet-database hybrid platform. SOC2 Type II and ISO 27001 certified."},
    {"name": "Monday.com", "slug": "monday-com", "score": 85, "grade": "A",
     "desc": "Work operating system for teams to manage projects and workflows. Public company (MNDY), SOC2 certified."},
    {"name": "Asana", "slug": "asana", "score": 85, "grade": "A",
     "desc": "Work management platform for team collaboration and project tracking. Public company (ASAN), SOC2 certified."},
    {"name": "Trello", "slug": "trello", "score": 82, "grade": "A-",
     "desc": "Kanban-style project management board. Owned by Atlassian, SOC2 certified."},
    {"name": "ClickUp", "slug": "clickup", "score": 80, "grade": "A-",
     "desc": "All-in-one productivity platform with tasks, docs, goals, and chat. SOC2 Type II certified."},
    {"name": "Todoist", "slug": "todoist", "score": 80, "grade": "A-",
     "desc": "Task management and to-do list application. Developed by Doist, remote-first company."},
    {"name": "Linear", "slug": "linear", "score": 82, "grade": "A-",
     "desc": "Issue tracking and project management tool for software teams. SOC2 Type II certified."},
    {"name": "Coda", "slug": "coda", "score": 78, "grade": "B+",
     "desc": "All-in-one document platform blending docs, spreadsheets, and applications. Founded by ex-Google/YouTube team."},
    {"name": "Obsidian", "slug": "obsidian", "score": 79, "grade": "B+",
     "desc": "Private knowledge base using local Markdown files. Privacy-focused, data stored locally by default."},
    {"name": "Roam Research", "slug": "roam-research", "score": 68, "grade": "B-",
     "desc": "Networked note-taking tool with bi-directional linking. Small independent team."},
    {"name": "Bear", "slug": "bear", "score": 76, "grade": "B+",
     "desc": "Elegant writing and note-taking app for Apple devices. Developed by Shiny Frog, Italian studio."},
    {"name": "Craft", "slug": "craft", "score": 77, "grade": "B+",
     "desc": "Document and note-taking app with rich formatting. Apple Design Award winner, Hungarian company."},
    {"name": "Capacities", "slug": "capacities", "score": 67, "grade": "B-",
     "desc": "Object-based note-taking app connecting ideas. German startup in early growth stage."},
    {"name": "Mem", "slug": "mem", "score": 65, "grade": "B-",
     "desc": "AI-powered workspace and note-taking tool. Venture-backed San Francisco startup."},
    {"name": "Logseq", "slug": "logseq", "score": 72, "grade": "B",
     "desc": "Open-source knowledge management and collaboration platform with outliner-style editing."},
    {"name": "Taskade", "slug": "taskade", "score": 69, "grade": "B-",
     "desc": "Unified workspace with tasks, notes, and video chat for teams. AI-powered features."},
    {"name": "Evernote", "slug": "evernote", "score": 70, "grade": "B",
     "desc": "Note-taking and task management application. Acquired by Bending Spoons in 2023."},
    {"name": "Microsoft OneNote", "slug": "microsoft-onenote", "score": 88, "grade": "A",
     "desc": "Free-form note-taking application. Part of Microsoft 365 suite, SOC2 and ISO 27001 certified."},
    {"name": "Apple Notes", "slug": "apple-notes", "score": 87, "grade": "A",
     "desc": "Note-taking application built into Apple platforms. End-to-end encrypted with iCloud."},
    {"name": "Google Keep", "slug": "google-keep", "score": 86, "grade": "A",
     "desc": "Note-taking service by Google. Integrated with Google Workspace, SOC2 certified."},
    {"name": "Any.do", "slug": "any-do", "score": 70, "grade": "B",
     "desc": "Task management and daily planner application. Israeli startup with cross-platform support."},
    {"name": "Things 3", "slug": "things-3", "score": 78, "grade": "B+",
     "desc": "Personal task manager for Apple devices. Developed by Cultured Code, German company."},
    {"name": "Fantastical", "slug": "fantastical", "score": 77, "grade": "B+",
     "desc": "Calendar and tasks app for Apple platforms. Developed by Flexibits."},

    # ── Communication ─────────────────────────────────────────────────────
    {"name": "Slack", "slug": "slack", "score": 90, "grade": "A+",
     "desc": "Business communication platform with channels and integrations. Owned by Salesforce, SOC2/ISO 27001 certified."},
    {"name": "Zoom", "slug": "zoom", "score": 88, "grade": "A",
     "desc": "Video conferencing and online meeting platform. Public company (ZM), SOC2 Type II certified."},
    {"name": "Microsoft Teams", "slug": "microsoft-teams", "score": 91, "grade": "A+",
     "desc": "Business communication platform with chat, video, and file sharing. Part of Microsoft 365, SOC2/ISO 27001."},
    {"name": "Discord", "slug": "discord", "score": 78, "grade": "B+",
     "desc": "Voice, video, and text communication platform. Originally for gamers, now broader community use."},
    {"name": "Google Meet", "slug": "google-meet", "score": 89, "grade": "A",
     "desc": "Video conferencing service by Google. Part of Google Workspace, SOC2/ISO 27001 certified."},
    {"name": "Loom", "slug": "loom", "score": 80, "grade": "A-",
     "desc": "Asynchronous video messaging platform for workplace communication. Acquired by Atlassian in 2023."},
    {"name": "Gather", "slug": "gather", "score": 68, "grade": "B-",
     "desc": "Virtual office platform with spatial video chat and customizable spaces. Venture-backed startup."},
    {"name": "Around", "slug": "around", "score": 62, "grade": "C+",
     "desc": "Video calling tool designed for hybrid work. Acquired by Miro in 2022."},
    {"name": "Whereby", "slug": "whereby", "score": 72, "grade": "B",
     "desc": "Browser-based video meeting platform with no downloads required. Norwegian company."},
    {"name": "Element (Matrix)", "slug": "element-matrix", "score": 74, "grade": "B",
     "desc": "Decentralized, end-to-end encrypted messaging client built on the Matrix protocol. UK-based."},
    {"name": "Signal", "slug": "signal", "score": 82, "grade": "A-",
     "desc": "Privacy-focused encrypted messaging app. Run by Signal Foundation, a nonprofit organization."},
    {"name": "Telegram", "slug": "telegram", "score": 72, "grade": "B",
     "desc": "Cloud-based instant messaging service with 900M+ users. Founded by Pavel Durov."},
    {"name": "WhatsApp Business", "slug": "whatsapp-business", "score": 85, "grade": "A",
     "desc": "Business communication tool by Meta. End-to-end encrypted, used by millions of businesses."},
    {"name": "RingCentral", "slug": "ringcentral", "score": 84, "grade": "A-",
     "desc": "Cloud communications platform with phone, video, and messaging. Public company (RNG), SOC2 certified."},
    {"name": "Webex", "slug": "webex", "score": 85, "grade": "A",
     "desc": "Video conferencing and online meeting platform by Cisco. Enterprise-grade security, SOC2/ISO 27001."},
    {"name": "GoTo Meeting", "slug": "goto-meeting", "score": 78, "grade": "B+",
     "desc": "Online meeting and video conferencing platform. Part of GoTo (formerly LogMeIn)."},
    {"name": "Dialpad", "slug": "dialpad", "score": 76, "grade": "B+",
     "desc": "AI-powered cloud communications platform for business. SOC2 Type II certified."},
    {"name": "Vonage", "slug": "vonage", "score": 80, "grade": "A-",
     "desc": "Cloud communications provider with APIs for messaging, voice, and video. Owned by Ericsson."},
    {"name": "Twist", "slug": "twist", "score": 69, "grade": "B-",
     "desc": "Async-first team communication tool. Built by Doist (makers of Todoist)."},
    {"name": "Chanty", "slug": "chanty", "score": 60, "grade": "C+",
     "desc": "Team chat and task management platform for small businesses. Simple alternative to Slack."},
    {"name": "Pumble", "slug": "pumble", "score": 62, "grade": "C+",
     "desc": "Free team communication app with unlimited message history. Made by Clockify team."},
    {"name": "Mattermost", "slug": "mattermost", "score": 76, "grade": "B+",
     "desc": "Open-source, self-hosted messaging platform for teams. Enterprise and community editions."},
    {"name": "Rocket.Chat", "slug": "rocket-chat", "score": 73, "grade": "B",
     "desc": "Open-source team collaboration platform with real-time messaging and video. SOC2 certified."},

    # ── DevTools ──────────────────────────────────────────────────────────
    {"name": "GitHub", "slug": "github", "score": 93, "grade": "A+",
     "desc": "Code hosting platform for version control and collaboration. Owned by Microsoft, SOC2/ISO 27001 certified."},
    {"name": "GitLab", "slug": "gitlab", "score": 88, "grade": "A",
     "desc": "DevSecOps platform providing CI/CD, source control, and security scanning. Public company (GTLB), SOC2 certified."},
    {"name": "Vercel", "slug": "vercel", "score": 84, "grade": "A-",
     "desc": "Frontend cloud platform for deploying web applications. Creators of Next.js, SOC2 Type II certified."},
    {"name": "Netlify", "slug": "netlify", "score": 82, "grade": "A-",
     "desc": "Web development platform for building and deploying modern web projects. SOC2 Type II certified."},
    {"name": "Railway", "slug": "railway", "score": 74, "grade": "B",
     "desc": "Infrastructure platform for deploying applications with instant provisioning. Growing developer platform."},
    {"name": "Render", "slug": "render", "score": 76, "grade": "B+",
     "desc": "Unified cloud platform to build and run apps and websites. SOC2 Type II certified."},
    {"name": "Fly.io", "slug": "fly-io", "score": 74, "grade": "B",
     "desc": "Platform for running full-stack apps globally on edge infrastructure. Developer-focused."},
    {"name": "Supabase", "slug": "supabase", "score": 80, "grade": "A-",
     "desc": "Open-source Firebase alternative with PostgreSQL. SOC2 Type II certified."},
    {"name": "PlanetScale", "slug": "planetscale", "score": 79, "grade": "B+",
     "desc": "Serverless MySQL database platform with branching and deployment workflows. SOC2 Type II certified."},
    {"name": "Neon", "slug": "neon", "score": 76, "grade": "B+",
     "desc": "Serverless PostgreSQL platform with branching and autoscaling. Open-source foundation, SOC2 certified."},
    {"name": "Cloudflare", "slug": "cloudflare", "score": 92, "grade": "A+",
     "desc": "Web infrastructure and security company providing CDN, DNS, DDoS protection, and edge computing. Public company (NET)."},
    {"name": "DigitalOcean", "slug": "digitalocean", "score": 84, "grade": "A-",
     "desc": "Cloud infrastructure provider for developers and small businesses. Public company (DOCN), SOC2 certified."},
    {"name": "Heroku", "slug": "heroku", "score": 75, "grade": "B+",
     "desc": "Cloud platform-as-a-service for building, deploying, and managing applications. Owned by Salesforce."},
    {"name": "Replit", "slug": "replit", "score": 76, "grade": "B+",
     "desc": "Browser-based collaborative IDE and deployment platform. Popular for education and rapid prototyping."},
    {"name": "Bitbucket", "slug": "bitbucket", "score": 82, "grade": "A-",
     "desc": "Git-based source code hosting service. Owned by Atlassian, SOC2 certified."},
    {"name": "AWS", "slug": "aws", "score": 95, "grade": "A+",
     "desc": "Amazon Web Services, largest cloud computing platform globally. SOC2/ISO 27001/FedRAMP certified."},
    {"name": "Google Cloud Platform", "slug": "google-cloud-platform", "score": 94, "grade": "A+",
     "desc": "Cloud computing services by Google. SOC2/ISO 27001/FedRAMP certified. Alphabet (GOOGL)."},
    {"name": "Microsoft Azure", "slug": "microsoft-azure", "score": 94, "grade": "A+",
     "desc": "Cloud computing platform by Microsoft. SOC2/ISO 27001/FedRAMP certified. Microsoft (MSFT)."},
    {"name": "Hetzner", "slug": "hetzner", "score": 80, "grade": "A-",
     "desc": "German web hosting and cloud provider known for competitive pricing. ISO 27001 certified."},
    {"name": "Linode (Akamai)", "slug": "linode", "score": 80, "grade": "A-",
     "desc": "Cloud computing provider acquired by Akamai Technologies. SOC2 certified."},
    {"name": "Vultr", "slug": "vultr", "score": 76, "grade": "B+",
     "desc": "Cloud infrastructure provider with global data centers. Privately held, developer-focused."},
    {"name": "Docker Hub", "slug": "docker-hub", "score": 82, "grade": "A-",
     "desc": "Container image registry and repository service by Docker Inc. SOC2 Type II certified."},
    {"name": "Terraform Cloud", "slug": "terraform-cloud", "score": 84, "grade": "A-",
     "desc": "Infrastructure-as-code collaboration platform by HashiCorp. SOC2 Type II certified."},
    {"name": "CircleCI", "slug": "circleci", "score": 80, "grade": "A-",
     "desc": "Continuous integration and delivery platform. SOC2 Type II certified, security incident in 2023."},
    {"name": "Travis CI", "slug": "travis-ci", "score": 68, "grade": "B-",
     "desc": "Continuous integration service for building and testing software. Lost market share to GitHub Actions."},
    {"name": "Jenkins (CloudBees)", "slug": "jenkins-cloudbees", "score": 78, "grade": "B+",
     "desc": "Open-source automation server with managed cloud offering by CloudBees."},
    {"name": "Sentry", "slug": "sentry", "score": 82, "grade": "A-",
     "desc": "Application performance monitoring and error tracking platform. SOC2 Type II certified, open-source core."},
    {"name": "Datadog", "slug": "datadog", "score": 90, "grade": "A+",
     "desc": "Cloud monitoring and observability platform for infrastructure and applications. Public company (DDOG), SOC2 certified."},
    {"name": "New Relic", "slug": "new-relic", "score": 85, "grade": "A",
     "desc": "Observability platform for monitoring application performance. Public company (NEWR), SOC2 certified."},
    {"name": "PagerDuty", "slug": "pagerduty", "score": 85, "grade": "A",
     "desc": "Incident management platform for real-time operations. Public company (PD), SOC2/ISO 27001 certified."},
    {"name": "LaunchDarkly", "slug": "launchdarkly", "score": 80, "grade": "A-",
     "desc": "Feature management and experimentation platform. SOC2 Type II certified."},
    {"name": "Snyk", "slug": "snyk", "score": 82, "grade": "A-",
     "desc": "Developer security platform for finding and fixing vulnerabilities. SOC2 Type II certified."},
    {"name": "Postman", "slug": "postman", "score": 83, "grade": "A-",
     "desc": "API platform for building, testing, and documenting APIs. SOC2 Type II certified, 30M+ users."},
    {"name": "Insomnia", "slug": "insomnia", "score": 72, "grade": "B",
     "desc": "Open-source API client for REST, GraphQL, and gRPC. Owned by Kong Inc."},

    # ── Payments/Fintech ──────────────────────────────────────────────────
    {"name": "Stripe", "slug": "stripe", "score": 92, "grade": "A+",
     "desc": "Payment processing platform for internet businesses. PCI DSS Level 1, SOC2/ISO 27001 certified."},
    {"name": "PayPal", "slug": "paypal-saas", "score": 90, "grade": "A+",
     "desc": "Online payment system supporting money transfers and payments. Public company (PYPL), PCI DSS certified."},
    {"name": "Square (Block)", "slug": "square", "score": 88, "grade": "A",
     "desc": "Financial services and digital payments company. Public company (SQ), PCI DSS/SOC2 certified."},
    {"name": "Braintree", "slug": "braintree", "score": 87, "grade": "A",
     "desc": "Full-stack payment platform for online and mobile commerce. Owned by PayPal, PCI DSS Level 1."},
    {"name": "Wise", "slug": "wise", "score": 85, "grade": "A",
     "desc": "International money transfer service with multi-currency accounts. Public company (WISE.L), regulated."},
    {"name": "Revolut", "slug": "revolut", "score": 82, "grade": "A-",
     "desc": "Digital banking and financial services app. UK banking license holder, regulated in multiple jurisdictions."},
    {"name": "Plaid", "slug": "plaid", "score": 83, "grade": "A-",
     "desc": "Financial data aggregation platform connecting apps to bank accounts. SOC2 Type II certified."},
    {"name": "Mercury", "slug": "mercury", "score": 82, "grade": "A-",
     "desc": "Banking platform for startups and SMBs. FDIC insured through partner banks."},
    {"name": "Adyen", "slug": "adyen", "score": 90, "grade": "A+",
     "desc": "Payment platform for enterprise businesses. Public company (ADYEN.AS), PCI DSS Level 1 certified."},
    {"name": "Klarna", "slug": "klarna", "score": 80, "grade": "A-",
     "desc": "Buy-now-pay-later and payment services. Swedish fintech, regulated as bank in EU."},
    {"name": "Affirm", "slug": "affirm", "score": 78, "grade": "B+",
     "desc": "Buy-now-pay-later payment network. Public company (AFRM), regulated lender."},
    {"name": "Razorpay", "slug": "razorpay", "score": 80, "grade": "A-",
     "desc": "Payment gateway and financial services for Indian businesses. PCI DSS Level 1 certified."},
    {"name": "Paddle", "slug": "paddle", "score": 78, "grade": "B+",
     "desc": "Payment infrastructure for SaaS companies handling tax compliance. UK-based."},
    {"name": "Chargebee", "slug": "chargebee", "score": 79, "grade": "B+",
     "desc": "Subscription billing and revenue management platform. SOC2 Type II certified."},
    {"name": "Recurly", "slug": "recurly", "score": 77, "grade": "B+",
     "desc": "Subscription management and recurring billing platform. PCI DSS Level 1, SOC2 certified."},
    {"name": "FastSpring", "slug": "fastspring", "score": 76, "grade": "B+",
     "desc": "Full-service ecommerce payment platform for digital products. Handles global tax compliance."},
    {"name": "GoCardless", "slug": "gocardless", "score": 79, "grade": "B+",
     "desc": "Direct debit and bank payment platform. Regulated by FCA, SOC2 certified."},
    {"name": "Mollie", "slug": "mollie", "score": 80, "grade": "A-",
     "desc": "European payment service provider. PCI DSS certified, regulated in Netherlands."},
    {"name": "Checkout.com", "slug": "checkout-com", "score": 82, "grade": "A-",
     "desc": "Cloud-based payment processing platform for enterprise. PCI DSS Level 1, SOC2 certified."},

    # ── E-commerce Platforms ──────────────────────────────────────────────
    {"name": "Shopify", "slug": "shopify", "score": 90, "grade": "A+",
     "desc": "E-commerce platform for online stores and retail point-of-sale systems. Public company (SHOP), SOC2/PCI DSS certified."},
    {"name": "WooCommerce", "slug": "woocommerce", "score": 78, "grade": "B+",
     "desc": "Open-source e-commerce plugin for WordPress. Owned by Automattic, powers millions of stores."},
    {"name": "BigCommerce", "slug": "bigcommerce", "score": 82, "grade": "A-",
     "desc": "E-commerce platform for B2B and B2C merchants. Public company (BIGC), SOC2/PCI DSS certified."},
    {"name": "Squarespace", "slug": "squarespace", "score": 83, "grade": "A-",
     "desc": "Website builder and hosting platform with e-commerce capabilities. SOC2 certified."},
    {"name": "Wix", "slug": "wix", "score": 82, "grade": "A-",
     "desc": "Cloud-based website builder with e-commerce and marketing tools. Public company (WIX), SOC2 certified."},
    {"name": "Gumroad", "slug": "gumroad", "score": 72, "grade": "B",
     "desc": "E-commerce platform for creators to sell digital products. Small independent company."},
    {"name": "LemonSqueezy", "slug": "lemonsqueezy", "score": 70, "grade": "B",
     "desc": "Digital product selling platform handling payments and tax compliance. Indie-friendly alternative to Gumroad."},
    {"name": "Sellfy", "slug": "sellfy", "score": 68, "grade": "B-",
     "desc": "E-commerce platform for selling digital products, subscriptions, and merchandise."},
    {"name": "Ecwid", "slug": "ecwid", "score": 74, "grade": "B",
     "desc": "E-commerce widget that can be added to any website. Acquired by Lightspeed Commerce."},
    {"name": "PrestaShop", "slug": "prestashop", "score": 72, "grade": "B",
     "desc": "Open-source e-commerce platform. French company, freemium model with paid add-ons."},
    {"name": "Volusion", "slug": "volusion", "score": 62, "grade": "C+",
     "desc": "E-commerce platform for small to medium businesses. Filed for Chapter 11 in 2020."},
    {"name": "3dcart (Shift4Shop)", "slug": "shift4shop", "score": 65, "grade": "B-",
     "desc": "E-commerce platform now owned by Shift4 Payments. Free plan available with Shift4 processing."},
    {"name": "Patreon", "slug": "patreon", "score": 78, "grade": "B+",
     "desc": "Membership platform for creators to offer subscriptions. Well-established creator economy tool."},
    {"name": "Ko-fi", "slug": "ko-fi", "score": 70, "grade": "B",
     "desc": "Platform for creators to receive support and sell products. UK-based, no-fee donation option."},
    {"name": "Buy Me a Coffee", "slug": "buy-me-a-coffee", "score": 68, "grade": "B-",
     "desc": "Creator support platform for tips and memberships. Simple alternative to Patreon."},

    # ── Marketing ─────────────────────────────────────────────────────────
    {"name": "HubSpot", "slug": "hubspot", "score": 90, "grade": "A+",
     "desc": "CRM platform with marketing, sales, and service tools. Public company (HUBS), SOC2/ISO 27001 certified."},
    {"name": "Mailchimp", "slug": "mailchimp", "score": 86, "grade": "A",
     "desc": "Email marketing and automation platform. Owned by Intuit, SOC2 Type II certified."},
    {"name": "SendGrid", "slug": "sendgrid", "score": 85, "grade": "A",
     "desc": "Cloud-based email delivery and marketing platform. Owned by Twilio, SOC2 certified."},
    {"name": "Twilio", "slug": "twilio", "score": 88, "grade": "A",
     "desc": "Cloud communications platform with APIs for messaging, voice, and email. Public company (TWLO), SOC2 certified."},
    {"name": "Hootsuite", "slug": "hootsuite", "score": 78, "grade": "B+",
     "desc": "Social media management platform for scheduling and analytics. SOC2 Type II certified."},
    {"name": "Buffer", "slug": "buffer", "score": 76, "grade": "B+",
     "desc": "Social media scheduling and analytics platform. Remote-first company with transparent culture."},
    {"name": "SEMrush", "slug": "semrush", "score": 84, "grade": "A-",
     "desc": "Online visibility management platform for SEO, PPC, and content marketing. Public company (SEMR)."},
    {"name": "Ahrefs", "slug": "ahrefs", "score": 83, "grade": "A-",
     "desc": "SEO toolset for backlink analysis, keyword research, and site auditing. Singapore-based."},
    {"name": "Moz", "slug": "moz", "score": 78, "grade": "B+",
     "desc": "SEO software platform for search engine optimization. Acquired by iContact/Zeta Global."},
    {"name": "ConvertKit (Kit)", "slug": "convertkit", "score": 77, "grade": "B+",
     "desc": "Email marketing platform for creators. Rebranded to Kit, focused on newsletter monetization."},
    {"name": "ActiveCampaign", "slug": "activecampaign", "score": 80, "grade": "A-",
     "desc": "Customer experience automation platform with email marketing and CRM. SOC2 Type II certified."},
    {"name": "Klaviyo", "slug": "klaviyo", "score": 85, "grade": "A",
     "desc": "Marketing automation platform for e-commerce. Public company (KVYO), SOC2 certified."},
    {"name": "Brevo (Sendinblue)", "slug": "brevo", "score": 76, "grade": "B+",
     "desc": "All-in-one marketing platform with email, SMS, and CRM. French company, rebranded from Sendinblue."},
    {"name": "Constant Contact", "slug": "constant-contact", "score": 78, "grade": "B+",
     "desc": "Email and digital marketing platform for small businesses. Endurance International Group."},
    {"name": "Drip", "slug": "drip", "score": 74, "grade": "B",
     "desc": "E-commerce marketing automation platform. Focused on DTC and Shopify brands."},
    {"name": "Sprout Social", "slug": "sprout-social", "score": 83, "grade": "A-",
     "desc": "Social media management and analytics platform. Public company (SPT), SOC2 certified."},
    {"name": "Later", "slug": "later", "score": 72, "grade": "B",
     "desc": "Social media scheduling and link-in-bio platform. Acquired Mavrck for influencer marketing."},
    {"name": "Unbounce", "slug": "unbounce", "score": 74, "grade": "B",
     "desc": "Landing page builder and conversion optimization platform. Canadian company."},
    {"name": "Leadpages", "slug": "leadpages", "score": 72, "grade": "B",
     "desc": "Landing page and website builder for lead generation. Part of Redbrick digital media group."},
    {"name": "OptinMonster", "slug": "optinmonster", "score": 70, "grade": "B",
     "desc": "Lead generation and conversion optimization software. WordPress plugin and standalone SaaS."},
    {"name": "Sumo", "slug": "sumo", "score": 66, "grade": "B-",
     "desc": "Email capture and sharing tools for websites. Founded by Noah Kagan (AppSumo)."},
    {"name": "Beehiiv", "slug": "beehiiv", "score": 74, "grade": "B",
     "desc": "Newsletter platform for creators and publishers. Growing alternative to Substack with monetization tools."},
    {"name": "Mailerlite", "slug": "mailerlite", "score": 76, "grade": "B+",
     "desc": "Email marketing platform for small businesses with website builder. Lithuanian company, affordable plans."},

    # ── Storage/Cloud ─────────────────────────────────────────────────────
    {"name": "Dropbox", "slug": "dropbox", "score": 85, "grade": "A",
     "desc": "Cloud storage and file synchronization service. Public company (DBX), SOC2/ISO 27001 certified."},
    {"name": "Google Drive", "slug": "google-drive", "score": 91, "grade": "A+",
     "desc": "Cloud storage service integrated with Google Workspace. SOC2/ISO 27001 certified."},
    {"name": "Box", "slug": "box", "score": 88, "grade": "A",
     "desc": "Cloud content management and file sharing platform for enterprises. Public company (BOX), SOC2/FedRAMP certified."},
    {"name": "MEGA", "slug": "mega", "score": 72, "grade": "B",
     "desc": "End-to-end encrypted cloud storage service. New Zealand-based, 50GB free storage."},
    {"name": "iCloud", "slug": "icloud", "score": 90, "grade": "A+",
     "desc": "Cloud storage and computing service by Apple. End-to-end encryption, integrated with Apple devices."},
    {"name": "OneDrive", "slug": "onedrive", "score": 90, "grade": "A+",
     "desc": "Cloud storage and file hosting service by Microsoft. Part of Microsoft 365, SOC2/ISO 27001 certified."},
    {"name": "Backblaze", "slug": "backblaze", "score": 80, "grade": "A-",
     "desc": "Cloud backup and storage provider with B2 object storage. Public company (BLZE), SOC2 certified."},
    {"name": "Wasabi", "slug": "wasabi", "score": 76, "grade": "B+",
     "desc": "Hot cloud storage provider with competitive pricing and no egress fees."},
    {"name": "pCloud", "slug": "pcloud", "score": 72, "grade": "B",
     "desc": "Swiss cloud storage service with client-side encryption option. Lifetime plans available."},
    {"name": "Tresorit", "slug": "tresorit", "score": 78, "grade": "B+",
     "desc": "End-to-end encrypted cloud storage for businesses. Swiss-Hungarian, acquired by Swiss Post."},
    {"name": "Sync.com", "slug": "sync-com", "score": 74, "grade": "B",
     "desc": "End-to-end encrypted cloud storage service. Canadian company, zero-knowledge encryption."},
    {"name": "IDrive", "slug": "idrive", "score": 74, "grade": "B",
     "desc": "Online backup and cloud storage service with multiple device support."},
    {"name": "SpiderOak", "slug": "spideroak", "score": 70, "grade": "B",
     "desc": "Zero-knowledge encrypted cloud backup and file sharing. Privacy-focused."},

    # ── Writing ───────────────────────────────────────────────────────────
    {"name": "Grammarly", "slug": "grammarly", "score": 83, "grade": "A-",
     "desc": "AI-powered writing assistant for grammar, spelling, and style. SOC2 Type II certified, 30M+ daily users."},
    {"name": "Medium", "slug": "medium", "score": 78, "grade": "B+",
     "desc": "Online publishing platform for reading and writing articles. Founded by Twitter co-founder Ev Williams."},
    {"name": "Substack", "slug": "substack", "score": 78, "grade": "B+",
     "desc": "Newsletter and publishing platform enabling writers to monetize through subscriptions."},
    {"name": "Ghost", "slug": "ghost", "score": 76, "grade": "B+",
     "desc": "Open-source publishing platform for professional blogs and newsletters. Non-profit foundation."},
    {"name": "WordPress.com", "slug": "wordpress-com", "score": 85, "grade": "A",
     "desc": "Managed WordPress hosting and website platform by Automattic. Powers over 40% of the web."},
    {"name": "Hashnode", "slug": "hashnode", "score": 72, "grade": "B",
     "desc": "Blogging platform for developers with custom domain support. Built-in community features."},
    {"name": "DEV.to", "slug": "dev-to", "score": 74, "grade": "B",
     "desc": "Community of software developers sharing articles and discussions. Open-source, owned by Forem."},
    {"name": "Hemingway Editor", "slug": "hemingway-editor", "score": 70, "grade": "B",
     "desc": "Writing app highlighting complex sentences and common errors. Simple, focused editing tool."},
    {"name": "ProWritingAid", "slug": "prowritingaid", "score": 72, "grade": "B",
     "desc": "Grammar checker, style editor, and writing mentor for long-form content."},
    {"name": "Scrivener", "slug": "scrivener", "score": 76, "grade": "B+",
     "desc": "Word processing and project management tool for writers. Developed by Literature & Latte."},
    {"name": "Google Docs", "slug": "google-docs", "score": 91, "grade": "A+",
     "desc": "Online word processor as part of Google Workspace. Real-time collaboration, SOC2/ISO 27001 certified."},
    {"name": "Notion AI", "slug": "notion-ai", "score": 82, "grade": "A-",
     "desc": "AI writing assistant built into Notion workspace. Powered by multiple AI models."},
    {"name": "Quill", "slug": "quill-editor", "score": 68, "grade": "B-",
     "desc": "Open-source WYSIWYG rich text editor for the modern web. JavaScript library."},

    # ── Analytics ─────────────────────────────────────────────────────────
    {"name": "Google Analytics", "slug": "google-analytics", "score": 90, "grade": "A+",
     "desc": "Web analytics service tracking website traffic and user behavior. Google (GOOGL), SOC2 certified."},
    {"name": "Mixpanel", "slug": "mixpanel", "score": 84, "grade": "A-",
     "desc": "Product analytics platform tracking user interactions and events. SOC2 Type II certified."},
    {"name": "Amplitude", "slug": "amplitude", "score": 85, "grade": "A",
     "desc": "Digital analytics platform for product intelligence. Public company (AMPL), SOC2 certified."},
    {"name": "PostHog", "slug": "posthog", "score": 80, "grade": "A-",
     "desc": "Open-source product analytics platform with session recording and feature flags. SOC2 Type II certified."},
    {"name": "Hotjar", "slug": "hotjar", "score": 78, "grade": "B+",
     "desc": "Behavior analytics and user feedback platform with heatmaps and recordings. Owned by Contentsquare."},
    {"name": "FullStory", "slug": "fullstory", "score": 80, "grade": "A-",
     "desc": "Digital experience intelligence platform with session replay. SOC2 Type II certified."},
    {"name": "Plausible", "slug": "plausible", "score": 76, "grade": "B+",
     "desc": "Lightweight, privacy-friendly web analytics. Open-source, EU-based, GDPR compliant by design."},
    {"name": "Fathom Analytics", "slug": "fathom-analytics", "score": 76, "grade": "B+",
     "desc": "Privacy-focused website analytics without cookies. Canadian company, GDPR/CCPA compliant."},
    {"name": "Heap", "slug": "heap", "score": 80, "grade": "A-",
     "desc": "Digital insights platform with automatic event capture. Acquired by Contentsquare."},
    {"name": "Segment", "slug": "segment", "score": 86, "grade": "A",
     "desc": "Customer data platform for collecting and routing analytics data. Owned by Twilio, SOC2 certified."},
    {"name": "Matomo", "slug": "matomo", "score": 76, "grade": "B+",
     "desc": "Open-source web analytics platform. Privacy-focused alternative to Google Analytics, self-hosted option."},
    {"name": "Pendo", "slug": "pendo", "score": 80, "grade": "A-",
     "desc": "Product experience platform with analytics, user guidance, and feedback. SOC2 Type II certified."},
    {"name": "Countly", "slug": "countly", "score": 70, "grade": "B",
     "desc": "Open-source product analytics platform with real-time dashboards. Self-hosted and cloud options."},
    {"name": "Kissmetrics", "slug": "kissmetrics", "score": 66, "grade": "B-",
     "desc": "Behavioral analytics and engagement platform for SaaS and e-commerce."},
    {"name": "LogRocket", "slug": "logrocket", "score": 78, "grade": "B+",
     "desc": "Frontend application monitoring with session replay and error tracking. SOC2 Type II certified."},

    # ── Security ──────────────────────────────────────────────────────────
    {"name": "1Password", "slug": "1password", "score": 90, "grade": "A+",
     "desc": "Password manager for individuals and businesses. SOC2 Type II and ISO 27001 certified."},
    {"name": "LastPass", "slug": "lastpass", "score": 65, "grade": "B-",
     "desc": "Password management service. Major security breaches in 2022 significantly impacted trust."},
    {"name": "Bitwarden", "slug": "bitwarden", "score": 85, "grade": "A",
     "desc": "Open-source password manager with self-hosted option. SOC2 Type II certified."},
    {"name": "Okta", "slug": "okta", "score": 86, "grade": "A",
     "desc": "Identity and access management platform. Public company (OKTA), SOC2/ISO 27001/FedRAMP certified."},
    {"name": "Auth0", "slug": "auth0", "score": 85, "grade": "A",
     "desc": "Identity platform for authentication and authorization. Owned by Okta, SOC2/ISO 27001 certified."},
    {"name": "Duo Security", "slug": "duo-security", "score": 87, "grade": "A",
     "desc": "Multi-factor authentication and secure access platform. Owned by Cisco, SOC2/FedRAMP certified."},
    {"name": "CrowdStrike", "slug": "crowdstrike", "score": 88, "grade": "A",
     "desc": "Cybersecurity platform for endpoint protection. Public company (CRWD), SOC2/FedRAMP certified."},
    {"name": "SentinelOne", "slug": "sentinelone", "score": 85, "grade": "A",
     "desc": "AI-powered endpoint security platform. Public company (S), SOC2/FedRAMP certified."},
    {"name": "NordPass", "slug": "nordpass", "score": 78, "grade": "B+",
     "desc": "Password manager by Nord Security (makers of NordVPN). SOC2 Type II certified."},
    {"name": "Dashlane", "slug": "dashlane", "score": 80, "grade": "A-",
     "desc": "Password manager and digital wallet application. SOC2 Type II certified."},
    {"name": "KeePass", "slug": "keepass", "score": 78, "grade": "B+",
     "desc": "Free, open-source, lightweight password manager. Local-only by default, community-maintained."},
    {"name": "Keeper", "slug": "keeper-security", "score": 82, "grade": "A-",
     "desc": "Password management and security platform. SOC2 Type II and ISO 27001 certified."},
    {"name": "JumpCloud", "slug": "jumpcloud", "score": 80, "grade": "A-",
     "desc": "Open directory platform for identity, access, and device management. SOC2 Type II certified."},
    {"name": "Tailscale", "slug": "tailscale", "score": 82, "grade": "A-",
     "desc": "Zero-config VPN built on WireGuard for secure networking. SOC2 Type II certified."},
    {"name": "Proton VPN", "slug": "proton-vpn", "score": 82, "grade": "A-",
     "desc": "Secure VPN service by Proton AG. Swiss-based, open-source, independently audited."},
    {"name": "NordVPN", "slug": "nordvpn", "score": 80, "grade": "A-",
     "desc": "VPN service by Nord Security. Panama-based, independently audited, 14M+ users."},
    {"name": "ExpressVPN", "slug": "expressvpn", "score": 78, "grade": "B+",
     "desc": "VPN service now owned by Kape Technologies. Independently audited, British Virgin Islands-based."},
    {"name": "Mullvad VPN", "slug": "mullvad-vpn", "score": 82, "grade": "A-",
     "desc": "Privacy-focused VPN service from Sweden. Accepts anonymous payments, independently audited."},

    # ── HR ────────────────────────────────────────────────────────────────
    {"name": "Gusto", "slug": "gusto", "score": 85, "grade": "A",
     "desc": "Cloud-based payroll, benefits, and HR management platform. SOC2 Type II certified."},
    {"name": "BambooHR", "slug": "bamboohr", "score": 83, "grade": "A-",
     "desc": "HR software for small and medium businesses. SOC2 Type II certified."},
    {"name": "Deel", "slug": "deel", "score": 82, "grade": "A-",
     "desc": "Global payroll and compliance platform for hiring international teams. SOC2 Type II certified."},
    {"name": "Remote.com", "slug": "remote-com", "score": 80, "grade": "A-",
     "desc": "Global HR platform for hiring, managing, and paying remote employees. SOC2/ISO 27001 certified."},
    {"name": "Rippling", "slug": "rippling", "score": 84, "grade": "A-",
     "desc": "Workforce management platform combining HR, IT, and finance. SOC2 Type II certified."},
    {"name": "Lattice", "slug": "lattice", "score": 80, "grade": "A-",
     "desc": "People management platform with performance reviews and engagement surveys. SOC2 Type II certified."},
    {"name": "Culture Amp", "slug": "culture-amp", "score": 80, "grade": "A-",
     "desc": "Employee experience platform for engagement, performance, and development. SOC2/ISO 27001 certified."},
    {"name": "Workday", "slug": "workday", "score": 91, "grade": "A+",
     "desc": "Enterprise cloud platform for finance and HR management. Public company (WDAY), SOC2/ISO 27001 certified."},
    {"name": "ADP", "slug": "adp", "score": 90, "grade": "A+",
     "desc": "Human capital management and payroll services provider. Public company (ADP), SOC2 certified."},
    {"name": "Paycom", "slug": "paycom", "score": 85, "grade": "A",
     "desc": "Cloud-based HCM and payroll technology. Public company (PAYC), SOC2 certified."},
    {"name": "Paychex", "slug": "paychex", "score": 86, "grade": "A",
     "desc": "Payroll, HR, and benefits services for small to medium businesses. Public company (PAYX)."},
    {"name": "15Five", "slug": "15five", "score": 74, "grade": "B",
     "desc": "Performance management platform with continuous feedback and OKR tracking."},
    {"name": "Personio", "slug": "personio", "score": 80, "grade": "A-",
     "desc": "HR management platform for small and medium European businesses. German company, SOC2 certified."},
    {"name": "Bob (HiBob)", "slug": "hibob", "score": 78, "grade": "B+",
     "desc": "Modern HR platform for mid-sized companies. Israeli company, growing globally."},
    {"name": "Oyster HR", "slug": "oyster-hr", "score": 76, "grade": "B+",
     "desc": "Global employment platform for distributed companies. Handles compliance in 180+ countries."},
    {"name": "Justworks", "slug": "justworks", "score": 80, "grade": "A-",
     "desc": "PEO platform for small businesses handling payroll, benefits, and compliance. SOC2 certified."},
    {"name": "Lever", "slug": "lever", "score": 76, "grade": "B+",
     "desc": "Talent acquisition suite for hiring teams. Acquired by Employ Inc."},
    {"name": "Greenhouse", "slug": "greenhouse", "score": 80, "grade": "A-",
     "desc": "Hiring platform and applicant tracking system for growing companies. SOC2 Type II certified."},
    {"name": "Breezy HR", "slug": "breezy-hr", "score": 70, "grade": "B",
     "desc": "Applicant tracking system and recruiting software for small businesses."},
    {"name": "Factorial", "slug": "factorial-hr", "score": 74, "grade": "B",
     "desc": "HR software for small and medium businesses. Spanish company, growing in Europe."},

    # ── CRM ───────────────────────────────────────────────────────────────
    {"name": "Salesforce", "slug": "salesforce", "score": 92, "grade": "A+",
     "desc": "World's largest CRM platform for sales, service, and marketing. Public company (CRM), SOC2/ISO 27001 certified."},
    {"name": "HubSpot CRM", "slug": "hubspot-crm", "score": 88, "grade": "A",
     "desc": "Free CRM platform with marketing, sales, and service hubs. Public company (HUBS), SOC2 certified."},
    {"name": "Pipedrive", "slug": "pipedrive", "score": 80, "grade": "A-",
     "desc": "Sales CRM and pipeline management tool for small teams. SOC2 Type II certified."},
    {"name": "Freshsales", "slug": "freshsales", "score": 79, "grade": "B+",
     "desc": "CRM software by Freshworks with AI-powered features. Part of Freshworks (FRSH), SOC2 certified."},
    {"name": "Close", "slug": "close-crm", "score": 76, "grade": "B+",
     "desc": "CRM platform built for inside sales teams with built-in calling and email."},
    {"name": "Copper", "slug": "copper-crm", "score": 74, "grade": "B",
     "desc": "CRM designed for Google Workspace users. Tight Gmail and Calendar integration."},
    {"name": "Zoho CRM", "slug": "zoho-crm", "score": 82, "grade": "A-",
     "desc": "CRM platform part of Zoho suite. Indian company, SOC2/ISO 27001 certified, 250K+ customers."},
    {"name": "Insightly", "slug": "insightly", "score": 74, "grade": "B",
     "desc": "CRM and project management platform for small businesses. Unified customer data approach."},
    {"name": "Keap (Infusionsoft)", "slug": "keap", "score": 72, "grade": "B",
     "desc": "CRM and marketing automation for small businesses. Rebranded from Infusionsoft."},
    {"name": "Nimble", "slug": "nimble-crm", "score": 70, "grade": "B",
     "desc": "Social CRM for individuals and teams. Integrates with Office 365 and Google Workspace."},
    {"name": "Nutshell", "slug": "nutshell-crm", "score": 72, "grade": "B",
     "desc": "CRM and email marketing platform for small businesses. Ann Arbor-based company."},
    {"name": "Less Annoying CRM", "slug": "less-annoying-crm", "score": 74, "grade": "B",
     "desc": "Simple CRM for small businesses. Low-cost, no contracts, focused on simplicity."},
    {"name": "Streak", "slug": "streak-crm", "score": 70, "grade": "B",
     "desc": "CRM built directly inside Gmail. Lightweight CRM for email-centric workflows."},

    # ── Support ───────────────────────────────────────────────────────────
    {"name": "Zendesk", "slug": "zendesk", "score": 88, "grade": "A",
     "desc": "Customer service and engagement platform. Taken private by investment group in 2022, SOC2/ISO 27001 certified."},
    {"name": "Intercom", "slug": "intercom", "score": 84, "grade": "A-",
     "desc": "Customer messaging platform with live chat, bots, and help desk. SOC2 Type II certified."},
    {"name": "Freshdesk", "slug": "freshdesk", "score": 82, "grade": "A-",
     "desc": "Customer support software by Freshworks. Part of Freshworks (FRSH), SOC2 certified."},
    {"name": "Help Scout", "slug": "help-scout", "score": 80, "grade": "A-",
     "desc": "Help desk and customer support platform for growing businesses. SOC2 Type II certified."},
    {"name": "Crisp", "slug": "crisp", "score": 72, "grade": "B",
     "desc": "Customer messaging platform with live chat, chatbot, and knowledge base. French company."},
    {"name": "Tawk.to", "slug": "tawk-to", "score": 70, "grade": "B",
     "desc": "Free live chat application for websites. Monetized through hired agents service."},
    {"name": "LiveChat", "slug": "livechat", "score": 78, "grade": "B+",
     "desc": "Customer service platform with live chat for websites. Polish public company (LVC)."},
    {"name": "Drift", "slug": "drift", "score": 78, "grade": "B+",
     "desc": "Conversational marketing and sales platform. Acquired by Salesloft in 2024."},
    {"name": "Tidio", "slug": "tidio", "score": 72, "grade": "B",
     "desc": "Live chat and chatbot platform for small businesses. Polish company, AI-powered responses."},
    {"name": "Front", "slug": "front-app", "score": 78, "grade": "B+",
     "desc": "Customer operations platform combining email, chat, and CRM. SOC2 Type II certified."},
    {"name": "Kayako", "slug": "kayako", "score": 66, "grade": "B-",
     "desc": "Customer service platform with shared inbox and live chat. Acquired by ESW Capital."},
    {"name": "Gorgias", "slug": "gorgias", "score": 76, "grade": "B+",
     "desc": "Customer support helpdesk for e-commerce stores. Deep Shopify integration."},
    {"name": "Re:amaze", "slug": "reamaze", "score": 72, "grade": "B",
     "desc": "Customer support platform for online businesses. Owned by GoDaddy."},

    # ── Database/Backend ──────────────────────────────────────────────────
    {"name": "Firebase", "slug": "firebase", "score": 90, "grade": "A+",
     "desc": "App development platform by Google with real-time database and authentication. SOC2/ISO 27001 certified."},
    {"name": "MongoDB Atlas", "slug": "mongodb-atlas", "score": 88, "grade": "A",
     "desc": "Cloud-hosted MongoDB database service. Public company (MDB), SOC2/ISO 27001 certified."},
    {"name": "Redis Cloud", "slug": "redis-cloud", "score": 84, "grade": "A-",
     "desc": "Managed Redis database service by Redis Inc. SOC2 Type II certified."},
    {"name": "Elastic Cloud", "slug": "elastic-cloud", "score": 85, "grade": "A",
     "desc": "Managed Elasticsearch, Kibana, and observability platform. Public company (ESTC), SOC2 certified."},
    {"name": "Hasura", "slug": "hasura", "score": 78, "grade": "B+",
     "desc": "Instant GraphQL APIs on databases with real-time capabilities. SOC2 Type II certified."},
    {"name": "Appwrite", "slug": "appwrite", "score": 74, "grade": "B",
     "desc": "Open-source backend-as-a-service platform for web and mobile apps. Self-hosted and cloud options."},
    {"name": "Fauna", "slug": "fauna", "score": 72, "grade": "B",
     "desc": "Serverless document-relational database. Distributed globally, SOC2 Type II certified."},
    {"name": "CockroachDB", "slug": "cockroachdb", "score": 82, "grade": "A-",
     "desc": "Distributed SQL database for cloud-native applications. SOC2 Type II certified, open-source core."},
    {"name": "Upstash", "slug": "upstash", "score": 76, "grade": "B+",
     "desc": "Serverless Redis and Kafka with per-request pricing. SOC2 Type II certified."},
    {"name": "Convex", "slug": "convex", "score": 72, "grade": "B",
     "desc": "Backend-as-a-service with reactive database and serverless functions. Growing developer platform."},
    {"name": "Xata", "slug": "xata", "score": 70, "grade": "B",
     "desc": "Serverless database platform with built-in search and analytics. Berlin-based startup."},
    {"name": "Turso", "slug": "turso", "score": 72, "grade": "B",
     "desc": "Edge-hosted distributed database based on libSQL (SQLite fork). SOC2 certified."},
    {"name": "Tigris Data", "slug": "tigris-data", "score": 66, "grade": "B-",
     "desc": "Globally distributed object storage service built on FoundationDB. Early-stage startup."},

    # ── Project Management ────────────────────────────────────────────────
    {"name": "Jira", "slug": "jira", "score": 88, "grade": "A",
     "desc": "Issue and project tracking software by Atlassian. Public company (TEAM), SOC2/ISO 27001 certified."},
    {"name": "Confluence", "slug": "confluence", "score": 86, "grade": "A",
     "desc": "Team wiki and knowledge management platform by Atlassian. SOC2/ISO 27001 certified."},
    {"name": "Basecamp", "slug": "basecamp", "score": 78, "grade": "B+",
     "desc": "Project management and team communication tool. Independent company, bootstrapped, privacy-focused."},
    {"name": "Teamwork", "slug": "teamwork", "score": 76, "grade": "B+",
     "desc": "Project management platform for client work. Irish company, SOC2 certified."},
    {"name": "Wrike", "slug": "wrike", "score": 82, "grade": "A-",
     "desc": "Collaborative work management platform. Owned by Citrix, SOC2/ISO 27001 certified."},
    {"name": "Smartsheet", "slug": "smartsheet", "score": 85, "grade": "A",
     "desc": "Work management and automation platform. Public company (SMAR), SOC2/ISO 27001/FedRAMP certified."},
    {"name": "Shortcut (Clubhouse)", "slug": "shortcut", "score": 74, "grade": "B",
     "desc": "Project management platform for software teams. Rebranded from Clubhouse, SOC2 certified."},
    {"name": "Height", "slug": "height-app", "score": 68, "grade": "B-",
     "desc": "Autonomous project management tool with AI features. Startup with modern task management approach."},
    {"name": "Plane", "slug": "plane-project", "score": 70, "grade": "B",
     "desc": "Open-source project planning tool. Alternative to Jira with modern UI and self-hosted option."},
    {"name": "Hive", "slug": "hive-project", "score": 72, "grade": "B",
     "desc": "Project management platform with flexible views and AI features."},
    {"name": "Zoho Projects", "slug": "zoho-projects", "score": 78, "grade": "B+",
     "desc": "Project management software by Zoho. Part of Zoho suite, SOC2/ISO 27001 certified."},
    {"name": "Notion (PM)", "slug": "notion-pm", "score": 82, "grade": "A-",
     "desc": "Project management capabilities within Notion workspace. Popular for flexible project tracking."},
    {"name": "Range", "slug": "range-co", "score": 64, "grade": "C+",
     "desc": "Team coordination tool with async standups and check-ins. Small startup."},

    # ── Video/Streaming ───────────────────────────────────────────────────
    {"name": "Vimeo", "slug": "vimeo", "score": 82, "grade": "A-",
     "desc": "Video hosting and streaming platform for businesses. Public company (VMEO), SOC2 certified."},
    {"name": "Riverside", "slug": "riverside", "score": 76, "grade": "B+",
     "desc": "Remote podcast and video recording platform with local recording quality."},
    {"name": "Descript", "slug": "descript", "score": 78, "grade": "B+",
     "desc": "Video and podcast editing platform with AI-powered tools. Edit video by editing text."},
    {"name": "StreamYard", "slug": "streamyard", "score": 74, "grade": "B",
     "desc": "Browser-based live streaming studio for multistreaming. Acquired by Hopin."},
    {"name": "Restream", "slug": "restream", "score": 72, "grade": "B",
     "desc": "Multi-platform live streaming service broadcasting to 30+ channels simultaneously."},
    {"name": "Wistia", "slug": "wistia", "score": 78, "grade": "B+",
     "desc": "Video hosting and marketing platform for businesses. Privacy-focused, no third-party tracking."},
    {"name": "Mux", "slug": "mux", "score": 80, "grade": "A-",
     "desc": "Video infrastructure API for developers. SOC2 Type II certified, used by major streaming services."},
    {"name": "Cloudinary", "slug": "cloudinary", "score": 82, "grade": "A-",
     "desc": "Cloud-based media management platform for images and video. SOC2/ISO 27001 certified."},
    {"name": "Vidyard", "slug": "vidyard", "score": 74, "grade": "B",
     "desc": "Video hosting and analytics platform for business. SOC2 Type II certified."},
    {"name": "Brightcove", "slug": "brightcove", "score": 80, "grade": "A-",
     "desc": "Enterprise video hosting and streaming platform. Public company (BCOV), SOC2 certified."},
    {"name": "Synthesia", "slug": "synthesia-saas", "score": 76, "grade": "B+",
     "desc": "AI video generation platform creating videos from text with virtual avatars."},
    {"name": "Kapwing", "slug": "kapwing", "score": 72, "grade": "B",
     "desc": "Online video editor and content creation platform. Browser-based, AI-powered features."},
    {"name": "InVideo", "slug": "invideo", "score": 70, "grade": "B",
     "desc": "Online video creation platform with templates and AI tools. Indian company."},
    {"name": "Canva Video", "slug": "canva-video", "score": 82, "grade": "A-",
     "desc": "Video editing capabilities within the Canva design platform."},

    # ── Education SaaS ────────────────────────────────────────────────────
    {"name": "Teachable", "slug": "teachable", "score": 78, "grade": "B+",
     "desc": "Online course creation and selling platform. Acquired by Hotmart."},
    {"name": "Thinkific", "slug": "thinkific", "score": 78, "grade": "B+",
     "desc": "Online course and digital product platform. Public company (THNC.V), SOC2 certified."},
    {"name": "Podia", "slug": "podia", "score": 74, "grade": "B",
     "desc": "All-in-one platform for selling online courses, downloads, and memberships."},
    {"name": "Kajabi", "slug": "kajabi", "score": 80, "grade": "A-",
     "desc": "All-in-one platform for online courses, coaching, and memberships. Premium pricing, established."},
    {"name": "LearnDash", "slug": "learndash", "score": 74, "grade": "B",
     "desc": "WordPress LMS plugin for creating and selling courses. Acquired by StellarWP (Liquid Web)."},
    {"name": "Skillshare", "slug": "skillshare", "score": 76, "grade": "B+",
     "desc": "Online learning community for creative skills. Subscription-based platform."},
    {"name": "Udemy Business", "slug": "udemy-business", "score": 82, "grade": "A-",
     "desc": "Enterprise learning platform by Udemy. Public company (UDMY), SOC2 certified."},
    {"name": "Coursera for Business", "slug": "coursera-business", "score": 84, "grade": "A-",
     "desc": "Enterprise online learning platform. Public company (COUR), partnered with top universities."},
    {"name": "Mighty Networks", "slug": "mighty-networks", "score": 72, "grade": "B",
     "desc": "Community and course platform for creators and brands. Combines courses with community."},
    {"name": "Circle", "slug": "circle-community", "score": 74, "grade": "B",
     "desc": "Community platform for creators, brands, and businesses. Growing alternative to Facebook Groups."},
    {"name": "Skool", "slug": "skool", "score": 72, "grade": "B",
     "desc": "Community and course platform combining community features with gamification."},
    {"name": "Graphy", "slug": "graphy", "score": 66, "grade": "B-",
     "desc": "Online course and community platform. Indian company, affordable pricing for creators."},
    {"name": "LearnWorlds", "slug": "learnworlds", "score": 74, "grade": "B",
     "desc": "Online course platform with interactive video and course builder. Greek company."},

    # ── Forms/Surveys ─────────────────────────────────────────────────────
    {"name": "Typeform", "slug": "typeform", "score": 80, "grade": "A-",
     "desc": "Online form builder and survey platform with conversational interface. SOC2 Type II certified."},
    {"name": "JotForm", "slug": "jotform", "score": 78, "grade": "B+",
     "desc": "Online form builder with drag-and-drop interface and payment integrations. SOC2 certified."},
    {"name": "SurveyMonkey", "slug": "surveymonkey", "score": 84, "grade": "A-",
     "desc": "Online survey and forms platform. Part of Momentive (acquired by Symphony Technology Group)."},
    {"name": "Google Forms", "slug": "google-forms", "score": 89, "grade": "A",
     "desc": "Free online form and survey builder by Google. Part of Google Workspace, SOC2 certified."},
    {"name": "Tally", "slug": "tally", "score": 74, "grade": "B",
     "desc": "Free online form builder with no-code approach. Belgian startup, generous free tier."},
    {"name": "Arengu", "slug": "arengu", "score": 64, "grade": "C+",
     "desc": "Low-code form builder for sign-up flows and authentication. Spanish startup."},
    {"name": "Paperform", "slug": "paperform", "score": 72, "grade": "B",
     "desc": "Online form builder with payment processing and e-commerce capabilities. Australian company."},
    {"name": "Formstack", "slug": "formstack", "score": 76, "grade": "B+",
     "desc": "Workplace productivity platform with forms, documents, and e-signatures. SOC2 certified."},
    {"name": "Cognito Forms", "slug": "cognito-forms", "score": 72, "grade": "B",
     "desc": "Online form builder with calculations, payments, and conditional logic."},
    {"name": "Fillout", "slug": "fillout", "score": 68, "grade": "B-",
     "desc": "Form builder for Notion, Airtable, and other databases. Y Combinator-backed startup."},
    {"name": "Formbricks", "slug": "formbricks", "score": 68, "grade": "B-",
     "desc": "Open-source survey and forms platform. Self-hosted option, GDPR compliant."},
    {"name": "Qualtrics", "slug": "qualtrics", "score": 88, "grade": "A",
     "desc": "Enterprise experience management platform for surveys and research. Owned by Silver Lake/CPPIB, SOC2/FedRAMP."},

    # ── Scheduling ────────────────────────────────────────────────────────
    {"name": "Calendly", "slug": "calendly", "score": 84, "grade": "A-",
     "desc": "Online appointment scheduling software. SOC2 Type II certified, 20M+ users."},
    {"name": "Cal.com", "slug": "cal-com", "score": 76, "grade": "B+",
     "desc": "Open-source scheduling platform. Self-hosted option, alternative to Calendly."},
    {"name": "Acuity Scheduling", "slug": "acuity-scheduling", "score": 78, "grade": "B+",
     "desc": "Online appointment scheduling for businesses. Owned by Squarespace."},
    {"name": "SavvyCal", "slug": "savvycal", "score": 70, "grade": "B",
     "desc": "Scheduling tool designed for personalized meeting booking. Small independent product."},
    {"name": "TidyCal", "slug": "tidycal", "score": 66, "grade": "B-",
     "desc": "Simple scheduling tool with lifetime deal option. Made by AppSumo team."},
    {"name": "Doodle", "slug": "doodle", "score": 76, "grade": "B+",
     "desc": "Scheduling platform for finding meeting times with groups. Swiss company."},
    {"name": "Reclaim.ai", "slug": "reclaim-ai", "score": 72, "grade": "B",
     "desc": "AI-powered calendar management and scheduling tool. Acquired by Dropbox in 2024."},
    {"name": "Clockwise", "slug": "clockwise", "score": 72, "grade": "B",
     "desc": "AI-powered calendar management for optimizing schedules. Shut down operations in 2024."},
    {"name": "YouCanBookMe", "slug": "youcanbook-me", "score": 70, "grade": "B",
     "desc": "Online scheduling tool for booking appointments. UK-based company."},
    {"name": "Chili Piper", "slug": "chili-piper", "score": 76, "grade": "B+",
     "desc": "Scheduling and routing platform for sales teams. SOC2 Type II certified."},

    # ── Additional Productivity/Business Tools ────────────────────────────
    {"name": "Microsoft 365", "slug": "microsoft-365", "score": 93, "grade": "A+",
     "desc": "Suite of productivity applications including Word, Excel, and PowerPoint. Microsoft (MSFT), SOC2/ISO 27001/FedRAMP."},
    {"name": "Google Workspace", "slug": "google-workspace", "score": 93, "grade": "A+",
     "desc": "Cloud-based productivity suite with Gmail, Drive, Docs, and Meet. Alphabet (GOOGL), SOC2/ISO 27001/FedRAMP."},
    {"name": "Zoho", "slug": "zoho", "score": 84, "grade": "A-",
     "desc": "Suite of online productivity and business applications. Indian company, SOC2/ISO 27001 certified, 100M+ users."},
    {"name": "Freshworks", "slug": "freshworks", "score": 82, "grade": "A-",
     "desc": "Business software suite for customer service, IT, and CRM. Public company (FRSH), SOC2/ISO 27001 certified."},
    {"name": "DocuSign", "slug": "docusign", "score": 88, "grade": "A",
     "desc": "Electronic signature and agreement management platform. Public company (DOCU), SOC2/ISO 27001 certified."},
    {"name": "HelloSign (Dropbox Sign)", "slug": "hellosign", "score": 82, "grade": "A-",
     "desc": "Electronic signature platform. Acquired by Dropbox, SOC2 Type II certified."},
    {"name": "PandaDoc", "slug": "pandadoc", "score": 78, "grade": "B+",
     "desc": "Document automation platform with e-signatures, proposals, and contracts. SOC2 Type II certified."},
    {"name": "Loomly", "slug": "loomly", "score": 70, "grade": "B",
     "desc": "Social media management platform for marketing teams. Acquired by Traject (ASG)."},
    {"name": "Notion Calendar", "slug": "notion-calendar", "score": 78, "grade": "B+",
     "desc": "Calendar app integrated with Notion. Formerly Cron, acquired by Notion."},
    {"name": "Zapier", "slug": "zapier", "score": 86, "grade": "A",
     "desc": "Automation platform connecting 6000+ apps with no-code workflows. SOC2 Type II certified."},
    {"name": "Make (Integromat)", "slug": "make", "score": 80, "grade": "A-",
     "desc": "Visual automation platform for connecting apps and workflows. Rebranded from Integromat, SOC2 certified."},
    {"name": "n8n", "slug": "n8n", "score": 76, "grade": "B+",
     "desc": "Open-source workflow automation tool with self-hosted option. Fair-code licensed."},
    {"name": "IFTTT", "slug": "ifttt", "score": 74, "grade": "B",
     "desc": "Automation platform connecting devices and services with simple conditional logic."},
    {"name": "Power Automate", "slug": "power-automate", "score": 88, "grade": "A",
     "desc": "Low-code automation platform by Microsoft. Part of Power Platform, SOC2/ISO 27001 certified."},
    {"name": "Retool", "slug": "retool", "score": 80, "grade": "A-",
     "desc": "Low-code platform for building internal tools and dashboards. SOC2 Type II certified."},
    {"name": "Budibase", "slug": "budibase", "score": 70, "grade": "B",
     "desc": "Open-source low-code platform for building internal tools. Self-hosted option available."},
    {"name": "Appsmith", "slug": "appsmith", "score": 72, "grade": "B",
     "desc": "Open-source framework for building internal tools and admin panels. Self-hosted and cloud."},
    {"name": "Bubble", "slug": "bubble", "score": 76, "grade": "B+",
     "desc": "No-code platform for building web applications. SOC2 Type II certified."},
    {"name": "Glide", "slug": "glide", "score": 72, "grade": "B",
     "desc": "No-code platform for creating apps from spreadsheets. Mobile and web app builder."},
    {"name": "Softr", "slug": "softr", "score": 68, "grade": "B-",
     "desc": "No-code platform for building web apps from Airtable and Google Sheets."},
    {"name": "Stacker", "slug": "stacker", "score": 66, "grade": "B-",
     "desc": "No-code platform for building business apps on top of spreadsheets and databases."},
    {"name": "Webflow", "slug": "webflow-cms", "score": 80, "grade": "A-",
     "desc": "CMS and website design platform enabling visual development without code. SOC2 Type II certified."},
    {"name": "Contentful", "slug": "contentful", "score": 82, "grade": "A-",
     "desc": "Headless CMS platform for managing content across channels. SOC2/ISO 27001 certified."},
    {"name": "Sanity", "slug": "sanity-cms", "score": 78, "grade": "B+",
     "desc": "Composable content platform and headless CMS. Norwegian company, developer-focused."},
    {"name": "Strapi", "slug": "strapi", "score": 76, "grade": "B+",
     "desc": "Open-source headless CMS with REST and GraphQL APIs. Self-hosted and cloud options."},
    {"name": "DatoCMS", "slug": "datocms", "score": 74, "grade": "B",
     "desc": "Headless CMS with real-time collaboration and structured content. Italian company."},
    {"name": "Storyblok", "slug": "storyblok", "score": 76, "grade": "B+",
     "desc": "Headless CMS with visual editor for content management. Austrian company, SOC2 certified."},
    {"name": "Hygraph", "slug": "hygraph", "score": 74, "grade": "B",
     "desc": "Federated content platform and headless CMS. German company, formerly GraphCMS."},
    {"name": "Builder.io CMS", "slug": "builder-io-cms", "score": 72, "grade": "B",
     "desc": "Visual headless CMS for building pages with drag-and-drop editor."},
    {"name": "Prismic", "slug": "prismic", "score": 74, "grade": "B",
     "desc": "Headless website builder and CMS. French company, focused on marketing sites."},
    {"name": "Directus", "slug": "directus", "score": 74, "grade": "B",
     "desc": "Open-source data platform and headless CMS wrapping SQL databases. Self-hosted and cloud."},
    {"name": "Ghost (CMS)", "slug": "ghost-cms", "score": 76, "grade": "B+",
     "desc": "Open-source headless CMS and publishing platform. Non-profit foundation, Node.js-based."},
    {"name": "KeystoneJS", "slug": "keystonejs", "score": 70, "grade": "B",
     "desc": "Open-source headless CMS and GraphQL API framework built with Node.js. Thinkmill."},

    # ── Additional Collaboration ──────────────────────────────────────────
    {"name": "Mural", "slug": "mural", "score": 80, "grade": "A-",
     "desc": "Digital workspace for visual collaboration and brainstorming. SOC2/ISO 27001 certified."},
    {"name": "FigJam", "slug": "figjam", "score": 82, "grade": "A-",
     "desc": "Collaborative whiteboarding tool by Figma for brainstorming and workshops."},
    {"name": "Excalidraw", "slug": "excalidraw", "score": 74, "grade": "B",
     "desc": "Open-source virtual whiteboard for sketching hand-drawn-like diagrams. Browser-based."},
    {"name": "Pitch", "slug": "pitch", "score": 74, "grade": "B",
     "desc": "Collaborative presentation software for modern teams. German company."},
    {"name": "Beautiful.ai", "slug": "beautiful-ai", "score": 72, "grade": "B",
     "desc": "AI-powered presentation software with smart formatting. Automates slide design."},
    {"name": "Gamma", "slug": "gamma-app", "score": 70, "grade": "B",
     "desc": "AI-powered presentation and document creation tool. Generates presentations from prompts."},
    {"name": "Tome", "slug": "tome", "score": 68, "grade": "B-",
     "desc": "AI-powered storytelling and presentation format. Venture-backed startup."},
    {"name": "Prezi", "slug": "prezi", "score": 74, "grade": "B",
     "desc": "Presentation platform with zooming user interface. Hungarian company."},
    {"name": "Canva Presentations", "slug": "canva-presentations", "score": 82, "grade": "A-",
     "desc": "Presentation creation tool within the Canva design platform."},
    {"name": "Slite", "slug": "slite", "score": 70, "grade": "B",
     "desc": "Knowledge base and documentation tool for teams. French startup."},
    {"name": "Almanac", "slug": "almanac", "score": 66, "grade": "B-",
     "desc": "Document collaboration platform for modern work. Alternative to Google Docs for teams."},
    {"name": "GitBook", "slug": "gitbook", "score": 76, "grade": "B+",
     "desc": "Documentation platform for technical teams with Git-backed content."},
    {"name": "ReadMe", "slug": "readme", "score": 76, "grade": "B+",
     "desc": "Developer hub platform for API documentation. SOC2 Type II certified."},
    {"name": "Mintlify", "slug": "mintlify", "score": 72, "grade": "B",
     "desc": "Modern documentation platform for developer-facing companies. AI-powered search."},
    {"name": "Docsify", "slug": "docsify", "score": 68, "grade": "B-",
     "desc": "Open-source documentation site generator with no statically built HTML files."},

    # ── Miscellaneous SaaS ────────────────────────────────────────────────
    {"name": "Canva Docs", "slug": "canva-docs", "score": 82, "grade": "A-",
     "desc": "Visual document editor within the Canva platform for creating polished documents."},
    {"name": "1Password Developer", "slug": "1password-dev", "score": 88, "grade": "A",
     "desc": "Secrets management and developer tools by 1Password. SSH key management, CLI tools."},
    {"name": "Doppler", "slug": "doppler", "score": 78, "grade": "B+",
     "desc": "Secrets management platform for developers. SOC2 Type II certified."},
    {"name": "Vault (HashiCorp)", "slug": "hashicorp-vault", "score": 86, "grade": "A",
     "desc": "Secrets management and data protection platform. HashiCorp (HCP), SOC2/ISO 27001 certified."},
    {"name": "Vercel v0", "slug": "vercel-v0", "score": 74, "grade": "B",
     "desc": "AI-powered UI generation tool by Vercel. Creates React components from prompts."},
    {"name": "Algolia", "slug": "algolia", "score": 84, "grade": "A-",
     "desc": "Search-as-a-service API platform for websites and apps. SOC2/ISO 27001 certified."},
    {"name": "Typesense", "slug": "typesense", "score": 74, "grade": "B",
     "desc": "Open-source search engine with typo tolerance. Self-hosted and cloud options."},
    {"name": "Meilisearch", "slug": "meilisearch", "score": 74, "grade": "B",
     "desc": "Open-source search engine with instant search capabilities. French company, Rust-based."},
    {"name": "imgix", "slug": "imgix", "score": 78, "grade": "B+",
     "desc": "Real-time image processing and CDN platform. SOC2 Type II certified."},
    {"name": "Transloadit", "slug": "transloadit", "score": 72, "grade": "B",
     "desc": "File uploading and processing API service. German company, powers tus.io protocol."},
    {"name": "Uploadthing", "slug": "uploadthing", "score": 68, "grade": "B-",
     "desc": "File upload solution for TypeScript/Next.js applications. Developer-focused."},
    {"name": "Clerk", "slug": "clerk", "score": 78, "grade": "B+",
     "desc": "Authentication and user management platform for developers. SOC2 Type II certified."},
    {"name": "Stytch", "slug": "stytch", "score": 76, "grade": "B+",
     "desc": "Authentication infrastructure for developers with passwordless and MFA options. SOC2 certified."},
    {"name": "WorkOS", "slug": "workos", "score": 76, "grade": "B+",
     "desc": "Enterprise authentication APIs for SSO, SCIM, and directory sync. SOC2 Type II certified."},
    {"name": "Descope", "slug": "descope", "score": 72, "grade": "B",
     "desc": "Authentication and user management platform with drag-and-drop workflows."},
    {"name": "Resend", "slug": "resend", "score": 72, "grade": "B",
     "desc": "Email API for developers built with modern stack. Created by former Vercel team member."},
    {"name": "Loops", "slug": "loops", "score": 66, "grade": "B-",
     "desc": "Email platform for SaaS companies. Focused on transactional and marketing emails."},
    {"name": "Customer.io", "slug": "customer-io", "score": 78, "grade": "B+",
     "desc": "Customer engagement platform for messaging automation. SOC2 Type II certified."},
    {"name": "Iterable", "slug": "iterable", "score": 80, "grade": "A-",
     "desc": "Cross-channel marketing automation platform. SOC2 Type II certified."},
    {"name": "OneSignal", "slug": "onesignal", "score": 76, "grade": "B+",
     "desc": "Push notification and messaging platform for mobile and web. SOC2 Type II certified."},
    {"name": "Knock", "slug": "knock", "score": 70, "grade": "B",
     "desc": "Notification infrastructure for developers. Multi-channel notification system."},
    {"name": "Novu", "slug": "novu", "score": 68, "grade": "B-",
     "desc": "Open-source notification infrastructure for developers. Self-hosted and cloud options."},
    {"name": "LaunchDarkly", "slug": "launchdarkly-fm", "score": 82, "grade": "A-",
     "desc": "Feature management platform for controlled feature rollouts. SOC2 Type II certified."},
    {"name": "Split.io", "slug": "split-io", "score": 78, "grade": "B+",
     "desc": "Feature delivery and experimentation platform. Acquired by Harness. SOC2 certified."},
    {"name": "Flagsmith", "slug": "flagsmith", "score": 70, "grade": "B",
     "desc": "Open-source feature flag and remote config service. Self-hosted and cloud options."},
    {"name": "ConfigCat", "slug": "configcat", "score": 70, "grade": "B",
     "desc": "Feature flag service with config management. Hungarian company, simple pricing."},
    {"name": "Unleash", "slug": "unleash", "score": 72, "grade": "B",
     "desc": "Open-source feature flag management platform. Norwegian company, self-hosted option."},
    {"name": "StatusPage (Atlassian)", "slug": "statuspage", "score": 84, "grade": "A-",
     "desc": "Status page and incident communication platform. Part of Atlassian, SOC2 certified."},
    {"name": "Better Uptime (Betterstack)", "slug": "betterstack", "score": 76, "grade": "B+",
     "desc": "Uptime monitoring and status page platform. Czech company, modern observability tools."},
    {"name": "UptimeRobot", "slug": "uptimerobot", "score": 74, "grade": "B",
     "desc": "Website monitoring service checking uptime every 5 minutes. Free tier with 50 monitors."},
    {"name": "Instatus", "slug": "instatus", "score": 68, "grade": "B-",
     "desc": "Status page platform with fast performance. Simple and affordable alternative to StatusPage."},
    {"name": "Cronitor", "slug": "cronitor", "score": 72, "grade": "B",
     "desc": "Monitoring platform for cron jobs, heartbeats, and application health checks."},
    {"name": "Checkly", "slug": "checkly", "score": 76, "grade": "B+",
     "desc": "Monitoring-as-code platform for API and browser checks. SOC2 Type II certified."},
    {"name": "Grafana Cloud", "slug": "grafana-cloud", "score": 84, "grade": "A-",
     "desc": "Managed observability platform with dashboards and alerting. SOC2/ISO 27001 certified."},
    {"name": "Prometheus Cloud", "slug": "prometheus-cloud", "score": 80, "grade": "A-",
     "desc": "Managed Prometheus monitoring service. CNCF graduated project, various cloud providers."},
    {"name": "Axiom", "slug": "axiom", "score": 74, "grade": "B",
     "desc": "Log management and observability platform with unlimited data retention. Developer-focused."},
    {"name": "Highlight.io", "slug": "highlight-io", "score": 70, "grade": "B",
     "desc": "Open-source session replay, error monitoring, and logging platform."},
    {"name": "Papertrail", "slug": "papertrail", "score": 76, "grade": "B+",
     "desc": "Cloud-hosted log management service. Owned by SolarWinds, SOC2 certified."},
    {"name": "LogDNA (Mezmo)", "slug": "mezmo", "score": 74, "grade": "B",
     "desc": "Log management and observability platform. Rebranded from LogDNA to Mezmo."},

    # ── Accounting/Finance SaaS ───────────────────────────────────────────
    {"name": "QuickBooks Online", "slug": "quickbooks-online", "score": 90, "grade": "A+",
     "desc": "Cloud-based accounting software for small businesses. Owned by Intuit (INTU), SOC2 certified."},
    {"name": "Xero", "slug": "xero", "score": 86, "grade": "A",
     "desc": "Cloud accounting platform for small businesses. Public company (XRO.AX), SOC2/ISO 27001 certified."},
    {"name": "FreshBooks", "slug": "freshbooks", "score": 80, "grade": "A-",
     "desc": "Cloud accounting and invoicing software for freelancers and small businesses. SOC2 certified."},
    {"name": "Wave", "slug": "wave-accounting", "score": 74, "grade": "B",
     "desc": "Free accounting software for small businesses. Owned by H&R Block."},
    {"name": "Brex", "slug": "brex", "score": 82, "grade": "A-",
     "desc": "Corporate card and spend management platform for startups. SOC2 Type II certified."},
    {"name": "Ramp", "slug": "ramp", "score": 82, "grade": "A-",
     "desc": "Corporate card and expense management platform. SOC2 Type II certified."},
    {"name": "Expensify", "slug": "expensify", "score": 78, "grade": "B+",
     "desc": "Expense management and corporate card platform. Public company (EXFY), SOC2 certified."},
    {"name": "Bill.com", "slug": "bill-com", "score": 84, "grade": "A-",
     "desc": "Accounts payable and receivable automation platform. Public company (BILL), SOC2/ISO 27001 certified."},
    {"name": "Tipalti", "slug": "tipalti", "score": 80, "grade": "A-",
     "desc": "Global payables automation platform for mid-market companies. SOC2 Type II certified."},
    {"name": "Stripe Atlas", "slug": "stripe-atlas", "score": 86, "grade": "A",
     "desc": "Company formation and banking for internet startups by Stripe. Delaware C-corp in days."},

    # ── Legal/Compliance SaaS ─────────────────────────────────────────────
    {"name": "Ironclad", "slug": "ironclad", "score": 80, "grade": "A-",
     "desc": "Contract lifecycle management platform. SOC2 Type II certified, used by L'Oreal, Mastercard."},
    {"name": "Docusign CLM", "slug": "docusign-clm", "score": 86, "grade": "A",
     "desc": "Contract lifecycle management by DocuSign. Enterprise-grade, SOC2/ISO 27001 certified."},
    {"name": "Clio", "slug": "clio", "score": 80, "grade": "A-",
     "desc": "Legal practice management software for law firms. SOC2 Type II certified, 150K+ users."},
    {"name": "Notion for Legal", "slug": "notion-legal", "score": 78, "grade": "B+",
     "desc": "Legal team workspace using Notion for contracts, policies, and legal ops."},
    {"name": "Vanta", "slug": "vanta", "score": 82, "grade": "A-",
     "desc": "Security compliance automation platform for SOC2, ISO 27001, and HIPAA. SOC2 certified."},
    {"name": "Drata", "slug": "drata", "score": 82, "grade": "A-",
     "desc": "Compliance automation platform for SOC2, ISO 27001, HIPAA, and PCI DSS. SOC2 certified."},
    {"name": "Secureframe", "slug": "secureframe", "score": 80, "grade": "A-",
     "desc": "Security and compliance automation platform. SOC2 Type II certified."},
    {"name": "OneTrust", "slug": "onetrust", "score": 84, "grade": "A-",
     "desc": "Privacy, security, and governance platform. SOC2/ISO 27001 certified, used by 14K+ customers."},

    # ── Testing/QA SaaS ───────────────────────────────────────────────────
    {"name": "BrowserStack", "slug": "browserstack", "score": 82, "grade": "A-",
     "desc": "Cloud-based cross-browser testing platform. SOC2 Type II certified, used by 50K+ companies."},
    {"name": "Sauce Labs", "slug": "sauce-labs", "score": 80, "grade": "A-",
     "desc": "Cloud-based testing platform for web and mobile applications. SOC2 Type II certified."},
    {"name": "LambdaTest", "slug": "lambdatest", "score": 76, "grade": "B+",
     "desc": "Cloud cross-browser testing platform with 3000+ browser environments."},
    {"name": "Cypress Cloud", "slug": "cypress-cloud", "score": 78, "grade": "B+",
     "desc": "Test runner dashboard and CI/CD parallelization for Cypress tests. SOC2 certified."},
    {"name": "Playwright (Microsoft)", "slug": "playwright-cloud", "score": 84, "grade": "A-",
     "desc": "End-to-end testing framework by Microsoft with cloud reporting capabilities."},
    {"name": "Testim", "slug": "testim", "score": 74, "grade": "B",
     "desc": "AI-powered test automation platform. Acquired by Tricentis."},
    {"name": "Mabl", "slug": "mabl", "score": 76, "grade": "B+",
     "desc": "Intelligent test automation platform with AI-driven testing. SOC2 Type II certified."},

    # ── Translation/Localization ──────────────────────────────────────────
    {"name": "Phrase (Memsource)", "slug": "phrase", "score": 78, "grade": "B+",
     "desc": "Translation management platform for localization workflows. SOC2/ISO 27001 certified."},
    {"name": "Crowdin", "slug": "crowdin", "score": 76, "grade": "B+",
     "desc": "Localization management platform for software and content. Used by Microsoft, Uber."},
    {"name": "Lokalise", "slug": "lokalise", "score": 76, "grade": "B+",
     "desc": "Translation management system for software localization. SOC2 Type II certified."},
    {"name": "Transifex", "slug": "transifex", "score": 74, "grade": "B",
     "desc": "Localization and translation management platform. Used by Atlassian, Hubspot."},
    {"name": "Smartling", "slug": "smartling", "score": 78, "grade": "B+",
     "desc": "Translation management software for enterprises. SOC2 Type II certified."},

    # ── Diagramming/Visualization ─────────────────────────────────────────
    {"name": "Draw.io (diagrams.net)", "slug": "draw-io", "score": 78, "grade": "B+",
     "desc": "Free online diagram and flowchart editor. Open-source, owned by JGraph Ltd."},
    {"name": "Creately", "slug": "creately", "score": 70, "grade": "B",
     "desc": "Visual collaboration platform for diagramming and project management."},
    {"name": "Cacoo", "slug": "cacoo", "score": 68, "grade": "B-",
     "desc": "Online diagramming and collaboration tool by Nulab. Japanese company."},
    {"name": "Coggle", "slug": "coggle", "score": 66, "grade": "B-",
     "desc": "Online mind mapping and collaborative diagramming tool. UK-based."},
    {"name": "MindMeister", "slug": "mindmeister", "score": 72, "grade": "B",
     "desc": "Online mind mapping application for brainstorming and planning. German company (MeisterLabs)."},

    # ── Data Warehouse/BI ─────────────────────────────────────────────────
    {"name": "Snowflake", "slug": "snowflake", "score": 92, "grade": "A+",
     "desc": "Cloud data warehouse platform. Public company (SNOW), SOC2/ISO 27001/FedRAMP certified."},
    {"name": "Databricks", "slug": "databricks", "score": 90, "grade": "A+",
     "desc": "Unified analytics platform for data engineering and ML. SOC2/ISO 27001 certified."},
    {"name": "Tableau Online", "slug": "tableau-online", "score": 88, "grade": "A",
     "desc": "Cloud-based data visualization platform. Owned by Salesforce, SOC2/ISO 27001 certified."},
    {"name": "Looker", "slug": "looker", "score": 88, "grade": "A",
     "desc": "Business intelligence and data analytics platform. Owned by Google Cloud, SOC2 certified."},
    {"name": "Power BI", "slug": "power-bi", "score": 90, "grade": "A+",
     "desc": "Business intelligence and data visualization platform by Microsoft. SOC2/ISO 27001 certified."},
    {"name": "Metabase", "slug": "metabase", "score": 78, "grade": "B+",
     "desc": "Open-source business intelligence and analytics tool. Self-hosted and cloud options."},
    {"name": "Mode Analytics", "slug": "mode-analytics", "score": 76, "grade": "B+",
     "desc": "Collaborative analytics platform for data teams. Acquired by ThoughtSpot."},
    {"name": "Hex", "slug": "hex-analytics", "score": 76, "grade": "B+",
     "desc": "Collaborative data workspace for notebooks, SQL, and visualization."},
    {"name": "Sigma Computing", "slug": "sigma-computing", "score": 78, "grade": "B+",
     "desc": "Cloud-based spreadsheet analytics platform connected to data warehouses. SOC2 certified."},
    {"name": "Fivetran", "slug": "fivetran", "score": 84, "grade": "A-",
     "desc": "Automated data pipeline and ETL platform. SOC2 Type II certified."},
    {"name": "Airbyte", "slug": "airbyte", "score": 76, "grade": "B+",
     "desc": "Open-source data integration platform for ELT pipelines. Self-hosted and cloud options."},
    {"name": "Stitch Data", "slug": "stitch-data", "score": 74, "grade": "B",
     "desc": "Simple data integration platform. Owned by Talend (acquired by Qlik)."},
    {"name": "dbt Cloud", "slug": "dbt-cloud", "score": 82, "grade": "A-",
     "desc": "Cloud-hosted data transformation platform for analytics engineering. SOC2 Type II certified."},
    {"name": "Census", "slug": "census", "score": 74, "grade": "B",
     "desc": "Reverse ETL platform syncing data warehouse to business tools. SOC2 Type II certified."},
    {"name": "Hightouch", "slug": "hightouch", "score": 74, "grade": "B",
     "desc": "Reverse ETL and data activation platform. SOC2 Type II certified."},
    {"name": "Monte Carlo", "slug": "monte-carlo", "score": 78, "grade": "B+",
     "desc": "Data observability platform for monitoring data quality. SOC2 Type II certified."},

    # ── Customer Data/CDP ─────────────────────────────────────────────────
    {"name": "mParticle", "slug": "mparticle", "score": 80, "grade": "A-",
     "desc": "Customer data platform for real-time data integration. SOC2 Type II certified."},
    {"name": "RudderStack", "slug": "rudderstack", "score": 74, "grade": "B",
     "desc": "Open-source customer data platform for event streaming. Self-hosted and cloud options."},
    {"name": "Lytics", "slug": "lytics", "score": 72, "grade": "B",
     "desc": "Customer data platform for personalized marketing. SOC2 Type II certified."},
    {"name": "Treasure Data", "slug": "treasure-data", "score": 78, "grade": "B+",
     "desc": "Enterprise customer data platform. SOC2/ISO 27001 certified, Arm Holdings subsidiary."},

    # ── Additional Enterprise/Niche SaaS ──────────────────────────────────
    {"name": "ServiceNow", "slug": "servicenow", "score": 92, "grade": "A+",
     "desc": "Enterprise IT service management and workflow automation platform. Public company (NOW), SOC2/ISO 27001 certified."},
    {"name": "Atlassian", "slug": "atlassian", "score": 90, "grade": "A+",
     "desc": "Software development and collaboration suite including Jira, Confluence, and Trello. Public company (TEAM)."},
    {"name": "SAP Business Technology Platform", "slug": "sap-btp", "score": 91, "grade": "A+",
     "desc": "Enterprise application platform for analytics, AI, and integration. SAP SE (SAP), SOC2/ISO 27001 certified."},
    {"name": "Oracle Cloud", "slug": "oracle-cloud", "score": 90, "grade": "A+",
     "desc": "Enterprise cloud infrastructure and applications platform. Oracle (ORCL), SOC2/ISO 27001/FedRAMP certified."},
    {"name": "Twitch (Creator Tools)", "slug": "twitch-creator", "score": 82, "grade": "A-",
     "desc": "Live streaming platform with creator monetization tools. Owned by Amazon."},
    {"name": "Anchor (Spotify for Podcasters)", "slug": "spotify-podcasters", "score": 82, "grade": "A-",
     "desc": "Podcast creation and hosting platform. Owned by Spotify (SPOT)."},
    {"name": "Transistor.fm", "slug": "transistor-fm", "score": 72, "grade": "B",
     "desc": "Podcast hosting and analytics platform for businesses and creators."},
    {"name": "Buzzsprout", "slug": "buzzsprout", "score": 74, "grade": "B",
     "desc": "Podcast hosting platform making it easy to publish podcasts. Jacksonville-based company."},
    {"name": "Liveblocks", "slug": "liveblocks", "score": 70, "grade": "B",
     "desc": "Real-time collaboration infrastructure for developers. APIs for multiplayer experiences."},
    {"name": "Pusher", "slug": "pusher", "score": 76, "grade": "B+",
     "desc": "Real-time communication APIs for web and mobile applications. Acquired by MessageBird."},
    {"name": "Ably", "slug": "ably", "score": 78, "grade": "B+",
     "desc": "Real-time messaging infrastructure platform. SOC2 Type II certified."},
    {"name": "Stream", "slug": "stream-chat", "score": 78, "grade": "B+",
     "desc": "Chat and activity feed APIs for building real-time features. SOC2 Type II certified."},
    {"name": "Supabase Realtime", "slug": "supabase-realtime", "score": 76, "grade": "B+",
     "desc": "Real-time database subscriptions built on PostgreSQL. Part of Supabase open-source platform."},
    {"name": "Railway (Templates)", "slug": "railway-templates", "score": 72, "grade": "B",
     "desc": "One-click deploy templates for databases and services on Railway platform."},
    {"name": "Render Blueprints", "slug": "render-blueprints", "score": 74, "grade": "B",
     "desc": "Infrastructure-as-code for deploying multi-service applications on Render platform."},
]

assert len(SAAS) == 500, f"Expected 500 SaaS entries, got {len(SAAS)}"


def seed():
    """Upsert all SaaS entries into software_registry."""
    session = get_session()
    inserted = 0

    for s in SAAS:
        try:
            session.execute(text("""
                INSERT INTO software_registry
                    (name, slug, registry, description, trust_score, trust_grade,
                     enriched_at, created_at, security_score, popularity_score, is_king)
                VALUES
                    (:name, :slug, 'saas', :desc, :score, :grade,
                     NOW(), NOW(), :sec, :pop, true)
                ON CONFLICT (registry, slug) DO UPDATE SET
                    description = EXCLUDED.description,
                    trust_score = EXCLUDED.trust_score,
                    trust_grade = EXCLUDED.trust_grade,
                    security_score = EXCLUDED.security_score,
                    popularity_score = EXCLUDED.popularity_score,
                    is_king = true,
                    enriched_at = NOW()
            """), {
                "name": s["name"],
                "slug": s["slug"],
                "desc": s["desc"],
                "score": s["score"],
                "grade": s["grade"],
                "sec": s["score"],
                "pop": 85,
            })
            inserted += 1

        except Exception as e:
            log.error(f"Failed to upsert {s['name']}: {e}")
            session.rollback()
            continue

    session.commit()
    session.close()
    log.info(f"SaaS seed complete: {inserted} upserted")
    return inserted


if __name__ == "__main__":
    total = seed()
    log.info(f"Done. {total}/{len(SAAS)} SaaS entries seeded.")
