-- 2026-05-30 Phase 4 PREP-1: zarq.endpoint_usage_audit
-- Context: deprecation_logger middleware mounted on /crypto, /experiments and
-- /action prefixes (per Anders' F.1-F.3 answers). 14-day audit window before
-- any delete decision on those routes.
-- Idempotent: yes.

BEGIN;

CREATE TABLE IF NOT EXISTS zarq.endpoint_usage_audit (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint          text NOT NULL,
    method            text NOT NULL,
    user_agent        text,
    client_ip         inet,
    response_status   smallint,
    response_time_ms  integer,
    called_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_endpoint_usage_audit_endpoint_time
    ON zarq.endpoint_usage_audit (endpoint, called_at DESC);
CREATE INDEX IF NOT EXISTS idx_endpoint_usage_audit_called_at
    ON zarq.endpoint_usage_audit (called_at DESC);

COMMIT;


-- DOWN (manual; for reference)
-- DROP TABLE IF EXISTS zarq.endpoint_usage_audit;
