-- 2026-05-30 Backfill: identity defaults on 4 audit tables + 2 new observability tables.
-- Context: ADR-003a decision log + commits 2bce993 (multi-fix) and e4a1458 (healthcheck).
-- These DDLs were originally applied directly via psql during the 2026-05-29 ZARQ
-- recovery and the 2026-05-30 outage triage. This file backfills them into git so a
-- fresh database build receives them as part of the migration chain.
-- Idempotent: yes (every statement is safe to re-run against a DB where it already exists).

BEGIN;

-- ── 1. ADD GENERATED BY DEFAULT AS IDENTITY on the 4 zarq tables whose `id`
--    columns had no default. The baseline schema in
--    docs/migrations/zarq-tier-a-postgres.sql created them as plain INTEGER
--    NOT NULL, so dual-writes from SQLite (where the id is AUTOINCREMENT)
--    omitted the column and failed with "null value in column id".
--
--    The DO blocks check pg_attribute.attidentity ('d' = GENERATED BY DEFAULT,
--    'a' = ALWAYS, '' = none) so re-running on an already-fixed column is a
--    no-op rather than an error.

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'zarq.crypto_pipeline_runs'::regclass
          AND attname = 'id' AND attidentity = 'd'
    ) THEN
        ALTER TABLE zarq.crypto_pipeline_runs
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        PERFORM setval(
            pg_get_serial_sequence('zarq.crypto_pipeline_runs', 'id'),
            COALESCE((SELECT MAX(id) FROM zarq.crypto_pipeline_runs), 0) + 1,
            false
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'zarq.crypto_ndd_alerts'::regclass
          AND attname = 'id' AND attidentity = 'd'
    ) THEN
        ALTER TABLE zarq.crypto_ndd_alerts
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        PERFORM setval(
            pg_get_serial_sequence('zarq.crypto_ndd_alerts', 'id'),
            COALESCE((SELECT MAX(id) FROM zarq.crypto_ndd_alerts), 0) + 1,
            false
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'zarq.crypto_ndd_daily'::regclass
          AND attname = 'id' AND attidentity = 'd'
    ) THEN
        ALTER TABLE zarq.crypto_ndd_daily
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        PERFORM setval(
            pg_get_serial_sequence('zarq.crypto_ndd_daily', 'id'),
            COALESCE((SELECT MAX(id) FROM zarq.crypto_ndd_daily), 0) + 1,
            false
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'zarq.crypto_rating_daily'::regclass
          AND attname = 'id' AND attidentity = 'd'
    ) THEN
        ALTER TABLE zarq.crypto_rating_daily
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        PERFORM setval(
            pg_get_serial_sequence('zarq.crypto_rating_daily', 'id'),
            COALESCE((SELECT MAX(id) FROM zarq.crypto_rating_daily), 0) + 1,
            false
        );
    END IF;
END $$;

-- ── 2. zarq.dual_write_failures — observability for silent dual_write errors.
--    Created in commit 2bce993 (2026-05-29). Originally the dual_write helper
--    silently swallowed PG errors; this table captures them so future
--    regressions surface in PG, not just a file log.

CREATE TABLE IF NOT EXISTS zarq.dual_write_failures (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at  timestamptz NOT NULL DEFAULT now(),
    table_name   text NOT NULL,
    op           text NOT NULL,          -- EXECUTE | EXECUTEMANY | DELETE | EXECUTEMANY_NAMED
    row_count    int,                    -- nullable; only set for batches
    error_msg    text NOT NULL,
    sql_excerpt  text                    -- first 300 chars of translated SQL
);

CREATE INDEX IF NOT EXISTS idx_dual_write_failures_occurred
    ON zarq.dual_write_failures (occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_dual_write_failures_table
    ON zarq.dual_write_failures (table_name, occurred_at DESC);

-- ── 3. zarq.infrastructure_alerts — TCP-reachability surface for the periodic
--    infra healthcheck (scripts/infra_healthcheck.py + LaunchAgent every 5min).
--    Created during the 2026-05-30 outage triage. The partial unique index
--    on (host, port, service) WHERE resolved_at IS NULL keeps re-probes of a
--    still-failing target on a single row (bumping probe_count) instead of
--    inserting duplicates.

CREATE TABLE IF NOT EXISTS zarq.infrastructure_alerts (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host         text NOT NULL,
    port         int  NOT NULL,
    service      text NOT NULL,
    severity     text NOT NULL CHECK (severity IN ('warning', 'critical')),
    error_msg    text NOT NULL,
    occurred_at  timestamptz NOT NULL DEFAULT now(),
    resolved_at  timestamptz,
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    probe_count  int  NOT NULL DEFAULT 1
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_infra_alerts_open
    ON zarq.infrastructure_alerts (host, port, service)
    WHERE resolved_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_infra_alerts_occurred
    ON zarq.infrastructure_alerts (occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_infra_alerts_open_first
    ON zarq.infrastructure_alerts (resolved_at NULLS FIRST, occurred_at DESC);

COMMIT;


-- ───────────────────────────────────────────────────────────────────────────
-- DOWN (manual; for reference only — do not auto-run)
-- ───────────────────────────────────────────────────────────────────────────
-- BEGIN;
--
-- DROP TABLE IF EXISTS zarq.infrastructure_alerts;
-- DROP TABLE IF EXISTS zarq.dual_write_failures;
--
-- -- Removing identity defaults is reversible but losses are real: inserts
-- -- that relied on the default will start failing with "null value in column
-- -- id" again. Only do this if you also intend to revert the dual_write helper
-- -- and the daily-master code paths that omit the id column.
-- ALTER TABLE zarq.crypto_pipeline_runs ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE zarq.crypto_ndd_alerts    ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE zarq.crypto_ndd_daily     ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE zarq.crypto_rating_daily  ALTER COLUMN id DROP IDENTITY IF EXISTS;
--
-- COMMIT;
